"use client"

import React, { useState } from 'react';

// Datos de los bateadores (mantenidos igual)
const batters = [
  {
    nombre: "Emilio Bonifacio",
    edad: 39,
    pos: "CF",
    jj: 48,
    app: 217,
    ab: 189,
    c: 33,
    h: 55,
    b1: 43,
    b2: 7,
    b3: 4,
    hr: 1,
    rbi: 9,
    bb: 24,
    so: 26,
    sb: 13,
    cs: 3,
    avg: 0.291,
    obp: 0.369,
    slg: 0.386,
    ops: 0.755,
    opsp: 112,
    tb: 73,
    hbp: 0,
    ibb: 2,
    sf: 1,
    s: 3,
    dp: 3,
  },
  {
    nombre: "Sergio Alcántara",
    edad: 28,
    pos: "SS",
    jj: 40,
    app: 175,
    ab: 144,
    c: 20,
    h: 40,
    b1: 26,
    b2: 10,
    b3: 1,
    hr: 3,
    rbi: 22,
    bb: 26,
    so: 27,
    sb: 1,
    cs: 1,
    avg: 0.278,
    obp: 0.379,
    slg: 0.424,
    ops: 0.803,
    opsp: 119,
    tb: 61,
    hbp: 0,
    ibb: 0,
    sf: 4,
    s: 1,
    dp: 3,
  },
  {
    nombre: "Luis Barrera",
    edad: 29,
    pos: "PR",
    jj: 32,
    app: 46,
    ab: 41,
    c: 11,
    h: 8,
    b1: 5,
    b2: 2,
    b3: 1,
    hr: 0,
    rbi: 6,
    bb: 2,
    so: 8,
    sb: 6,
    cs: 0,
    avg: 0.195,
    obp: 0.227,
    slg: 0.293,
    ops: 0.52,
    opsp: 77,
    tb: 12,
    hbp: 0,
    ibb: 0,
    sf: 1,
    s: 2,
    dp: 0,
  },
  {
    nombre: "Dawel Lugo",
    edad: 30,
    pos: "3B",
    jj: 28,
    app: 104,
    ab: 100,
    c: 6,
    h: 28,
    b1: 23,
    b2: 3,
    b3: 1,
    hr: 1,
    rbi: 6,
    bb: 2,
    so: 14,
    sb: 0,
    cs: 1,
    avg: 0.28,
    obp: 0.288,
    slg: 0.36,
    ops: 0.648,
    opsp: 96,
    tb: 36,
    hbp: 0,
    ibb: 1,
    sf: 2,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Jordan Lawlar",
    edad: 22,
    pos: "SS",
    jj: 27,
    app: 108,
    ab: 93,
    c: 9,
    h: 22,
    b1: 17,
    b2: 2,
    b3: 0,
    hr: 3,
    rbi: 14,
    bb: 9,
    so: 32,
    sb: 9,
    cs: 1,
    avg: 0.237,
    obp: 0.315,
    slg: 0.355,
    ops: 0.67,
    opsp: 99,
    tb: 33,
    hbp: 3,
    ibb: 0,
    sf: 3,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Jair Camargo",
    edad: 25,
    pos: "C",
    jj: 26,
    app: 106,
    ab: 99,
    c: 11,
    h: 32,
    b1: 21,
    b2: 8,
    b3: 0,
    hr: 3,
    rbi: 15,
    bb: 3,
    so: 34,
    sb: 1,
    cs: 1,
    avg: 0.323,
    obp: 0.358,
    slg: 0.495,
    ops: 0.853,
    opsp: 126,
    tb: 49,
    hbp: 3,
    ibb: 0,
    sf: 1,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Ramón Hernández",
    edad: 28,
    pos: "1B",
    jj: 24,
    app: 88,
    ab: 72,
    c: 8,
    h: 18,
    b1: 10,
    b2: 5,
    b3: 0,
    hr: 3,
    rbi: 10,
    bb: 13,
    so: 24,
    sb: 1,
    cs: 1,
    avg: 0.25,
    obp: 0.375,
    slg: 0.444,
    ops: 0.819,
    opsp: 121,
    tb: 32,
    hbp: 2,
    ibb: 1,
    sf: 1,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Daniel Johnson",
    edad: 29,
    pos: "LF",
    jj: 23,
    app: 101,
    ab: 96,
    c: 10,
    h: 22,
    b1: 17,
    b2: 3,
    b3: 1,
    hr: 1,
    rbi: 12,
    bb: 3,
    so: 16,
    sb: 3,
    cs: 2,
    avg: 0.229,
    obp: 0.248,
    slg: 0.313,
    ops: 0.561,
    opsp: 83,
    tb: 30,
    hbp: 0,
    ibb: 0,
    sf: 2,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Francisco Mejía",
    edad: 29,
    pos: "C",
    jj: 23,
    app: 83,
    ab: 73,
    c: 5,
    h: 15,
    b1: 9,
    b2: 6,
    b3: 0,
    hr: 0,
    rbi: 13,
    bb: 5,
    so: 5,
    sb: 2,
    cs: 0,
    avg: 0.205,
    obp: 0.277,
    slg: 0.288,
    ops: 0.565,
    opsp: 83,
    tb: 21,
    hbp: 3,
    ibb: 0,
    sf: 2,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Arístides Aquino",
    edad: 30,
    pos: "LF",
    jj: 22,
    app: 52,
    ab: 49,
    c: 5,
    h: 8,
    b1: 4,
    b2: 0,
    b3: 1,
    hr: 3,
    rbi: 8,
    bb: 2,
    so: 19,
    sb: 1,
    cs: 0,
    avg: 0.163,
    obp: 0.192,
    slg: 0.388,
    ops: 0.58,
    opsp: 86,
    tb: 19,
    hbp: 0,
    ibb: 0,
    sf: 1,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Domingo Leyba",
    edad: 29,
    pos: "2B",
    jj: 21,
    app: 77,
    ab: 56,
    c: 7,
    h: 15,
    b1: 12,
    b2: 1,
    b3: 0,
    hr: 2,
    rbi: 10,
    bb: 17,
    so: 15,
    sb: 0,
    cs: 0,
    avg: 0.268,
    obp: 0.432,
    slg: 0.393,
    ops: 0.825,
    opsp: 122,
    tb: 22,
    hbp: 0,
    ibb: 0,
    sf: 1,
    s: 3,
    dp: 1,
  },
  {
    nombre: "Angel Ortiz",
    edad: 22,
    pos: "LF",
    jj: 20,
    app: 67,
    ab: 58,
    c: 10,
    h: 16,
    b1: 10,
    b2: 3,
    b3: 1,
    hr: 2,
    rbi: 7,
    bb: 8,
    so: 18,
    sb: 0,
    cs: 0,
    avg: 0.276,
    obp: 0.373,
    slg: 0.466,
    ops: 0.839,
    opsp: 124,
    tb: 27,
    hbp: 1,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "David Hensley",
    edad: 28,
    pos: "RF",
    jj: 20,
    app: 76,
    ab: 59,
    c: 10,
    h: 17,
    b1: 12,
    b2: 5,
    b3: 0,
    hr: 0,
    rbi: 6,
    bb: 16,
    so: 22,
    sb: 3,
    cs: 1,
    avg: 0.288,
    obp: 0.434,
    slg: 0.373,
    ops: 0.807,
    opsp: 119,
    tb: 22,
    hbp: 0,
    ibb: 0,
    sf: 1,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Michael De La Cruz",
    edad: 31,
    pos: "C",
    jj: 19,
    app: 49,
    ab: 36,
    c: 5,
    h: 4,
    b1: 2,
    b2: 1,
    b3: 0,
    hr: 1,
    rbi: 2,
    bb: 12,
    so: 13,
    sb: 0,
    cs: 0,
    avg: 0.111,
    obp: 0.333,
    slg: 0.222,
    ops: 0.555,
    opsp: 82,
    tb: 8,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 1,
    dp: 0,
  },
  {
    nombre: "Liover Peguero",
    edad: 24,
    pos: "2B",
    jj: 18,
    app: 74,
    ab: 67,
    c: 6,
    h: 18,
    b1: 14,
    b2: 4,
    b3: 0,
    hr: 0,
    rbi: 5,
    bb: 6,
    so: 22,
    sb: 1,
    cs: 1,
    avg: 0.269,
    obp: 0.329,
    slg: 0.328,
    ops: 0.657,
    opsp: 97,
    tb: 22,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 1,
    dp: 3,
  },
  {
    nombre: "Ryan Fitzgerald",
    edad: 30,
    pos: "3B",
    jj: 15,
    app: 63,
    ab: 58,
    c: 9,
    h: 15,
    b1: 13,
    b2: 1,
    b3: 0,
    hr: 1,
    rbi: 8,
    bb: 4,
    so: 11,
    sb: 1,
    cs: 0,
    avg: 0.259,
    obp: 0.317,
    slg: 0.328,
    ops: 0.645,
    opsp: 95,
    tb: 19,
    hbp: 1,
    ibb: 1,
    sf: 0,
    s: 0,
    dp: 2,
  },
  {
    nombre: "Andre Lipcius",
    edad: 26,
    pos: "1B",
    jj: 14,
    app: 46,
    ab: 42,
    c: 4,
    h: 9,
    b1: 7,
    b2: 2,
    b3: 0,
    hr: 0,
    rbi: 4,
    bb: 3,
    so: 6,
    sb: 0,
    cs: 1,
    avg: 0.214,
    obp: 0.283,
    slg: 0.262,
    ops: 0.545,
    opsp: 81,
    tb: 11,
    hbp: 1,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Luis Campusano",
    edad: 26,
    pos: "DH",
    jj: 13,
    app: 58,
    ab: 54,
    c: 8,
    h: 13,
    b1: 6,
    b2: 6,
    b3: 0,
    hr: 1,
    rbi: 5,
    bb: 1,
    so: 6,
    sb: 0,
    cs: 0,
    avg: 0.241,
    obp: 0.259,
    slg: 0.407,
    ops: 0.666,
    opsp: 98,
    tb: 22,
    hbp: 1,
    ibb: 0,
    sf: 2,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Michael De León",
    edad: 27,
    pos: "1B",
    jj: 12,
    app: 11,
    ab: 9,
    c: 4,
    h: 4,
    b1: 2,
    b2: 2,
    b3: 0,
    hr: 0,
    rbi: 3,
    bb: 1,
    so: 1,
    sb: 0,
    cs: 0,
    avg: 0.444,
    obp: 0.545,
    slg: 0.556,
    ops: 1.101,
    opsp: 163,
    tb: 5,
    hbp: 1,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Leonys Martin",
    edad: 36,
    pos: "RF",
    jj: 11,
    app: 32,
    ab: 25,
    c: 4,
    h: 5,
    b1: 2,
    b2: 2,
    b3: 1,
    hr: 0,
    rbi: 2,
    bb: 4,
    so: 7,
    sb: 1,
    cs: 0,
    avg: 0.2,
    obp: 0.323,
    slg: 0.36,
    ops: 0.683,
    opsp: 101,
    tb: 9,
    hbp: 1,
    ibb: 0,
    sf: 1,
    s: 1,
    dp: 0,
  },
  {
    nombre: "Robel García",
    edad: 31,
    pos: "PR",
    jj: 10,
    app: 15,
    ab: 15,
    c: 4,
    h: 2,
    b1: 1,
    b2: 0,
    b3: 0,
    hr: 1,
    rbi: 3,
    bb: 0,
    so: 5,
    sb: 0,
    cs: 0,
    avg: 0.133,
    obp: 0.133,
    slg: 0.333,
    ops: 0.466,
    opsp: 69,
    tb: 5,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Nasim Núñez",
    edad: 24,
    pos: "SS",
    jj: 10,
    app: 35,
    ab: 30,
    c: 3,
    h: 5,
    b1: 2,
    b2: 3,
    b3: 0,
    hr: 0,
    rbi: 2,
    bb: 3,
    so: 11,
    sb: 2,
    cs: 2,
    avg: 0.167,
    obp: 0.242,
    slg: 0.267,
    ops: 0.509,
    opsp: 75,
    tb: 8,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 2,
    dp: 0,
  },
  {
    nombre: "Jorge Alfaro",
    edad: 31,
    pos: "1B",
    jj: 9,
    app: 36,
    ab: 33,
    c: 6,
    h: 10,
    b1: 7,
    b2: 2,
    b3: 0,
    hr: 1,
    rbi: 8,
    bb: 2,
    so: 7,
    sb: 0,
    cs: 0,
    avg: 0.303,
    obp: 0.361,
    slg: 0.455,
    ops: 0.816,
    opsp: 121,
    tb: 15,
    hbp: 1,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Allan Cerda",
    edad: 25,
    pos: "PR",
    jj: 9,
    app: 3,
    ab: 3,
    c: 0,
    h: 0,
    b1: 0,
    b2: 0,
    b3: 0,
    hr: 0,
    rbi: 0,
    bb: 0,
    so: 2,
    sb: 0,
    cs: 0,
    avg: 0,
    obp: 0,
    slg: 0,
    ops: 0,
    opsp: 0,
    tb: 0,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Logan Davidson",
    edad: 27,
    pos: "LF",
    jj: 9,
    app: 26,
    ab: 20,
    c: 2,
    h: 2,
    b1: 1,
    b2: 1,
    b3: 0,
    hr: 0,
    rbi: 1,
    bb: 4,
    so: 13,
    sb: 1,
    cs: 0,
    avg: 0.1,
    obp: 0.308,
    slg: 0.15,
    ops: 0.458,
    opsp: 68,
    tb: 3,
    hbp: 2,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Miguel Andújar",
    edad: 29,
    pos: "DH",
    jj: 8,
    app: 32,
    ab: 31,
    c: 2,
    h: 5,
    b1: 3,
    b2: 1,
    b3: 0,
    hr: 1,
    rbi: 3,
    bb: 1,
    so: 6,
    sb: 0,
    cs: 0,
    avg: 0.161,
    obp: 0.188,
    slg: 0.29,
    ops: 0.478,
    opsp: 71,
    tb: 9,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 1,
  },
  {
    nombre: "Yamal Encarnación",
    edad: 21,
    pos: "PR",
    jj: 6,
    app: 3,
    ab: 3,
    c: 4,
    h: 1,
    b1: 0,
    b2: 1,
    b3: 0,
    hr: 0,
    rbi: 2,
    bb: 0,
    so: 0,
    sb: 1,
    cs: 0,
    avg: 0.333,
    obp: 0.333,
    slg: 0.667,
    ops: 1,
    opsp: 148,
    tb: 2,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Joe Dunand",
    edad: 29,
    pos: "1B",
    jj: 5,
    app: 12,
    ab: 12,
    c: 0,
    h: 0,
    b1: 0,
    b2: 0,
    b3: 0,
    hr: 0,
    rbi: 0,
    bb: 0,
    so: 4,
    sb: 0,
    cs: 0,
    avg: 0,
    obp: 0,
    slg: 0,
    ops: 0,
    opsp: 0,
    tb: 0,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Cristian Pache",
    edad: 26,
    pos: "CF",
    jj: 5,
    app: 16,
    ab: 13,
    c: 1,
    h: 2,
    b1: 1,
    b2: 0,
    b3: 1,
    hr: 0,
    rbi: 1,
    bb: 2,
    so: 7,
    sb: 0,
    cs: 0,
    avg: 0.154,
    obp: 0.25,
    slg: 0.308,
    ops: 0.558,
    opsp: 82,
    tb: 4,
    hbp: 0,
    ibb: 0,
    sf: 1,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Oneil Cruz",
    edad: 26,
    pos: "DH",
    jj: 4,
    app: 17,
    ab: 16,
    c: 1,
    h: 2,
    b1: 2,
    b2: 0,
    b3: 0,
    hr: 0,
    rbi: 1,
    bb: 1,
    so: 8,
    sb: 1,
    cs: 0,
    avg: 0.125,
    obp: 0.176,
    slg: 0.125,
    ops: 0.301,
    opsp: 44,
    tb: 2,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Orelvis Martinez",
    edad: 23,
    pos: "DH",
    jj: 4,
    app: 17,
    ab: 14,
    c: 2,
    h: 2,
    b1: 1,
    b2: 0,
    b3: 0,
    hr: 1,
    rbi: 1,
    bb: 3,
    so: 7,
    sb: 0,
    cs: 1,
    avg: 0.143,
    obp: 0.294,
    slg: 0.357,
    ops: 0.651,
    opsp: 96,
    tb: 5,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Juan Francisco",
    edad: 37,
    pos: "DH",
    jj: 2,
    app: 6,
    ab: 6,
    c: 0,
    h: 0,
    b1: 0,
    b2: 0,
    b3: 0,
    hr: 0,
    rbi: 0,
    bb: 0,
    so: 3,
    sb: 0,
    cs: 0,
    avg: 0,
    obp: 0,
    slg: 0,
    ops: 0,
    opsp: 0,
    tb: 0,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 1,
  },  {
    nombre: "Yunior Severino",
    edad: 25,
    pos: "DH",
    jj: 1,
    app: 4,
    ab: 3,
    c: 1,
    h: 0,
    b1: 0,
    b2: 0,
    b3: 0,
    hr: 0,
    rbi: 0,
    bb: 1,
    so: 1,
    sb: 0,
    cs: 0,
    avg: 0,
    obp: 0.25,
    slg: 0,
    ops: 0.25,
    opsp: 37,
    tb: 0,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Yonathan Daza",
    edad: 30,
    pos: "RF",
    jj: 1,
    app: 3,
    ab: 3,
    c: 0,
    h: 0,
    b1: 0,
    b2: 0,
    b3: 0,
    hr: 0,
    rbi: 0,
    bb: 0,
    so: 0,
    sb: 0,
    cs: 0,
    avg: 0,
    obp: 0,
    slg: 0,
    ops: 0,
    opsp: 0,
    tb: 0,
    hbp: 0,
    ibb: 0,
    sf: 0,
    s: 0,
    dp: 0,
  },
  {
    nombre: "Totales",
    edad: 28,
    pos: "",
    jj: 539,
    app: 1858,
    ab: 1622,
    c: 211,
    h: 395,
    b1: 273,
    b2: 81,
    b3: 12,
    hr: 29,
    rbi: 189,
    bb: 178,
    so: 400,
    sb: 48,
    cs: 16,
    avg: 0.244,
    obp: 0.322,
    slg: 0.361,
    ops: 0.683,
    opsp: 0,
    tb: 586,
    hbp: 20,
    ibb: 5,
    sf: 24,
    s: 14,
    dp: 20,
  },
];

// Datos de los lanzadores (mantenidos igual)
const pitchers = [
  {
    nombre: "Jonathan Aro",
    edad: 34,
    w: 3,
    l: 2,
    pct: 0.6,
    era: 2.92,
    eraplus: 131,
    gp: 27,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 2,
    ip: 24.2,
    h: 19,
    r: 11,
    er: 8,
    hr: 3,
    bb: 6,
    ibb: 1,
    so: 13,
    hbp: 1,
    wp: 1,
    be: 97,
    dec: 5,
    bs: 0,
    whip: 1.01,
    fip: 4.71,
  },
  {
    nombre: "Jean Carlos Mejía",
    edad: 28,
    w: 1,
    l: 2,
    pct: 0.333,
    era: 1.88,
    eraplus: 203,
    gp: 24,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 13,
    ip: 24,
    h: 14,
    r: 6,
    er: 5,
    hr: 0,
    bb: 9,
    ibb: 0,
    so: 22,
    hbp: 1,
    wp: 0,
    be: 94,
    dec: 3,
    bs: 0,
    whip: 0.96,
    fip: 2.75,
  },
  {
    nombre: "Adonis Medina",
    edad: 28,
    w: 0,
    l: 0,
    pct: 0,
    era: 2.93,
    eraplus: 130,
    gp: 21,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 15.1,
    h: 14,
    r: 5,
    er: 5,
    hr: 0,
    bb: 3,
    ibb: 0,
    so: 12,
    hbp: 3,
    wp: 0,
    be: 61,
    dec: 0,
    bs: 0,
    whip: 1.11,
    fip: 2.94,
  },
  {
    nombre: "Wander Suero",
    edad: 33,
    w: 1,
    l: 2,
    pct: 0.333,
    era: 1.83,
    eraplus: 209,
    gp: 20,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 19.2,
    h: 11,
    r: 7,
    er: 4,
    hr: 1,
    bb: 10,
    ibb: 5,
    so: 19,
    hbp: 0,
    wp: 1,
    be: 80,
    dec: 3,
    bs: 0,
    whip: 1.07,
    fip: 3.59,
  },
  {
    nombre: "Miguel Díaz",
    edad: 30,
    w: 2,
    l: 0,
    pct: 1,
    era: 2.76,
    eraplus: 138,
    gp: 20,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 16.1,
    h: 9,
    r: 8,
    er: 5,
    hr: 2,
    bb: 8,
    ibb: 0,
    so: 16,
    hbp: 0,
    wp: 1,
    be: 68,
    dec: 2,
    bs: 0,
    whip: 1.04,
    fip: 4.44,
  },
  {
    nombre: "Elniery García",
    edad: 30,
    w: 2,
    l: 0,
    pct: 1,
    era: 1.65,
    eraplus: 232,
    gp: 20,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 16.1,
    h: 10,
    r: 3,
    er: 3,
    hr: 0,
    bb: 7,
    ibb: 0,
    so: 19,
    hbp: 0,
    wp: 0,
    be: 65,
    dec: 2,
    bs: 0,
    whip: 1.04,
    fip: 2.29,
  },
  {
    nombre: "Jairo Asencio",
    edad: 41,
    w: 1,
    l: 2,
    pct: 0.333,
    era: 4.5,
    eraplus: 85,
    gp: 19,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 1,
    ip: 18,
    h: 18,
    r: 9,
    er: 9,
    hr: 2,
    bb: 4,
    ibb: 1,
    so: 14,
    hbp: 0,
    wp: 1,
    be: 72,
    dec: 3,
    bs: 0,
    whip: 1.22,
    fip: 3.89,
  },
  {
    nombre: "Andrew Pérez",
    edad: 27,
    w: 0,
    l: 0,
    pct: 0,
    era: 1.84,
    eraplus: 208,
    gp: 19,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 14.2,
    h: 12,
    r: 3,
    er: 3,
    hr: 0,
    bb: 9,
    ibb: 0,
    so: 11,
    hbp: 0,
    wp: 3,
    be: 62,
    dec: 0,
    bs: 0,
    whip: 1.43,
    fip: 3.68,
  },
  {
    nombre: "Misael Tamárez",
    edad: 24,
    w: 1,
    l: 1,
    pct: 0.5,
    era: 1.13,
    eraplus: 338,
    gp: 19,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 16,
    h: 8,
    r: 2,
    er: 2,
    hr: 0,
    bb: 5,
    ibb: 0,
    so: 11,
    hbp: 0,
    wp: 0,
    be: 58,
    dec: 2,
    bs: 0,
    whip: 0.81,
    fip: 2.9,
  },
  {
    nombre: "Ulises Joaquín",
    edad: 32,
    w: 3,
    l: 0,
    pct: 1,
    era: 0.87,
    eraplus: 439,
    gp: 17,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 20.2,
    h: 12,
    r: 3,
    er: 2,
    hr: 0,
    bb: 3,
    ibb: 1,
    so: 14,
    hbp: 0,
    wp: 0,
    be: 76,
    dec: 3,
    bs: 0,
    whip: 0.73,
    fip: 2.42,
  },
  {
    nombre: "Yunior Marte",
    edad: 29,
    w: 1,
    l: 0,
    pct: 1,
    era: 4.66,
    eraplus: 82,
    gp: 11,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 9.2,
    h: 7,
    r: 7,
    er: 5,
    hr: 2,
    bb: 3,
    ibb: 0,
    so: 5,
    hbp: 0,
    wp: 0,
    be: 39,
    dec: 1,
    bs: 0,
    whip: 1.03,
    fip: 5.92,
  },
  {
    nombre: "Radhamés Liz",
    edad: 41,
    w: 3,
    l: 1,
    pct: 0.75,
    era: 1.64,
    eraplus: 233,
    gp: 9,
    gs: 9,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 38.1,
    h: 22,
    r: 7,
    er: 7,
    hr: 1,
    bb: 18,
    ibb: 0,
    so: 33,
    hbp: 0,
    wp: 2,
    be: 147,
    dec: 4,
    bs: 0,
    whip: 1.04,
    fip: 3.36,
  },
  {
    nombre: "Steve Moyers",
    edad: 31,
    w: 1,
    l: 3,
    pct: 0.25,
    era: 3.24,
    eraplus: 118,
    gp: 8,
    gs: 8,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 33.1,
    h: 28,
    r: 13,
    er: 12,
    hr: 2,
    bb: 8,
    ibb: 0,
    so: 15,
    hbp: 0,
    wp: 0,
    be: 131,
    dec: 4,
    bs: 0,
    whip: 1.08,
    fip: 3.94,
  },
  {
    nombre: "Nico Tellache",
    edad: 26,
    w: 2,
    l: 1,
    pct: 0.667,
    era: 2.17,
    eraplus: 176,
    gp: 8,
    gs: 8,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 29,
    h: 27,
    r: 8,
    er: 7,
    hr: 0,
    bb: 8,
    ibb: 0,
    so: 23,
    hbp: 0,
    wp: 0,
    be: 119,
    dec: 3,
    bs: 0,
    whip: 1.21,
    fip: 2.58,
  },
  {
    nombre: "Ben Heller",
    edad: 33,
    w: 1,
    l: 0,
    pct: 1,
    era: 5.63,
    eraplus: 68,
    gp: 8,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 8,
    h: 7,
    r: 5,
    er: 5,
    hr: 1,
    bb: 2,
    ibb: 0,
    so: 8,
    hbp: 0,
    wp: 1,
    be: 31,
    dec: 1,
    bs: 0,
    whip: 1.13,
    fip: 3.71,
  },
  {
    nombre: "César Valdez",
    edad: 39,
    w: 1,
    l: 3,
    pct: 0.25,
    era: 3.6,
    eraplus: 106,
    gp: 7,
    gs: 7,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 35,
    h: 35,
    r: 18,
    er: 14,
    hr: 4,
    bb: 0,
    ibb: 0,
    so: 20,
    hbp: 1,
    wp: 0,
    be: 139,
    dec: 4,
    bs: 0,
    whip: 1,
    fip: 3.76,
  },
  {
    nombre: "Lisalverto Bonilla",
    edad: 34,
    w: 1,
    l: 0,
    pct: 1,
    era: 1.69,
    eraplus: 226,
    gp: 7,
    gs: 3,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 16,
    h: 6,
    r: 7,
    er: 3,
    hr: 1,
    bb: 7,
    ibb: 1,
    so: 13,
    hbp: 1,
    wp: 1,
    be: 65,
    dec: 1,
    bs: 0,
    whip: 0.81,
    fip: 4.02,
  },
  {
    nombre: "Albert Abreu",
    edad: 29,
    w: 0,
    l: 1,
    pct: 0,
    era: 3.18,
    eraplus: 120,
    gp: 6,
    gs: 6,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 22.2,
    h: 24,
    r: 11,
    er: 8,
    hr: 0,
    bb: 9,
    ibb: 1,
    so: 15,
    hbp: 2,
    wp: 2,
    be: 100,
    dec: 1,
    bs: 0,
    whip: 1.46,
    fip: 3.47,
  },
  {
    nombre: "Carlos Vargas",
    edad: 25,
    w: 1,
    l: 0,
    pct: 1,
    era: 3.6,
    eraplus: 106,
    gp: 6,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 5,
    h: 5,
    r: 2,
    er: 2,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 9,
    hbp: 0,
    wp: 1,
    be: 21,
    dec: 1,
    bs: 0,
    whip: 1.2,
    fip: 0.33,
  },
  {
    nombre: "Phillip Diehl",
    edad: 30,
    w: 0,
    l: 0,
    pct: 0,
    era: 3,
    eraplus: 127,
    gp: 5,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 3,
    h: 1,
    r: 1,
    er: 1,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 3,
    hbp: 0,
    wp: 0,
    be: 11,
    dec: 0,
    bs: 0,
    whip: 0.67,
    fip: 2.33,
  },
  {
    nombre: "Jake Miednik",
    edad: 28,
    w: 1,
    l: 1,
    pct: 0.5,
    era: 1.5,
    eraplus: 255,
    gp: 5,
    gs: 1,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 6,
    h: 3,
    r: 1,
    er: 1,
    hr: 0,
    bb: 4,
    ibb: 0,
    so: 4,
    hbp: 0,
    wp: 0,
    be: 23,
    dec: 2,
    bs: 0,
    whip: 1.17,
    fip: 4.0,
  },
  {
    nombre: "Enyel De Los Santos",
    edad: 29,
    w: 0,
    l: 0,
    pct: 0,
    era: 0,
    eraplus: Infinity,
    gp: 4,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 3.2,
    h: 1,
    r: 0,
    er: 0,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 5,
    hbp: 0,
    wp: 0,
    be: 13,
    dec: 0,
    bs: 0,
    whip: 0.55,
    fip: 1.43,
  },
  {
    nombre: "Ryan Sherriff",
    edad: 34,
    w: 1,
    l: 0,
    pct: 1,
    era: 0,
    eraplus: Infinity,
    gp: 4,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 3.2,
    h: 1,
    r: 0,
    er: 0,
    hr: 0,
    bb: 0,
    ibb: 0,
    so: 3,
    hbp: 0,
    wp: 0,
    be: 12,
    dec: 1,
    bs: 0,
    whip: 0.27,
    fip: 1.7,
  },
  {
    nombre: "Raúl Valdés",
    edad: 47,
    w: 0,
    l: 2,
    pct: 0,
    era: 9,
    eraplus: 42,
    gp: 3,
    gs: 3,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 10,
    h: 13,
    r: 12,
    er: 10,
    hr: 2,
    bb: 2,
    ibb: 0,
    so: 3,
    hbp: 0,
    wp: 1,
    be: 46,
    dec: 2,
    bs: 0,
    whip: 1.5,
    fip: 5.94,
  },
  {
    nombre: "Dany Jiménez",
    edad: 31,
    w: 0,
    l: 0,
    pct: 0,
    era: 3.86,
    eraplus: 99,
    gp: 3,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 2.1,
    h: 5,
    r: 1,
    er: 1,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 1,
    hbp: 0,
    wp: 1,
    be: 11,
    dec: 0,
    bs: 0,
    whip: 2.57,
    fip: 3.76,
  },
  {
    nombre: "Juan Then",
    edad: 24,
    w: 0,
    l: 0,
    pct: 0,
    era: 4.5,
    eraplus: 85,
    gp: 3,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 2,
    h: 2,
    r: 1,
    er: 1,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 2,
    hbp: 0,
    wp: 1,
    be: 9,
    dec: 0,
    bs: 0,
    whip: 1.5,
    fip: 2.84,
  },
  {
    nombre: "Zac Grotz",
    edad: 31,
    w: 0,
    l: 1,
    pct: 0,
    era: 4,
    eraplus: 96,
    gp: 3,
    gs: 3,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 9,
    h: 7,
    r: 5,
    er: 4,
    hr: 1,
    bb: 7,
    ibb: 0,
    so: 4,
    hbp: 0,
    wp: 1,
    be: 40,
    dec: 1,
    bs: 0,
    whip: 1.56,
    fip: 6.22,
  },
  {
    nombre: "Heath Hembree",
    edad: 35,
    w: 0,
    l: 0,
    pct: 0,
    era: 7.71,
    eraplus: 50,
    gp: 3,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 2.1,
    h: 2,
    r: 2,
    er: 2,
    hr: 0,
    bb: 4,
    ibb: 0,
    so: 3,
    hbp: 0,
    wp: 0,
    be: 12,
    dec: 0,
    bs: 0,
    whip: 2.57,
    fip: 5.91,
  },
  {
    nombre: "Carlos Contreras",
    edad: 34,
    w: 0,
    l: 0,
    pct: 0,
    era: 6,
    eraplus: 64,
    gp: 2,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 3,
    h: 4,
    r: 2,
    er: 2,
    hr: 1,
    bb: 0,
    ibb: 0,
    so: 2,
    hbp: 0,
    wp: 0,
    be: 13,
    dec: 0,
    bs: 0,
    whip: 1.33,
    fip: 6.33,
  },
  {
    nombre: "Gerald Ogando",
    edad: 24,
    w: 0,
    l: 0,
    pct: 0,
    era: 0,
    eraplus: Infinity,
    gp: 2,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 2,
    h: 0,
    r: 0,
    er: 0,
    hr: 0,
    bb: 0,
    ibb: 0,
    so: 3,
    hbp: 0,
    wp: 0,
    be: 6,
    dec: 0,
    bs: 0,
    whip: 0,
    fip: 0.33,
  },
  {
    nombre: "Deivi García",
    edad: 25,
    w: 0,
    l: 0,
    pct: 0,
    era: 26.99,
    eraplus: 14,
    gp: 1,
    gs: 1,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 0.2,
    h: 3,
    r: 2,
    er: 2,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 0,
    hbp: 1,
    wp: 0,
    be: 6,
    dec: 0,
    bs: 0,
    whip: 6,
    fip: 12.33,
  },
  {
    nombre: "Anderson Severino",
    edad: 30,
    w: 0,
    l: 0,
    pct: 0,
    era: 9,
    eraplus: 42,
    gp: 1,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 1,
    h: 1,
    r: 1,
    er: 1,
    hr: 0,
    bb: 1,
    ibb: 0,
    so: 2,
    hbp: 0,
    wp: 1,
    be: 5,
    dec: 0,
    bs: 0,
    whip: 2,
    fip: 2.33,
  },
  {
    nombre: "Brooks Hall",
    edad: 34,
    w: 0,
    l: 0,
    pct: 0,
    era: 0,
    eraplus: Infinity,
    gp: 1,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 2,
    h: 0,
    r: 0,
    er: 0,
    hr: 0,
    bb: 0,
    ibb: 0,
    so: 3,
    hbp: 0,
    wp: 0,
    be: 6,
    dec: 0,
    bs: 0,
    whip: 0,
    fip: 0.33,
  },
  {
    nombre: "Michael Arias",
    edad: 23,
    w: 0,
    l: 0,
    pct: 0,
    era: 0,
    eraplus: Infinity,
    gp: 1,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 0.2,
    h: 0,
    r: 0,
    er: 0,
    hr: 0,
    bb: 0,
    ibb: 0,
    so: 0,
    hbp: 1,
    wp: 0,
    be: 2,
    dec: 0,
    bs: 0,
    whip: 0,
    fip: 7.83,
  },
  {
    nombre: "Armando Vásquez",
    edad: 23,
    w: 0,
    l: 0,
    pct: 0,
    era: 18,
    eraplus: 21,
    gp: 1,
    gs: 0,
    cg: 0,
    sho: 0,
    sv: 0,
    ip: 1,
    h: 2,
    r: 2,
    er: 2,
    hr: 1,
    bb: 0,
    ibb: 0,
    so: 2,
    hbp: 0,
    wp: 1,
    be: 5,
    dec: 0,
    bs: 0,
    whip: 2,
    fip: 12.34,
  },
  {
    nombre: "Totales",
    edad: 31,
    w: 27,
    l: 22,
    pct: 0.551,
    era: 2.81,
    eraplus: 0,
    gp: 318,
    gs: 49,
    cg: 0,
    sho: 0,
    sv: 16,
    ip: 435,
    h: 333,
    r: 165,
    er: 136,
    hr: 24,
    bb: 143,
    ibb: 10,
    so: 332,
    hbp: 11,
    wp: 20,
    be: 1745,
    dec: 49,
    bs: 0,
    whip: 1.09,
    fip: 0,
  },

];

function formatNumber(value: number): string {
  return value === 0 ? ".000" : value.toString().replace("0.", ".");
}

export default function Page() {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredBatters = batters.filter((jugador) =>
    jugador.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredPitchers = pitchers.filter((pitcher) =>
    pitcher.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Encabezado con imagen difuminada */}
      <header className="relative h-64 shadow-xl">
        <div className="absolute inset-0 z-0">
          <img
            src="/Logos/Licey.png"
            alt="Estadio de béisbol"
            className="object-cover  h-full blur-s "
          />
          <div className="absolute inset-0 bg-black/30" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-4xl font-bold text-white mb-4 drop-shadow-lg">
            Estadísticas de Los Tigres del Licey
          </h1>
          <p className="text-xl text-white/90 drop-shadow-md">
          Temporada 2024 Serie Regular
          </p>
        </div>
      </header>

      {/* Contenido principal */}
      <div className="p-6 max-w-9xl mx-auto">
        {/* Barra de búsqueda */}
        <div className="mb-6">
          <input
            type="text"
            placeholder="Buscar jugador..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm"
          />
        </div>

        {/* Sección de Bateadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-blue-900">Bateadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-blue-900 text-white ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">POS</th>
            <th className="border border-gray-300 p-2">JJ</th>
            <th className="border border-gray-300 p-2">APP</th>
            <th className="border border-gray-300 p-2">AB</th>
            <th className="border border-gray-300 p-2">C</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">1B</th>
            <th className="border border-gray-300 p-2">2B</th>
            <th className="border border-gray-300 p-2">3B</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">RBI</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">SB</th>
            <th className="border border-gray-300 p-2">CS</th>
            <th className="border border-gray-300 p-2">AVG</th>
            <th className="border border-gray-300 p-2">OBP</th>
            <th className="border border-gray-300 p-2">SLG</th>
            <th className="border border-gray-300 p-2">OPS</th>
            <th className="border border-gray-300 p-2">OPS+</th>
            <th className="border border-gray-300 p-2">TB</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SF</th>
            <th className="border border-gray-300 p-2">S</th>
            <th className="border border-gray-300 p-2">DP</th>
            
          </tr>
              </thead>
              <tbody>
                {filteredBatters.map((jugador, index) => (
                  <tr key={index} className={jugador.nombre === "Totales" ? "bg-blue-400 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-blue-800 bg-black/10">{jugador.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.pos}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.jj}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ab}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.app}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.c}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b1}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b2}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b3}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.rbi}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.cs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.avg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.obp)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.slg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.ops)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.opsp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.tb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sf}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.s}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.dp}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sección de Lanzadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mt-8 mb-4 text-blue-900">Lanzadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-blue-900 ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">W</th>
            <th className="border border-gray-300 p-2">L</th>
            <th className="border border-gray-300 p-2">PCT</th>
            <th className="border border-gray-300 p-2">ERA</th>
            <th className="border border-gray-300 p-2">ERA+</th>
            <th className="border border-gray-300 p-2">GP</th>
            <th className="border border-gray-300 p-2">GS</th>
            <th className="border border-gray-300 p-2">CG</th>
            <th className="border border-gray-300 p-2">SHO</th>
            <th className="border border-gray-300 p-2">SV</th>
            <th className="border border-gray-300 p-2">IP</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">R</th>
            <th className="border border-gray-300 p-2">ER</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">WP</th>
            <th className="border border-gray-300 p-2">BE</th>
            <th className="border border-gray-300 p-2">DEC</th>
            <th className="border border-gray-300 p-2">BS</th>
            <th className="border border-gray-300 p-2">WHIP</th>
            <th className="border border-gray-300 p-2">FIP</th>
          </tr>
              </thead>
              <tbody>
                {filteredPitchers.map((pitcher, index) => (
                  <tr key={index} className={pitcher.nombre === "Totales" ? "bg-blue-400 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-blue-800 bg-black/10">{pitcher.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.w}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.l}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.pct.toFixed(3)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.era.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.eraplus}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.cg}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sho}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sv}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ip}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.r}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.er}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.wp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.be}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.dec}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.whip.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.fip.toFixed(2)}</td>
              </tr>
                  
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}