"use client"

import React, { useState } from 'react';

// Datos de los bateadores (mantenidos igual)
const batters = [
  
    {
        "nombre": "Leury García",
        "edad": 33,
        "pos": "2B",
        "jj": 39,
        "app": 160,
        "ab": 148,
        "c": 22,
        "h": 40,
        "b1": 27,
        "b2": 9,
        "b3": 1,
        "hr": 3,
        "rbi": 20,
        "bb": 8,
        "so": 29,
        "sb": 11,
        "cs": 0,
        "avg": 0.270,
        "obp": 0.321,
        "slg": 0.399,
        "ops": 0.720,
        "opsp": 106,
        "tb": 59,
        "hbp": 3,
        "ibb": 0,
        "sf": 0,
        "s": 1,
        "dp": 1
      },
      {
        "nombre": "Kelvin Gutiérrez",
        "edad": 30,
        "pos": "3B",
        "jj": 38,
        "app": 156,
        "ab": 135,
        "c": 17,
        "h": 40,
        "b1": 31,
        "b2": 7,
        "b3": 0,
        "hr": 2,
        "rbi": 20,
        "bb": 19,
        "so": 28,
        "sb": 3,
        "cs": 2,
        "avg": 0.296,
        "obp": 0.385,
        "slg": 0.393,
        "ops": 0.778,
        "opsp": 115,
        "tb": 53,
        "hbp": 1,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 3
      },
      {
        "nombre": "Henry Urrutia",
        "edad": 37,
        "pos": "DH",
        "jj": 38,
        "app": 136,
        "ab": 122,
        "c": 12,
        "h": 32,
        "b1": 27,
        "b2": 4,
        "b3": 0,
        "hr": 1,
        "rbi": 16,
        "bb": 12,
        "so": 21,
        "sb": 0,
        "cs": 0,
        "avg": 0.262,
        "obp": 0.331,
        "slg": 0.320,
        "ops": 0.651,
        "opsp": 96,
        "tb": 39,
        "hbp": 1,
        "ibb": 2,
        "sf": 1,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Carlos Peguero",
        "edad": 37,
        "pos": "RF",
        "jj": 34,
        "app": 124,
        "ab": 111,
        "c": 15,
        "h": 32,
        "b1": 18,
        "b2": 5,
        "b3": 1,
        "hr": 8,
        "rbi": 25,
        "bb": 11,
        "so": 34,
        "sb": 0,
        "cs": 0,
        "avg": 0.288,
        "obp": 0.355,
        "slg": 0.568,
        "ops": 0.923,
        "opsp": 136,
        "tb": 63,
        "hbp": 1,
        "ibb": 3,
        "sf": 1,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Carlos Franco",
        "edad": 33,
        "pos": "1B",
        "jj": 33,
        "app": 89,
        "ab": 71,
        "c": 12,
        "h": 21,
        "b1": 15,
        "b2": 2,
        "b3": 0,
        "hr": 4,
        "rbi": 13,
        "bb": 17,
        "so": 17,
        "sb": 0,
        "cs": 1,
        "avg": 0.296,
        "obp": 0.438,
        "slg": 0.493,
        "ops": 0.931,
        "opsp": 138,
        "tb": 35,
        "hbp": 1,
        "ibb": 1,
        "sf": 0,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Jorge Bonifacio",
        "edad": 31,
        "pos": "RF",
        "jj": 32,
        "app": 59,
        "ab": 50,
        "c": 9,
        "h": 9,
        "b1": 6,
        "b2": 2,
        "b3": 0,
        "hr": 1,
        "rbi": 6,
        "bb": 6,
        "so": 11,
        "sb": 1,
        "cs": 2,
        "avg": 0.180,
        "obp": 0.271,
        "slg": 0.280,
        "ops": 0.551,
        "opsp": 81,
        "tb": 14,
        "hbp": 1,
        "ibb": 0,
        "sf": 2,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Wilmer Difó",
        "edad": 32,
        "pos": "2B",
        "jj": 32,
        "app": 132,
        "ab": 112,
        "c": 16,
        "h": 25,
        "b1": 21,
        "b2": 4,
        "b3": 0,
        "hr": 0,
        "rbi": 14,
        "bb": 16,
        "so": 23,
        "sb": 1,
        "cs": 2,
        "avg": 0.223,
        "obp": 0.313,
        "slg": 0.259,
        "ops": 0.572,
        "opsp": 84,
        "tb": 29,
        "hbp": 0,
        "ibb": 0,
        "sf": 3,
        "s": 1,
        "dp": 2
      },
      {
        "nombre": "Julio Carreras",
        "edad": 24,
        "pos": "SS",
        "jj": 32,
        "app": 86,
        "ab": 72,
        "c": 11,
        "h": 10,
        "b1": 9,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 3,
        "bb": 9,
        "so": 18,
        "sb": 7,
        "cs": 1,
        "avg": 0.139,
        "obp": 0.262,
        "slg": 0.153,
        "ops": 0.415,
        "opsp": 61,
        "tb": 11,
        "hbp": 3,
        "ibb": 0,
        "sf": 0,
        "s": 2,
        "dp": 2
      },
      {
        "nombre": "Marco Hernández",
        "edad": 32,
        "pos": "2B",
        "jj": 27,
        "app": 63,
        "ab": 59,
        "c": 3,
        "h": 13,
        "b1": 9,
        "b2": 3,
        "b3": 1,
        "hr": 0,
        "rbi": 6,
        "bb": 4,
        "so": 15,
        "sb": 0,
        "cs": 2,
        "avg": 0.220,
        "obp": 0.270,
        "slg": 0.305,
        "ops": 0.575,
        "opsp": 85,
        "tb": 18,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Noelvi Marte",
        "edad": 23,
        "pos": "3B",
        "jj": 27,
        "app": 109,
        "ab": 97,
        "c": 18,
        "h": 22,
        "b1": 15,
        "b2": 4,
        "b3": 1,
        "hr": 2,
        "rbi": 14,
        "bb": 9,
        "so": 22,
        "sb": 5,
        "cs": 1,
        "avg": 0.227,
        "obp": 0.303,
        "slg": 0.351,
        "ops": 0.654,
        "opsp": 97,
        "tb": 34,
        "hbp": 2,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Johan Rojas",
        "edad": 24,
        "pos": "CF",
        "jj": 27,
        "app": 111,
        "ab": 95,
        "c": 20,
        "h": 28,
        "b1": 21,
        "b2": 6,
        "b3": 0,
        "hr": 1,
        "rbi": 8,
        "bb": 12,
        "so": 22,
        "sb": 23,
        "cs": 0,
        "avg": 0.295,
        "obp": 0.382,
        "slg": 0.389,
        "ops": 0.771,
        "opsp": 114,
        "tb": 37,
        "hbp": 2,
        "ibb": 0,
        "sf": 1,
        "s": 1,
        "dp": 4
      },
      {
        "nombre": "Geraldi Díaz",
        "edad": 24,
        "pos": "C",
        "jj": 22,
        "app": 57,
        "ab": 49,
        "c": 7,
        "h": 17,
        "b1": 11,
        "b2": 3,
        "b3": 1,
        "hr": 2,
        "rbi": 11,
        "bb": 4,
        "so": 7,
        "sb": 0,
        "cs": 0,
        "avg": 0.347,
        "obp": 0.429,
        "slg": 0.571,
        "ops": 1.000,
        "opsp": 148,
        "tb": 28,
        "hbp": 3,
        "ibb": 1,
        "sf": 0,
        "s": 1,
        "dp": 0
      },
      {
        "nombre": "Deivy Grullón",
        "edad": 28,
        "pos": "C",
        "jj": 21,
        "app": 55,
        "ab": 51,
        "c": 4,
        "h": 11,
        "b1": 8,
        "b2": 2,
        "b3": 0,
        "hr": 1,
        "rbi": 5,
        "bb": 3,
        "so": 23,
        "sb": 0,
        "cs": 0,
        "avg": 0.216,
        "obp": 0.255,
        "slg": 0.314,
        "ops": 0.569,
        "opsp": 84,
        "tb": 16,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Edwin Espinal",
        "edad": 30,
        "pos": "1B",
        "jj": 20,
        "app": 30,
        "ab": 25,
        "c": 4,
        "h": 5,
        "b1": 4,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 3,
        "bb": 5,
        "so": 6,
        "sb": 0,
        "cs": 0,
        "avg": 0.200,
        "obp": 0.333,
        "slg": 0.240,
        "ops": 0.573,
        "opsp": 85,
        "tb": 6,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Tyler Tolbert",
        "edad": 26,
        "pos": "CF",
        "jj": 20,
        "app": 39,
        "ab": 36,
        "c": 8,
        "h": 8,
        "b1": 4,
        "b2": 4,
        "b3": 0,
        "hr": 0,
        "rbi": 4,
        "bb": 2,
        "so": 9,
        "sb": 5,
        "cs": 2,
        "avg": 0.222,
        "obp": 0.282,
        "slg": 0.333,
        "ops": 0.615,
        "opsp": 91,
        "tb": 12,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Hanser Alberto",
        "edad": 32,
        "pos": "2B",
        "jj": 16,
        "app": 35,
        "ab": 32,
        "c": 2,
        "h": 6,
        "b1": 4,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 3,
        "bb": 2,
        "so": 4,
        "sb": 0,
        "cs": 0,
        "avg": 0.188,
        "obp": 0.257,
        "slg": 0.250,
        "ops": 0.507,
        "opsp": 75,
        "tb": 8,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Yermin Mercedes",
        "edad": 31,
        "pos": "DH",
        "jj": 16,
        "app": 51,
        "ab": 46,
        "c": 7,
        "h": 7,
        "b1": 2,
        "b2": 3,
        "b3": 0,
        "hr": 2,
        "rbi": 7,
        "bb": 3,
        "so": 9,
        "sb": 0,
        "cs": 0,
        "avg": 0.152,
        "obp": 0.235,
        "slg": 0.348,
        "ops": 0.583,
        "opsp": 86,
        "tb": 16,
        "hbp": 2,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Deyvison De Los Santos",
        "edad": 21,
        "pos": "1B",
        "jj": 16,
        "app": 54,
        "ab": 50,
        "c": 5,
        "h": 13,
        "b1": 11,
        "b2": 1,
        "b3": 1,
        "hr": 0,
        "rbi": 5,
        "bb": 3,
        "so": 10,
        "sb": 0,
        "cs": 0,
        "avg": 0.260,
        "obp": 0.296,
        "slg": 0.320,
        "ops": 0.616,
        "opsp": 91,
        "tb": 16,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 0
      },{
        "nombre": "José Siri",
        "edad": 29,
        "pos": "RF",
        "jj": 14,
        "app": 59,
        "ab": 50,
        "c": 10,
        "h": 13,
        "b1": 9,
        "b2": 3,
        "b3": 0,
        "hr": 1,
        "rbi": 4,
        "bb": 7,
        "so": 16,
        "sb": 8,
        "cs": 1,
        "avg": 0.260,
        "obp": 0.356,
        "slg": 0.380,
        "ops": 0.736,
        "opsp": 109,
        "tb": 19,
        "hbp": 1,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Andrew Knizner",
        "edad": 29,
        "pos": "C",
        "jj": 11,
        "app": 33,
        "ab": 31,
        "c": 2,
        "h": 8,
        "b1": 6,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 2,
        "so": 10,
        "sb": 0,
        "cs": 0,
        "avg": 0.258,
        "obp": 0.303,
        "slg": 0.323,
        "ops": 0.626,
        "opsp": 92,
        "tb": 10,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Diego Hernández",
        "edad": 24,
        "pos": "LF",
        "jj": 11,
        "app": 40,
        "ab": 34,
        "c": 4,
        "h": 10,
        "b1": 8,
        "b2": 1,
        "b3": 1,
        "hr": 0,
        "rbi": 2,
        "bb": 5,
        "so": 8,
        "sb": 1,
        "cs": 0,
        "avg": 0.294,
        "obp": 0.400,
        "slg": 0.382,
        "ops": 0.782,
        "opsp": 116,
        "tb": 13,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Oliver Dunn",
        "edad": 27,
        "pos": "LF",
        "jj": 11,
        "app": 26,
        "ab": 22,
        "c": 2,
        "h": 2,
        "b1": 2,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 4,
        "so": 9,
        "sb": 0,
        "cs": 1,
        "avg": 0.091,
        "obp": 0.231,
        "slg": 0.091,
        "ops": 0.322,
        "opsp": 48,
        "tb": 2,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Dane Myers",
        "edad": 28,
        "pos": "LF",
        "jj": 10,
        "app": 35,
        "ab": 29,
        "c": 5,
        "h": 8,
        "b1": 6,
        "b2": 0,
        "b3": 1,
        "hr": 1,
        "rbi": 4,
        "bb": 6,
        "so": 11,
        "sb": 4,
        "cs": 1,
        "avg": 0.276,
        "obp": 0.400,
        "slg": 0.448,
        "ops": 0.848,
        "opsp": 125,
        "tb": 13,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Jhon Núñez",
        "edad": 30,
        "pos": "C",
        "jj": 9,
        "app": 23,
        "ab": 18,
        "c": 3,
        "h": 2,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 1,
        "rbi": 1,
        "bb": 4,
        "so": 5,
        "sb": 1,
        "cs": 0,
        "avg": 0.111,
        "obp": 0.304,
        "slg": 0.278,
        "ops": 0.582,
        "opsp": 86,
        "tb": 5,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Yoyner Fajardo",
        "edad": 25,
        "pos": "LF",
        "jj": 9,
        "app": 28,
        "ab": 23,
        "c": 2,
        "h": 3,
        "b1": 2,
        "b2": 0,
        "b3": 1,
        "hr": 0,
        "rbi": 4,
        "bb": 3,
        "so": 8,
        "sb": 1,
        "cs": 1,
        "avg": 0.130,
        "obp": 0.222,
        "slg": 0.217,
        "ops": 0.439,
        "opsp": 65,
        "tb": 5,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 1,
        "dp": 1
      },
      {
        "nombre": "Melvin Mercedes",
        "edad": 32,
        "pos": "PH",
        "jj": 7,
        "app": 9,
        "ab": 7,
        "c": 1,
        "h": 2,
        "b1": 2,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 1,
        "so": 2,
        "sb": 1,
        "cs": 0,
        "avg": 0.286,
        "obp": 0.444,
        "slg": 0.286,
        "ops": 0.730,
        "opsp": 108,
        "tb": 2,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Joe Hudson",
        "edad": 33,
        "pos": "C",
        "jj": 5,
        "app": 15,
        "ab": 15,
        "c": 0,
        "h": 1,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 6,
        "sb": 0,
        "cs": 0,
        "avg": 0.067,
        "obp": 0.067,
        "slg": 0.067,
        "ops": 0.134,
        "opsp": 20,
        "tb": 1,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Richard Ureña",
        "edad": 28,
        "pos": "2B",
        "jj": 4,
        "app": 2,
        "ab": 2,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "José Fermín",
        "edad": 25,
        "pos": "2B",
        "jj": 4,
        "app": 16,
        "ab": 15,
        "c": 2,
        "h": 4,
        "b1": 2,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 1,
        "so": 2,
        "sb": 0,
        "cs": 0,
        "avg": 0.267,
        "obp": 0.313,
        "slg": 0.400,
        "ops": 0.713,
        "opsp": 105,
        "tb": 6,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Luis García Jr",
        "edad": 24,
        "pos": "2B",
        "jj": 4,
        "app": 17,
        "ab": 17,
        "c": 1,
        "h": 4,
        "b1": 4,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 0,
        "so": 4,
        "sb": 1,
        "cs": 0,
        "avg": 0.235,
        "obp": 0.235,
        "slg": 0.235,
        "ops": 0.470,
        "opsp": 69,
        "tb": 4,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Raylín Heredia",
        "edad": 21,
        "pos": "PR",
        "jj": 4,
        "app": 3,
        "ab": 2,
        "c": 1,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 0,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.333,
        "slg": 0.000,
        "ops": 0.333,
        "opsp": 49,
        "tb": 0,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Omar De Los Santos",
        "edad": 25,
        "pos": "PR",
        "jj": 4,
        "app": 1,
        "ab": 1,
        "c": 1,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Ronald Guzmán",
        "edad": 30,
        "pos": "1B",
        "jj": 1,
        "app": 4,
        "ab": 4,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 2,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Kervin Pichardo",
        "edad": 23,
        "pos": "PR",
        "jj": 1,
        "app": 1,
        "ab": 1,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Totales",
        "edad": 28,
        "pos": "",
        "jj": 599,
        "app": 1858,
        "ab": 1632,
        "c": 226,
        "h": 396,
        "b1": 286,
        "b2": 71,
        "b3": 9,
        "hr": 30,
        "rbi": 206,
        "bb": 178,
        "so": 394,
        "sb": 73,
        "cs": 17,
        "avg": 0.243,
        "obp": 0.325,
        "slg": 0.352,
        "ops": 0.677,
        "opsp": 0.000,
        "tb": 574,
        "hbp": 27,
        "ibb": 7,
        "sf": 14,
        "s": 7,
        "dp": 28
      }
];

// Datos de los lanzadores (mantenidos igual)
const pitchers = [
    {
        "nombre": "Edgar Santana",
        "edad": 33,
        "w": 0,
        "l": 2,
        "pct": 0.0,
        "era": 5.79,
        "eraplus": 66,
        "gp": 18,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 14,
        "h": 19,
        "r": 9,
        "er": 9,
        "hr": 1,
        "bb": 7,
        "ibb": 1,
        "so": 14,
        "hbp": 1,
        "wp": 0,
        "be": 63,
        "dec": 2,
        "bs": 0,
        "whip": 1.86,
        "fip": 3.98
      },
      {
        "nombre": "Joel César",
        "edad": 28,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 2.4,
        "eraplus": 159,
        "gp": 16,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 15,
        "h": 11,
        "r": 4,
        "er": 4,
        "hr": 1,
        "bb": 6,
        "ibb": 0,
        "so": 20,
        "hbp": 0,
        "wp": 1,
        "be": 62,
        "dec": 0,
        "bs": 0,
        "whip": 1.13,
        "fip": 2.73
      },
      {
        "nombre": "Anderson Pilar",
        "edad": 26,
        "w": 1,
        "l": 1,
        "pct": 0.5,
        "era": 3.0,
        "eraplus": 127,
        "gp": 16,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 21,
        "h": 15,
        "r": 7,
        "er": 7,
        "hr": 1,
        "bb": 2,
        "ibb": 0,
        "so": 27,
        "hbp": 0,
        "wp": 1,
        "be": 78,
        "dec": 2,
        "bs": 0,
        "whip": 0.81,
        "fip": 1.67
      },
      {
        "nombre": "Johan Domínguez",
        "edad": 28,
        "w": 1,
        "l": 0,
        "pct": 1.0,
        "era": 2.63,
        "eraplus": 145,
        "gp": 13,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 13.2,
        "h": 11,
        "r": 7,
        "er": 4,
        "hr": 1,
        "bb": 4,
        "ibb": 0,
        "so": 20,
        "hbp": 0,
        "wp": 1,
        "be": 58,
        "dec": 1,
        "bs": 0,
        "whip": 1.1,
        "fip": 2.24
      },
      {
        "nombre": "Reymin Guduan",
        "edad": 32,
        "w": 1,
        "l": 1,
        "pct": 0.5,
        "era": 2.79,
        "eraplus": 137,
        "gp": 11,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 2,
        "ip": 9.2,
        "h": 6,
        "r": 4,
        "er": 3,
        "hr": 1,
        "bb": 7,
        "ibb": 1,
        "so": 10,
        "hbp": 0,
        "wp": 2,
        "be": 42,
        "dec": 2,
        "bs": 0,
        "whip": 1.34,
        "fip": 4.78
      },
      {
        "nombre": "Edgar García",
        "edad": 28,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 9.0,
        "eraplus": 42,
        "gp": 11,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 10,
        "h": 5,
        "r": 10,
        "er": 10,
        "hr": 0,
        "bb": 11,
        "ibb": 1,
        "so": 8,
        "hbp": 1,
        "wp": 0,
        "be": 46,
        "dec": 1,
        "bs": 0,
        "whip": 1.6,
        "fip": 5.33
      },
      {
        "nombre": "Huascar Brazobán",
        "edad": 35,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 3.72,
        "eraplus": 103,
        "gp": 11,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 9.2,
        "h": 3,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 3,
        "ibb": 1,
        "so": 9,
        "hbp": 1,
        "wp": 0,
        "be": 35,
        "dec": 1,
        "bs": 0,
        "whip": 0.62,
        "fip": 2.71
      },
      {
        "nombre": "Nabil Crismatt",
        "edad": 30,
        "w": 5,
        "l": 2,
        "pct": 0.714,
        "era": 2.65,
        "eraplus": 144,
        "gp": 11,
        "gs": 11,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 54.1,
        "h": 45,
        "r": 19,
        "er": 16,
        "hr": 2,
        "bb": 11,
        "ibb": 0,
        "so": 49,
        "hbp": 0,
        "wp": 0,
        "be": 215,
        "dec": 7,
        "bs": 0,
        "whip": 1.03,
        "fip": 2.62
      },
      {
        "nombre": "Austin Roberts",
        "edad": 26,
        "w": 3,
        "l": 0,
        "pct": 1.0,
        "era": 6.39,
        "eraplus": 60,
        "gp": 11,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 12.2,
        "h": 13,
        "r": 11,
        "er": 9,
        "hr": 1,
        "bb": 5,
        "ibb": 1,
        "so": 8,
        "hbp": 1,
        "wp": 3,
        "be": 54,
        "dec": 3,
        "bs": 0,
        "whip": 1.42,
        "fip": 4.52
      },
      {
        "nombre": "Blake Weiman",
        "edad": 29,
        "w": 1,
        "l": 0,
        "pct": 1.0,
        "era": 1.0,
        "eraplus": 382,
        "gp": 11,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 9,
        "h": 8,
        "r": 4,
        "er": 1,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 5,
        "hbp": 0,
        "wp": 0,
        "be": 35,
        "dec": 1,
        "bs": 0,
        "whip": 1.0,
        "fip": 2.56
      },
      {
        "nombre": "Wily Peralta",
        "edad": 35,
        "w": 2,
        "l": 5,
        "pct": 0.286,
        "era": 2.85,
        "eraplus": 134,
        "gp": 10,
        "gs": 10,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 41,
        "h": 41,
        "r": 13,
        "er": 13,
        "hr": 1,
        "bb": 17,
        "ibb": 0,
        "so": 30,
        "hbp": 2,
        "wp": 1,
        "be": 176,
        "dec": 7,
        "bs": 0,
        "whip": 1.41,
        "fip": 3.58
      },
      {
        "nombre": "Antonio Santos",
        "edad": 28,
        "w": 0,
        "l": 3,
        "pct": 0.0,
        "era": 6.28,
        "eraplus": 61,
        "gp": 10,
        "gs": 8,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 28.2,
        "h": 37,
        "r": 21,
        "er": 20,
        "hr": 2,
        "bb": 12,
        "ibb": 0,
        "so": 23,
        "hbp": 2,
        "wp": 1,
        "be": 137,
        "dec": 3,
        "bs": 0,
        "whip": 1.71,
        "fip": 4.1
      },
      {
        "nombre": "Wilkin Ramos",
        "edad": 24,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 2.25,
        "eraplus": 170,
        "gp": 10,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 8,
        "h": 4,
        "r": 4,
        "er": 2,
        "hr": 0,
        "bb": 6,
        "ibb": 0,
        "so": 6,
        "hbp": 3,
        "wp": 1,
        "be": 39,
        "dec": 0,
        "bs": 0,
        "whip": 1.25,
        "fip": 5.21
      },
      {
        "nombre": "Oddy Núñez",
        "edad": 28,
        "w": 1,
        "l": 0,
        "pct": 1.0,
        "era": 5.19,
        "eraplus": 74,
        "gp": 9,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 8.2,
        "h": 9,
        "r": 5,
        "er": 5,
        "hr": 0,
        "bb": 5,
        "ibb": 0,
        "so": 3,
        "hbp": 1,
        "wp": 0,
        "be": 39,
        "dec": 1,
        "bs": 0,
        "whip": 1.62,
        "fip": 4.72
      },
      {
        "nombre": "Christian Montes de Oca",
        "edad": 25,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 0.0,
        "eraplus": "Inf",
        "gp": 9,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 9,
        "h": 7,
        "r": 1,
        "er": 0,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 10,
        "hbp": 1,
        "wp": 0,
        "be": 32,
        "dec": 1,
        "bs": 0,
        "whip": 0.89,
        "fip": 1.78
      },
      {
        "nombre": "Andrew Hoffmann",
        "edad": 24,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 5.56,
        "eraplus": 69,
        "gp": 9,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 11.1,
        "h": 14,
        "r": 7,
        "er": 7,
        "hr": 1,
        "bb": 4,
        "ibb": 0,
        "so": 12,
        "hbp": 0,
        "wp": 0,
        "be": 49,
        "dec": 0,
        "bs": 0,
        "whip": 1.59,
        "fip": 3.42
      },
      {
        "nombre": "Yerry Rodríguez",
        "edad": 27,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 6.0,
        "eraplus": 64,
        "gp": 8,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 6,
        "h": 9,
        "r": 6,
        "er": 4,
        "hr": 0,
        "bb": 2,
        "ibb": 0,
        "so": 4,
        "hbp": 0,
        "wp": 0,
        "be": 29,
        "dec": 1,
        "bs": 0,
        "whip": 1.83,
        "fip": 3.0
      },
      {
        "nombre": "Ian Krol",
        "edad": 33,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 4.5,
        "eraplus": 85,
        "gp": 8,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 6,
        "h": 5,
        "r": 4,
        "er": 3,
        "hr": 1,
        "bb": 4,
        "ibb": 0,
        "so": 5,
        "hbp": 0,
        "wp": 0,
        "be": 26,
        "dec": 0,
        "bs": 0,
        "whip": 1.5,
        "fip": 5.83
      },
      {
        "nombre": "Emilio Vargas",
        "edad": 28,
        "w": 5,
        "l": 0,
        "pct": 1.0,
        "era": 1.87,
        "eraplus": 204,
        "gp": 7,
        "gs": 6,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 33.2,
        "h": 25,
        "r": 7,
        "er": 7,
        "hr": 1,
        "bb": 8,
        "ibb": 0,
        "so": 19,
        "hbp": 4,
        "wp": 1,
        "be": 137,
        "dec": 5,
        "bs": 0,
        "whip": 0.98,
        "fip": 3.66
      },
      {
        "nombre": "Benony Robles",
        "edad": 24,
        "w": 1,
        "l": 0,
        "pct": 1.0,
        "era": 3.37,
        "eraplus": 113,
        "gp": 7,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 5.1,
        "h": 4,
        "r": 3,
        "er": 2,
        "hr": 2,
        "bb": 3,
        "ibb": 0,
        "so": 3,
        "hbp": 1,
        "wp": 0,
        "be": 22,
        "dec": 1,
        "bs": 0,
        "whip": 1.31,
        "fip": 9.33
      },
      {
        "nombre": "Ángel Chivilli",
        "edad": 22,
        "w": 0,
        "l": 2,
        "pct": 0.0,
        "era": 9.95,
        "eraplus": 38,
        "gp": 7,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 6.1,
        "h": 6,
        "r": 7,
        "er": 7,
        "hr": 2,
        "bb": 4,
        "ibb": 1,
        "so": 5,
        "hbp": 1,
        "wp": 0,
        "be": 31,
        "dec": 2,
        "bs": 0,
        "whip": 1.58,
        "fip": 8.23
      }, {
        "nombre": "Camilo Doval",
        "edad": 27,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 5.68,
        "eraplus": 67,
        "gp": 7,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 3,
        "ip": 6.1,
        "h": 5,
        "r": 5,
        "er": 4,
        "hr": 1,
        "bb": 6,
        "ibb": 0,
        "so": 7,
        "hbp": 1,
        "wp": 1,
        "be": 30,
        "dec": 1,
        "bs": 0,
        "whip": 1.74,
        "fip": 6.49
      },
      {
        "nombre": "Enmanuel Mejía",
        "edad": 26,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 6.23,
        "eraplus": 61,
        "gp": 6,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 4.1,
        "h": 4,
        "r": 3,
        "er": 3,
        "hr": 0,
        "bb": 7,
        "ibb": 1,
        "so": 6,
        "hbp": 0,
        "wp": 0,
        "be": 23,
        "dec": 0,
        "bs": 0,
        "whip": 2.54,
        "fip": 5.41
      },
      {
        "nombre": "Daniel Ponce De Leon",
        "edad": 32,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 5.52,
        "eraplus": 69,
        "gp": 6,
        "gs": 4,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 14.2,
        "h": 12,
        "r": 9,
        "er": 9,
        "hr": 1,
        "bb": 16,
        "ibb": 0,
        "so": 17,
        "hbp": 0,
        "wp": 2,
        "be": 71,
        "dec": 1,
        "bs": 0,
        "whip": 1.91,
        "fip": 5.18
      },
      {
        "nombre": "Joely Rodríguez",
        "edad": 33,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 7.2,
        "eraplus": 53,
        "gp": 5,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 5,
        "h": 7,
        "r": 4,
        "er": 4,
        "hr": 2,
        "bb": 0,
        "ibb": 0,
        "so": 6,
        "hbp": 0,
        "wp": 0,
        "be": 21,
        "dec": 0,
        "bs": 0,
        "whip": 1.4,
        "fip": 6.13
      },
      {
        "nombre": "Frank Garces",
        "edad": 34,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 0.93,
        "eraplus": 411,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 9.2,
        "h": 7,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 7,
        "hbp": 1,
        "wp": 1,
        "be": 36,
        "dec": 0,
        "bs": 0,
        "whip": 0.83,
        "fip": 2.51
      },
      {
        "nombre": "Wendell Floranus",
        "edad": 29,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 8.31,
        "eraplus": 46,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 4.1,
        "h": 7,
        "r": 4,
        "er": 4,
        "hr": 1,
        "bb": 1,
        "ibb": 0,
        "so": 5,
        "hbp": 0,
        "wp": 0,
        "be": 19,
        "dec": 0,
        "bs": 0,
        "whip": 1.85,
        "fip": 4.72
      },
      {
        "nombre": "Marco Jiménez",
        "edad": 25,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 10.8,
        "eraplus": 35,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.2,
        "h": 3,
        "r": 3,
        "er": 2,
        "hr": 0,
        "bb": 2,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 10,
        "dec": 0,
        "bs": 0,
        "whip": 3.0,
        "fip": 5.74
      },
      {
        "nombre": "Jake Walters",
        "edad": 28,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 9.0,
        "eraplus": 42,
        "gp": 4,
        "gs": 2,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 5,
        "h": 7,
        "r": 5,
        "er": 5,
        "hr": 1,
        "bb": 4,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 0,
        "be": 26,
        "dec": 1,
        "bs": 0,
        "whip": 2.2,
        "fip": 7.13
      },
      {
        "nombre": "Víctor López",
        "edad": 25,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 2.7,
        "eraplus": 141,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 3.1,
        "h": 3,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 3,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 0,
        "be": 16,
        "dec": 0,
        "bs": 0,
        "whip": 1.8,
        "fip": 4.24
      },
      {
        "nombre": "Danny Salazar",
        "edad": 35,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 8.44,
        "eraplus": 45,
        "gp": 3,
        "gs": 2,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 5.1,
        "h": 7,
        "r": 6,
        "er": 5,
        "hr": 0,
        "bb": 4,
        "ibb": 0,
        "so": 5,
        "hbp": 0,
        "wp": 0,
        "be": 28,
        "dec": 0,
        "bs": 0,
        "whip": 2.06,
        "fip": 3.71
      },
      {
        "nombre": "Wandy Peralta",
        "edad": 33,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 4.5,
        "eraplus": 85,
        "gp": 3,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 2,
        "h": 3,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 11,
        "dec": 1,
        "bs": 0,
        "whip": 2.0,
        "fip": 3.83
      },
      {
        "nombre": "Steven Cruz",
        "edad": 25,
        "w": 1,
        "l": 0,
        "pct": 1.0,
        "era": 0.0,
        "eraplus": "Inf",
        "gp": 3,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 3,
        "h": 2,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 4,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 0,
        "be": 15,
        "dec": 1,
        "bs": 0,
        "whip": 2.0,
        "fip": 5.33
      },
      {
        "nombre": "Garrett Davila",
        "edad": 27,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 3.37,
        "eraplus": 113,
        "gp": 3,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 2.2,
        "h": 3,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 3,
        "ibb": 1,
        "so": 3,
        "hbp": 0,
        "wp": 0,
        "be": 13,
        "dec": 0,
        "bs": 0,
        "whip": 2.25,
        "fip": 4.46
      },
      {
        "nombre": "Solomon Bates",
        "edad": 27,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 20.77,
        "eraplus": 18,
        "gp": 3,
        "gs": 2,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 4.1,
        "h": 10,
        "r": 10,
        "er": 10,
        "hr": 2,
        "bb": 4,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 1,
        "be": 27,
        "dec": 1,
        "bs": 0,
        "whip": 3.23,
        "fip": 10.72
      },
      {
        "nombre": "Beck Way",
        "edad": 25,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 13.5,
        "eraplus": 28,
        "gp": 3,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 2,
        "h": 2,
        "r": 3,
        "er": 3,
        "hr": 0,
        "bb": 5,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 1,
        "be": 13,
        "dec": 0,
        "bs": 0,
        "whip": 3.5,
        "fip": 7.83
      },
      {
        "nombre": "Yunesky Maya",
        "edad": 43,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 9.0,
        "eraplus": 42,
        "gp": 2,
        "gs": 2,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 4,
        "h": 8,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 3,
        "ibb": 0,
        "so": 5,
        "hbp": 1,
        "wp": 0,
        "be": 23,
        "dec": 0,
        "bs": 0,
        "whip": 2.75,
        "fip": 3.83
      },{
        "nombre": "Yerry De Los Santos",
        "edad": 27,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 10.8,
        "eraplus": 35,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 1.2,
        "h": 2,
        "r": 2,
        "er": 2,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 1,
        "hbp": 1,
        "wp": 0,
        "be": 9,
        "dec": 0,
        "bs": 0,
        "whip": 1.8,
        "fip": 5.73
      },
      {
        "nombre": "Jordany Ventura",
        "edad": 24,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 13.5,
        "eraplus": 28,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.1,
        "h": 4,
        "r": 2,
        "er": 2,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 1,
        "be": 8,
        "dec": 0,
        "bs": 0,
        "whip": 3.75,
        "fip": 5.59
      },
      {
        "nombre": "Luis Velásquez",
        "edad": 23,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 26.99,
        "eraplus": 14,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.2,
        "h": 3,
        "r": 3,
        "er": 2,
        "hr": 1,
        "bb": 1,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 7,
        "dec": 0,
        "bs": 0,
        "whip": 6.0,
        "fip": 24.32
      },
      {
        "nombre": "Nick Dombkowski",
        "edad": 26,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 3.37,
        "eraplus": 113,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 2.2,
        "h": 1,
        "r": 1,
        "er": 1,
        "hr": 1,
        "bb": 2,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 1,
        "be": 12,
        "dec": 0,
        "bs": 0,
        "whip": 1.12,
        "fip": 9.71
      },
      {
        "nombre": "Iván Oviedo",
        "edad": 22,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 8.31,
        "eraplus": 46,
        "gp": 2,
        "gs": 1,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 4.1,
        "h": 4,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 4,
        "ibb": 0,
        "so": 4,
        "hbp": 0,
        "wp": 2,
        "be": 21,
        "dec": 1,
        "bs": 0,
        "whip": 1.85,
        "fip": 4.26
      },
      {
        "nombre": "Calvin Coker",
        "edad": 28,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 26.99,
        "eraplus": 14,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.1,
        "h": 4,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 3,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 1,
        "be": 11,
        "dec": 0,
        "bs": 0,
        "whip": 5.25,
        "fip": 8.58
      },
      {
        "nombre": "Jojanse Torres",
        "edad": 29,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 0.0,
        "eraplus": "Inf",
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.2,
        "h": 1,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 4,
        "dec": 0,
        "bs": 0,
        "whip": 3.0,
        "fip": 7.83
      },
      {
        "nombre": "Joelvis Del Rosario",
        "edad": 23,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 27.03,
        "eraplus": 14,
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.1,
        "h": 1,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 3,
        "dec": 0,
        "bs": 0,
        "whip": 6.01,
        "fip": 12.34
      },
      {
        "nombre": "Tyler Danish",
        "edad": 30,
        "w": 0,
        "l": 1,
        "pct": 0.0,
        "era": 20.26,
        "eraplus": 19,
        "gp": 1,
        "gs": 1,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.1,
        "h": 4,
        "r": 3,
        "er": 3,
        "hr": 0,
        "bb": 3,
        "ibb": 0,
        "so": 2,
        "hbp": 0,
        "wp": 0,
        "be": 10,
        "dec": 1,
        "bs": 0,
        "whip": 5.25,
        "fip": 7.09
      },
      {
        "nombre": "Kenny Hernández",
        "edad": 26,
        "w": 0,
        "l": 0,
        "pct": 0.0,
        "era": 0.0,
        "eraplus": "Inf",
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.2,
        "h": 1,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 7,
        "dec": 0,
        "bs": 0,
        "whip": 1.2,
        "fip": 3.93
      },
      {
        "nombre": "Totales",
        "edad": 28,
        "w": 22,
        "l": 27,
        "pct": 0.449,
        "era": 4.49,
        "eraplus": 0,
        "gp": 303,
        "gs": 49,
        "cg": 0,
        "sho": 0,
        "sv": 10,
        "ip": 426.2,
        "h": 412,
        "r": 237,
        "er": 213,
        "hr": 28,
        "bb": 205,
        "ibb": 8,
        "so": 379,
        "hbp": 23,
        "wp": 23,
        "be": 1879,
        "dec": 49,
        "bs": 0,
        "whip": 1.45,
        "fip": 0.0
      }

];

function formatNumber(value: number): string {
  return value === 0 ? ".000" : value.toString().replace("0.", ".");
}

export default function Page() {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredBatters = batters.filter((jugador) =>
    jugador.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredPitchers = pitchers.filter((pitcher) =>
    pitcher.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-red-950">
      {/* Encabezado con imagen difuminada */}
      <header className="relative h-64 shadow-xl">
        <div className="absolute inset-0 z-0">
          <img
            src="/Logos/gigantes-del-cibao.png"
            alt="Estadio de béisbol"
            className="object-cover  h-full blur-s "
          />
          <div className="absolute inset-0 bg-black/30" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-4xl font-bold text-white mb-4 drop-shadow-lg">
            Estadísticas de Los Gigantes del Cibao
          </h1>
          <p className="text-xl text-white/90 drop-shadow-md">
          Temporada 2024 Serie Regular
          </p>
        </div>
      </header>

      {/* Contenido principal */}
      <div className="p-6 max-w-9xl mx-auto">
        {/* Barra de búsqueda */}
        <div className="mb-6">
          <input
            type="text"
            placeholder="Buscar jugador..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-950 focus:border-transparent shadow-sm"
          />
        </div>

        {/* Sección de Bateadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-white">Bateadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-black text-white ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">POS</th>
            <th className="border border-gray-300 p-2">JJ</th>
            <th className="border border-gray-300 p-2">APP</th>
            <th className="border border-gray-300 p-2">AB</th>
            <th className="border border-gray-300 p-2">C</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">1B</th>
            <th className="border border-gray-300 p-2">2B</th>
            <th className="border border-gray-300 p-2">3B</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">RBI</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">SB</th>
            <th className="border border-gray-300 p-2">CS</th>
            <th className="border border-gray-300 p-2">AVG</th>
            <th className="border border-gray-300 p-2">OBP</th>
            <th className="border border-gray-300 p-2">SLG</th>
            <th className="border border-gray-300 p-2">OPS</th>
            <th className="border border-gray-300 p-2">OPS+</th>
            <th className="border border-gray-300 p-2">TB</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SF</th>
            <th className="border border-gray-300 p-2">S</th>
            <th className="border border-gray-300 p-2">DP</th>
            
          </tr>
              </thead>
              <tbody>
                {filteredBatters.map((jugador, index) => (
                  <tr key={index} className={jugador.nombre === "Totales" ? "bg-red-950/40 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-red-950 bg-black/40">{jugador.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.pos}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.jj}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ab}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.app}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.c}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b1}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b2}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b3}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.rbi}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.cs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.avg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.obp)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.slg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.ops)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.opsp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.tb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sf}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.s}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.dp}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sección de Lanzadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mt-8 mb-4 text-white">Lanzadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-black ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">W</th>
            <th className="border border-gray-300 p-2">L</th>
            <th className="border border-gray-300 p-2">PCT</th>
            <th className="border border-gray-300 p-2">ERA</th>
            <th className="border border-gray-300 p-2">ERA+</th>
            <th className="border border-gray-300 p-2">GP</th>
            <th className="border border-gray-300 p-2">GS</th>
            <th className="border border-gray-300 p-2">CG</th>
            <th className="border border-gray-300 p-2">SHO</th>
            <th className="border border-gray-300 p-2">SV</th>
            <th className="border border-gray-300 p-2">IP</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">R</th>
            <th className="border border-gray-300 p-2">ER</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">WP</th>
            <th className="border border-gray-300 p-2">BE</th>
            <th className="border border-gray-300 p-2">DEC</th>
            <th className="border border-gray-300 p-2">BS</th>
            <th className="border border-gray-300 p-2">WHIP</th>
            <th className="border border-gray-300 p-2">FIP</th>
          </tr>
              </thead>
              <tbody>
                {filteredPitchers.map((pitcher, index) => (
                  <tr key={index} className={pitcher.nombre === "Totales" ? "bg-red-950/40 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-red-950 bg-black/40">{pitcher.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.w}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.l}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.pct.toFixed(3)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.era.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.eraplus}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.cg}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sho}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sv}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ip}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.r}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.er}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.wp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.be}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.dec}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.whip.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.fip.toFixed(2)}</td>
              </tr>
                  
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}