"use client"

import React, { useState } from 'react';

// Datos de los bateadores (mantenidos igual)
const batters = [
  {
    "nombre": "Jonathan Villar",
      "edad": 33,
      "pos": "3B",
      "jj": 42,
      "app": 177,
      "ab": 155,
      "c": 21,
      "h": 39,
      "b1": 33,
      "b2": 3,
      "b3": 0,
      "hr": 3,
      "rbi": 21,
      "bb": 18,
      "so": 33,
      "sb": 6,
      "cs": 7,
      "avg": 0.252,
      "obp": 0.328,
      "slg": 0.329,
      "ops": 0.657,
      "opsp": 97,
      "tb": 51,
      "hbp": 0,
      "ibb": 1,
      "sf": 1,
      "s": 3,
      "dp": 1
    },
    {
      "nombre": "Jerar Encarnación",
      "edad": 27,
      "pos": "RF",
      "jj": 42,
      "app": 169,
      "ab": 145,
      "c": 22,
      "h": 43,
      "b1": 28,
      "b2": 9,
      "b3": 2,
      "hr": 4,
      "rbi": 24,
      "bb": 20,
      "so": 31,
      "sb": 3,
      "cs": 2,
      "avg": 0.297,
      "obp": 0.391,
      "slg": 0.469,
      "ops": 0.86,
      "opsp": 127,
      "tb": 68,
      "hbp": 3,
      "ibb": 0,
      "sf": 1,
      "s": 0,
      "dp": 5
    },
    {
      "nombre": "Erick Mejía",
      "edad": 30,
      "pos": "CF",
      "jj": 41,
      "app": 155,
      "ab": 142,
      "c": 21,
      "h": 41,
      "b1": 28,
      "b2": 8,
      "b3": 0,
      "hr": 5,
      "rbi": 22,
      "bb": 12,
      "so": 34,
      "sb": 4,
      "cs": 1,
      "avg": 0.289,
      "obp": 0.344,
      "slg": 0.451,
      "ops": 0.795,
      "opsp": 117,
      "tb": 64,
      "hbp": 0,
      "ibb": 2,
      "sf": 0,
      "s": 1,
      "dp": 2
    },
    {
      "nombre": "Yefri Pérez",
      "edad": 33,
      "pos": "PR",
      "jj": 37,
      "app": 23,
      "ab": 21,
      "c": 14,
      "h": 6,
      "b1": 4,
      "b2": 1,
      "b3": 0,
      "hr": 1,
      "rbi": 3,
      "bb": 2,
      "so": 6,
      "sb": 5,
      "cs": 3,
      "avg": 0.286,
      "obp": 0.348,
      "slg": 0.476,
      "ops": 0.824,
      "opsp": 122,
      "tb": 10,
      "hbp": 0,
      "ibb": 0,
      "sf": 0,
      "s": 0,
      "dp": 1
    },
    {
      "nombre": "Aderlin Rodríguez",
      "edad": 33,
      "pos": "1B",
      "jj": 35,
      "app": 136,
      "ab": 124,
      "c": 22,
      "h": 40,
      "b1": 26,
      "b2": 4,
      "b3": 2,
      "hr": 8,
      "rbi": 28,
      "bb": 8,
      "so": 28,
      "sb": 1,
      "cs": 0,
      "avg": 0.323,
      "obp": 0.375,
      "slg": 0.581,
      "ops": 0.956,
      "opsp": 141,
      "tb": 72,
      "hbp": 3,
      "ibb": 1,
      "sf": 1,
      "s": 0,
      "dp": 2
    },
    {
      "nombre": "JC Escarra",
      "edad": 29,
      "pos": "C",
      "jj": 35,
      "app": 137,
      "ab": 113,
      "c": 22,
      "h": 41,
      "b1": 25,
      "b2": 13,
      "b3": 0,
      "hr": 3,
      "rbi": 14,
      "bb": 18,
      "so": 16,
      "sb": 1,
      "cs": 0,
      "avg": 0.363,
      "obp": 0.467,
      "slg": 0.549,
      "ops": 1.016,
      "opsp": 150,
      "tb": 62,
      "hbp": 5,
      "ibb": 0,
      "sf": 1,
      "s": 0,
      "dp": 3
    },
    {
      "nombre": "Ezequiel Durán",
      "edad": 25,
      "pos": "LF",
      "jj": 30,
      "app": 129,
      "ab": 109,
      "c": 22,
      "h": 33,
      "b1": 25,
      "b2": 4,
      "b3": 1,
      "hr": 3,
      "rbi": 17,
      "bb": 18,
      "so": 24,
      "sb": 2,
      "cs": 1,
      "avg": 0.303,
      "obp": 0.395,
      "slg": 0.44,
      "ops": 0.835,
      "opsp": 123,
      "tb": 48,
      "hbp": 0,
      "ibb": 1,
      "sf": 2,
      "s": 0,
      "dp": 3
    },
    {
      "nombre": "Cesar Prieto",
      "edad": 25,
      "pos": "2B",
      "jj": 29,
      "app": 112,
      "ab": 103,
      "c": 15,
      "h": 27,
      "b1": 23,
      "b2": 3,
      "b3": 1,
      "hr": 0,
      "rbi": 8,
      "bb": 5,
      "so": 12,
      "sb": 3,
      "cs": 2,
      "avg": 0.262,
      "obp": 0.306,
      "slg": 0.311,
      "ops": 0.617,
      "opsp": 91,
      "tb": 32,
      "hbp": 2,
      "ibb": 1,
      "sf": 1,
      "s": 1,
      "dp": 2
    },
    {
      "nombre": "Alexander Canario",
      "edad": 24,
      "pos": "LF",
      "jj": 27,
      "app": 95,
      "ab": 79,
      "c": 13,
      "h": 24,
      "b1": 13,
      "b2": 7,
      "b3": 0,
      "hr": 4,
      "rbi": 16,
      "bb": 13,
      "so": 19,
      "sb": 1,
      "cs": 0,
      "avg": 0.304,
      "obp": 0.411,
      "slg": 0.544,
      "ops": 0.955,
      "opsp": 141,
      "tb": 43,
      "hbp": 2,
      "ibb": 0,
      "sf": 1,
      "s": 0,
      "dp": 1
    },
    {
      "nombre": "Starlin Castro",
      "edad": 34,
      "pos": "1B",
      "jj": 25,
      "app": 83,
      "ab": 77,
      "c": 4,
      "h": 18,
      "b1": 12,
      "b2": 4,
      "b3": 1,
      "hr": 1,
      "rbi": 11,
      "bb": 3,
      "so": 13,
      "sb": 0,
      "cs": 0,
      "avg": 0.234,
      "obp": 0.253,
      "slg": 0.351,
      "ops": 0.604,
      "opsp": 89,
      "tb": 27,
      "hbp": 0,
      "ibb": 0,
      "sf": 3,
      "s": 0,
      "dp": 3
    },
    {
        "nombre": "Alfredo Reyes",
        "edad": 31,
        "pos": "2B",
        "jj": 25,
        "app": 39,
        "ab": 33,
        "c": 9,
        "h": 12,
        "b1": 7,
        "b2": 3,
        "b3": 2,
        "hr": 0,
        "rbi": 4,
        "bb": 3,
        "so": 8,
        "sb": 0,
        "cs": 0,
        "avg": 0.364,
        "obp": 0.447,
        "slg": 0.576,
        "ops": 1.023,
        "opsp": 151,
        "tb": 19,
        "hbp": 2,
        "ibb": 0,   
        "sf": 0,
        "s": 1,
        "dp": 1,
    },
    {
        "nombre": "Juan Lagares",
        "edad": 35,
        "pos": "CF",
        "jj": 22,
        "app": 76,
        "ab": 72,
        "c": 11,
        "h": 23,
        "b1": 14,
        "b2": 7,
        "b3": 0,
        "hr": 2,
        "rbi": 11,
        "bb": 2,
        "so": 16,
        "sb": 0,
        "cs": 1,
        "avg": 0.319,
        "obp": 0.355,
        "slg": 0.5,
        "ops": 0.855,
        "opsp": 126,
        "tb": 36,
        "hbp": 2,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Carlos Paulino",
        "edad": 35,
        "pos": "C",
        "jj": 21,
        "app": 51,
        "ab": 43,
        "c": 2,
        "h": 3,
        "b1": 1,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 6,
        "so": 20,
        "sb": 0,
        "cs": 0,
        "avg": 0.07,
        "obp": 0.2,
        "slg": 0.116,
        "ops": 0.316,
        "opsp": 47,
        "tb": 5,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 1,
        "dp": 1
      },
      {
        "nombre": "José Caballero",
        "edad": 28,
        "pos": "SS",
        "jj": 21,
        "app": 75,
        "ab": 65,
        "c": 9,
        "h": 11,
        "b1": 9,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 7,
        "bb": 8,
        "so": 17,
        "sb": 7,
        "cs": 1,
        "avg": 0.169,
        "obp": 0.257,
        "slg": 0.2,
        "ops": 0.457,
        "opsp": 68,
        "tb": 13,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 1,
        "dp": 0
      },
      {
        "nombre": "Yadiel Hernández",
        "edad": 37,
        "pos": "LF",
        "jj": 18,
        "app": 61,
        "ab": 53,
        "c": 6,
        "h": 10,
        "b1": 8,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 6,
        "so": 12,
        "sb": 0,
        "cs": 0,
        "avg": 0.189,
        "obp": 0.267,
        "slg": 0.226,
        "ops": 0.493,
        "opsp": 73,
        "tb": 12,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 1,
        "dp": 3
      },
      {
        "nombre": "Anthony Garcia",
        "edad": 24,
        "pos": "DH",
        "jj": 18,
        "app": 56,
        "ab": 43,
        "c": 8,
        "h": 11,
        "b1": 5,
        "b2": 3,
        "b3": 0,
        "hr": 3,
        "rbi": 10,
        "bb": 13,
        "so": 15,
        "sb": 1,
        "cs": 0,
        "avg": 0.256,
        "obp": 0.429,
        "slg": 0.535,
        "ops": 0.964,
        "opsp": 142,
        "tb": 23,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Ramón Torres",
        "edad": 31,
        "pos": "SS",
        "jj": 15,
        "app": 9,
        "ab": 8,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0,
        "obp": 0.111,
        "slg": 0,
        "ops": 0.111,
        "opsp": 16,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Yairo Muñoz",
        "edad": 29,
        "pos": "3B",
        "jj": 15,
        "app": 57,
        "ab": 55,
        "c": 3,
        "h": 16,
        "b1": 14,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 5,
        "bb": 1,
        "so": 7,
        "sb": 3,
        "cs": 2,
        "avg": 0.291,
        "obp": 0.298,
        "slg": 0.327,
        "ops": 0.625,
        "opsp": 92,
        "tb": 18,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 4
      },
      {
        "nombre": "Andretty Cordero",
        "edad": 27,
        "pos": "PH",
        "jj": 14,
        "app": 26,
        "ab": 22,
        "c": 2,
        "h": 6,
        "b1": 5,
        "b2": 0,
        "b3": 0,
        "hr": 1,
        "rbi": 5,
        "bb": 3,
        "so": 7,
        "sb": 0,
        "cs": 0,
        "avg": 0.273,
        "obp": 0.346,
        "slg": 0.409,
        "ops": 0.755,
        "opsp": 112,
        "tb": 9,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Bladimir Restituyo",
        "edad": 23,
        "pos": "CF",
        "jj": 14,
        "app": 18,
        "ab": 17,
        "c": 3,
        "h": 3,
        "b1": 3,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 6,
        "sb": 0,
        "cs": 0,
        "avg": 0.176,
        "obp": 0.176,
        "slg": 0.176,
        "ops": 0.352,
        "opsp": 52,
        "tb": 3,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 1,
        "dp": 0
      },
      {
        "nombre": "Christian Koss",
        "edad": 26,
        "pos": "SS",
        "jj": 14,
        "app": 41,
        "ab": 34,
        "c": 3,
        "h": 6,
        "b1": 5,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 4,
        "so": 12,
        "sb": 2,
        "cs": 0,
        "avg": 0.176,
        "obp": 0.3,
        "slg": 0.206,
        "ops": 0.506,
        "opsp": 75,
        "tb": 7,
        "hbp": 2,
        "ibb": 0,
        "sf": 0,
        "s": 1,
        "dp": 0
      },
      {
        "nombre": "Julio Rodríguez",
        "edad": 27,
        "pos": "C",
        "jj": 12,
        "app": 38,
        "ab": 31,
        "c": 4,
        "h": 6,
        "b1": 5,
        "b2": 0,
        "b3": 0,
        "hr": 1,
        "rbi": 6,
        "bb": 6,
        "so": 9,
        "sb": 0,
        "cs": 0,
        "avg": 0.194,
        "obp": 0.342,
        "slg": 0.29,
        "ops": 0.632,
        "opsp": 93,
        "tb": 9,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 3
      },
      {
        "nombre": "Eddys Leonard",
        "edad": 24,
        "pos": "DH",
        "jj": 12,
        "app": 33,
        "ab": 24,
        "c": 2,
        "h": 4,
        "b1": 3,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 6,
        "so": 6,
        "sb": 0,
        "cs": 0,
        "avg": 0.167,
        "obp": 0.375,
        "slg": 0.208,
        "ops": 0.583,
        "opsp": 86,
        "tb": 5,
        "hbp": 2,
        "ibb": 1,
        "sf": 0,
        "s": 1,
        "dp": 0
      },
      {
        "nombre": "Michael Pérez",
        "edad": 32,
        "pos": "C",
        "jj": 8,
        "app": 24,
        "ab": 23,
        "c": 1,
        "h": 3,
        "b1": 3,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 12,
        "sb": 0,
        "cs": 0,
        "avg": 0.13,
        "obp": 0.167,
        "slg": 0.13,
        "ops": 0.297,
        "opsp": 44,
        "tb": 3,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Gilberto Celestino",
        "edad": 25,
        "pos": "CF",
        "jj": 7,
        "app": 18,
        "ab": 13,
        "c": 1,
        "h": 2,
        "b1": 0,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 5,
        "so": 5,
        "sb": 0,
        "cs": 1,
        "avg": 0.154,
        "obp": 0.389,
        "slg": 0.308,
        "ops": 0.697,
        "opsp": 103,
        "tb": 4,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Luis Valenzuela",
        "edad": 31,
        "pos": "PH",
        "jj": 7,
        "app": 12,
        "ab": 11,
        "c": 0,
        "h": 1,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 0,
        "so": 3,
        "sb": 0,
        "cs": 0,
        "avg": 0.091,
        "obp": 0.091,
        "slg": 0.091,
        "ops": 0.182,
        "opsp": 27,
        "tb": 1,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 1,
        "dp": 2
      },
      {
        "nombre": "Brett Sullivan",
        "edad": 30,
        "pos": "C",
        "jj": 5,
        "app": 19,
        "ab": 18,
        "c": 1,
        "h": 4,
        "b1": 4,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 0,
        "so": 3,
        "sb": 0,
        "cs": 0,
        "avg": 0.222,
        "obp": 0.211,
        "slg": 0.222,
        "ops": 0.433,
        "opsp": 64,
        "tb": 4,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Jose Rodriguez",
        "edad": 23,
        "pos": "PH",
        "jj": 4,
        "app": 7,
        "ab": 5,
        "c": 1,
        "h": 2,
        "b1": 2,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 2,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.4,
        "obp": 0.571,
        "slg": 0.4,
        "ops": 0.971,
        "opsp": 143,
        "tb": 2,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Jonatan Clase",
        "edad": 22,
        "pos": "CF",
        "jj": 3,
        "app": 8,
        "ab": 7,
        "c": 1,
        "h": 1,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 2,
        "sb": 0,
        "cs": 0,
        "avg": 0.143,
        "obp": 0.25,
        "slg": 0.143,
        "ops": 0.393,
        "opsp": 58,
        "tb": 1,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Alberto Rodríguez",
        "edad": 24,
        "pos": "CF",
        "jj": 3,
        "app": 6,
        "ab": 5,
        "c": 1,
        "h": 2,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 1,
        "rbi": 3,
        "bb": 1,
        "so": 3,
        "sb": 0,
        "cs": 0,
        "avg": 0.4,
        "obp": 0.5,
        "slg": 1,
        "ops": 1.5,
        "opsp": 222,
        "tb": 5,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Geraldo Perdomo",
        "edad": 25,
        "pos": "SS",
        "jj": 2,
        "app": 6,
        "ab": 6,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0,
        "obp": 0,
        "slg": 0,
        "ops": 0,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Christopher Suero",
        "edad": 20,
        "pos": "1B",
        "jj": 2,
        "app": 3,
        "ab": 3,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0,
        "obp": 0,
        "slg": 0,
        "ops": 0,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Christopher Morel",
        "edad": 25,
        "pos": "LF",
        "jj": 1,
        "app": 2,
        "ab": 2,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0,
        "obp": 0,
        "slg": 0,
        "ops": 0,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Totales",
        "edad": 28,
        "pos": "",
        "jj": 606,
        "app": 1901,
        "ab": 1661,
        "c": 244,
        "h": 438,
        "b1": 308,
        "b2": 81,
        "b3": 9,
        "hr": 40,
        "rbi": 225,
        "bb": 186,
        "so": 384,
        "sb": 39,
        "cs": 21,
        "avg": 0.264,
        "obp": 0.344,
        "slg": 0.395,
        "ops": 0.739,
        "opsp": 0,
        "tb": 656,
        "hbp": 25,
        "ibb": 7,
        "sf": 16,
        "s": 13,
        "dp": 40
      }
    ]
// Datos de los lanzadores (mantenidos igual)
const pitchers = [
  {
    "nombre": "Jhan Maríñez",
      "edad": 36,
      "w": 5,
      "l": 1,
      "pct": 0.833,
      "era": 3.09,
      "eraplus": 124,
      "gp": 25,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 2,
      "ip": 23.1,
      "h": 17,
      "r": 8,
      "er": 8,
      "hr": 0,
      "bb": 10,
      "ibb": 1,
      "so": 20,
      "hbp": 1,
      "wp": 1,
      "be": 96,
      "dec": 6,
      "bs": 0,
      "whip": 1.16,
      "fip": 3.03
    },
    {
      "nombre": "Richard Rodríguez",
      "edad": 34,
      "w": 0,
      "l": 1,
      "pct": 0,
      "era": 1.29,
      "eraplus": 296,
      "gp": 23,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 2,
      "ip": 21,
      "h": 15,
      "r": 4,
      "er": 3,
      "hr": 0,
      "bb": 6,
      "ibb": 1,
      "so": 25,
      "hbp": 1,
      "wp": 1,
      "be": 85,
      "dec": 1,
      "bs": 0,
      "whip": 1,
      "fip": 1.95
    },
    {
      "nombre": "Junior Fernández",
      "edad": 27,
      "w": 0,
      "l": 1,
      "pct": 0,
      "era": 5.87,
      "eraplus": 65,
      "gp": 20,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 3,
      "ip": 15.1,
      "h": 22,
      "r": 12,
      "er": 10,
      "hr": 0,
      "bb": 12,
      "ibb": 0,
      "so": 13,
      "hbp": 0,
      "wp": 1,
      "be": 78,
      "dec": 1,
      "bs": 0,
      "whip": 2.22,
      "fip": 3.99
    },
    {
      "nombre": "Pedro Strop",
      "edad": 39,
      "w": 1,
      "l": 1,
      "pct": 0.5,
      "era": 2.55,
      "eraplus": 150,
      "gp": 19,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 2,
      "ip": 17.2,
      "h": 9,
      "r": 5,
      "er": 5,
      "hr": 4,
      "bb": 3,
      "ibb": 0,
      "so": 18,
      "hbp": 0,
      "wp": 0,
      "be": 63,
      "dec": 2,
      "bs": 0,
      "whip": 0.68,
      "fip": 4.75
    },
    {
      "nombre": "Jonathan Hernández",
      "edad": 28,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 3.68,
      "eraplus": 104,
      "gp": 18,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 2,
      "ip": 14.2,
      "h": 13,
      "r": 6,
      "er": 6,
      "hr": 1,
      "bb": 11,
      "ibb": 1,
      "so": 12,
      "hbp": 1,
      "wp": 2,
      "be": 67,
      "dec": 0,
      "bs": 0,
      "whip": 1.64,
      "fip": 5.04
    },
    {
      "nombre": "Williams Jerez",
      "edad": 32,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 5.78,
      "eraplus": 66,
      "gp": 17,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 14,
      "h": 11,
      "r": 9,
      "er": 9,
      "hr": 1,
      "bb": 10,
      "ibb": 1,
      "so": 10,
      "hbp": 2,
      "wp": 1,
      "be": 65,
      "dec": 0,
      "bs": 0,
      "whip": 1.5,
      "fip": 5.41
    },
    {
      "nombre": "Luis González",
      "edad": 32,
      "w": 0,
      "l": 1,
      "pct": 0,
      "era": 0.77,
      "eraplus": 496,
      "gp": 14,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 1,
      "ip": 11.2,
      "h": 11,
      "r": 2,
      "er": 1,
      "hr": 0,
      "bb": 2,
      "ibb": 0,
      "so": 18,
      "hbp": 0,
      "wp": 2,
      "be": 48,
      "dec": 1,
      "bs": 0,
      "whip": 1.11,
      "fip": 0.76
    },
    {
      "nombre": "Amir Garrett",
      "edad": 32,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 1.04,
      "eraplus": 367,
      "gp": 14,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 8.2,
      "h": 7,
      "r": 1,
      "er": 1,
      "hr": 1,
      "bb": 7,
      "ibb": 0,
      "so": 10,
      "hbp": 0,
      "wp": 1,
      "be": 38,
      "dec": 0,
      "bs": 0,
      "whip": 1.62,
      "fip": 4.95
    },
    {
      "nombre": "Jake Higginbotham",
      "edad": 28,
      "w": 1,
      "l": 0,
      "pct": 1,
      "era": 0,
      "eraplus": "Inf",
      "gp": 12,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 10.2,
      "h": 4,
      "r": 1,
      "er": 0,
      "hr": 0,
      "bb": 4,
      "ibb": 0,
      "so": 12,
      "hbp": 0,
      "wp": 1,
      "be": 38,
      "dec": 1,
      "bs": 0,
      "whip": 0.75,
      "fip": 2.21
    },
    {
      "nombre": "Vladimir Gutiérrez",
      "edad": 29,
      "w": 3,
      "l": 3,
      "pct": 0.5,
      "era": 4.03,
      "eraplus": 95,
      "gp": 11,
      "gs": 11,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 44.2,
      "h": 39,
      "r": 21,
      "er": 20,
      "hr": 4,
      "bb": 14,
      "ibb": 0,
      "so": 40,
      "hbp": 0,
      "wp": 3,
      "be": 183,
      "dec": 6,
      "bs": 0,
      "whip": 1.19,
      "fip": 3.65
    },
    {
      "nombre": "Nick Wittgren",
      "edad": 33,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 2.25,
      "eraplus": 170,
      "gp": 11,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 8,
      "h": 7,
      "r": 2,
      "er": 2,
      "hr": 2,
      "bb": 2,
      "ibb": 0,
      "so": 2,
      "hbp": 0,
      "wp": 1,
      "be": 34,
      "dec": 0,
      "bs": 0,
      "whip": 1.13,
      "fip": 6.83
    },
    {
      "nombre": "Braulio Torres",
      "edad": 31,
      "w": 4,
      "l": 3,
      "pct": 0.571,
      "era": 5.73,
      "eraplus": 67,
      "gp": 11,
      "gs": 9,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 33,
      "h": 41,
      "r": 23,
      "er": 21,
      "hr": 3,
      "bb": 5,
      "ibb": 0,
      "so": 27,
      "hbp": 3,
      "wp": 3,
      "be": 146,
      "dec": 7,
      "bs": 0,
      "whip": 1.39,
      "fip": 3.61
    },
    {
      "nombre": "Enny Romero",
      "edad": 33,
      "w": 6,
      "l": 1,
      "pct": 0.857,
      "era": 1.24,
      "eraplus": 308,
      "gp": 10,
      "gs": 10,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 51,
      "h": 36,
      "r": 9,
      "er": 7,
      "hr": 0,
      "bb": 19,
      "ibb": 0,
      "so": 47,
      "hbp": 2,
      "wp": 2,
      "be": 201,
      "dec": 7,
      "bs": 0,
      "whip": 1.08,
      "fip": 2.73
    },
    {
      "nombre": "Rodrigo Benoit",
      "edad": 30,
      "w": 2,
      "l": 0,
      "pct": 1,
      "era": 0.87,
      "eraplus": 439,
      "gp": 10,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 10.1,
      "h": 8,
      "r": 2,
      "er": 1,
      "hr": 0,
      "bb": 3,
      "ibb": 2,
      "so": 4,
      "hbp": 2,
      "wp": 0,
      "be": 44,
      "dec": 2,
      "bs": 0,
      "whip": 1.06,
      "fip": 4.01
    },
    {
      "nombre": "Welinton Herrera",
      "edad": 20,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 1.8,
      "eraplus": 212,
      "gp": 10,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 10,
      "h": 7,
      "r": 2,
      "er": 2,
      "hr": 0,
      "bb": 6,
      "ibb": 1,
      "so": 13,
      "hbp": 1,
      "wp": 0,
      "be": 42,
      "dec": 0,
      "bs": 0,
      "whip": 1.3,
      "fip": 2.83
    },
    {
      "nombre": "Kurt Heyer",
      "edad": 33,
      "w": 1,
      "l": 0,
      "pct": 1,
      "era": 8,
      "eraplus": 48,
      "gp": 9,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 9,
      "h": 8,
      "r": 8,
      "er": 8,
      "hr": 1,
      "bb": 4,
      "ibb": 1,
      "so": 8,
      "hbp": 0,
      "wp": 0,
      "be": 37,
      "dec": 1,
      "bs": 0,
      "whip": 1.33,
      "fip": 4.33
    },
    {
      "nombre": "Nathanael Heredia",
      "edad": 24,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 7.71,
      "eraplus": 50,
      "gp": 9,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 7,
      "h": 7,
      "r": 6,
      "er": 6,
      "hr": 1,
      "bb": 8,
      "ibb": 0,
      "so": 7,
      "hbp": 2,
      "wp": 0,
      "be": 37,
      "dec": 0,
      "bs": 0,
      "whip": 2.14,
      "fip": 7.48
    },
    {
      "nombre": "Dinelson Lamet",
      "edad": 32,
      "w": 0,
      "l": 1,
      "pct": 0,
      "era": 4.7,
      "eraplus": 81,
      "gp": 8,
      "gs": 3,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 15.1,
      "h": 15,
      "r": 9,
      "er": 8,
      "hr": 3,
      "bb": 7,
      "ibb": 1,
      "so": 10,
      "hbp": 0,
      "wp": 2,
      "be": 67,
      "dec": 1,
      "bs": 0,
      "whip": 1.43,
      "fip": 5.94
    },
    {
      "nombre": "Wirfin Obispo",
      "edad": 40,
      "w": 0,
      "l": 0,
      "pct": 0,
      "era": 6.75,
      "eraplus": 57,
      "gp": 6,
      "gs": 0,
      "cg": 0,
      "sho": 0,
      "sv": 0,
      "ip": 5.1,
      "h": 4,
      "r": 4,
      "er": 4,
      "hr": 1,
      "bb": 2,
      "ibb": 0,
      "so": 6,
      "hbp": 1,
      "wp": 0,
      "be": 23,
      "dec": 0,
      "bs": 0,
      "whip": 1.13,
      "fip": 5.21
    },
    {
        "nombre": "Carlos Espinal",
        "edad": 28,
        "w": 1,
        "l": 0,
        "pct": 1,
        "era": 7.36,
        "eraplus": 52,
        "gp": 6,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 7.1,
        "h": 9,
        "r": 7,
        "er": 6,
        "hr": 1,
        "bb": 4,
        "ibb": 0,
        "so": 6,
        "hbp": 0,
        "wp": 0,
        "be": 34,
        "dec": 1,
        "bs": 0,
        "whip": 1.77,
        "fip": 5.11
      },
      {
        "nombre": "Pedro Payano",
        "edad": 30,
        "w": 1,
        "l": 0,
        "pct": 1,
        "era": 7.2,
        "eraplus": 53,
        "gp": 6,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 5,
        "h": 2,
        "r": 4,
        "er": 4,
        "hr": 1,
        "bb": 7,
        "ibb": 0,
        "so": 3,
        "hbp": 1,
        "wp": 0,
        "be": 24,
        "dec": 1,
        "bs": 0,
        "whip": 1.8,
        "fip": 9.54
      },
      {
        "nombre": "Yoan López",
        "edad": 32,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 10.8,
        "eraplus": 35,
        "gp": 6,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 5,
        "h": 4,
        "r": 6,
        "er": 6,
        "hr": 1,
        "bb": 4,
        "ibb": 0,
        "so": 4,
        "hbp": 1,
        "wp": 0,
        "be": 24,
        "dec": 0,
        "bs": 0,
        "whip": 1.6,
        "fip": 7.33
      },
      {
        "nombre": "Gerson Garabito",
        "edad": 29,
        "w": 0,
        "l": 2,
        "pct": 0,
        "era": 5.48,
        "eraplus": 70,
        "gp": 6,
        "gs": 6,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 21.1,
        "h": 22,
        "r": 13,
        "er": 13,
        "hr": 1,
        "bb": 10,
        "ibb": 0,
        "so": 16,
        "hbp": 1,
        "wp": 1,
        "be": 95,
        "dec": 2,
        "bs": 0,
        "whip": 1.5,
        "fip": 3.99
      },
      {
        "nombre": "José Ureña",
        "edad": 33,
        "w": 0,
        "l": 1,
        "pct": 0,
        "era": 7.88,
        "eraplus": 48,
        "gp": 5,
        "gs": 2,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 8,
        "h": 15,
        "r": 10,
        "er": 7,
        "hr": 1,
        "bb": 1,
        "ibb": 0,
        "so": 7,
        "hbp": 1,
        "wp": 1,
        "be": 41,
        "dec": 1,
        "bs": 0,
        "whip": 2,
        "fip": 3.96
      },
      {
        "nombre": "Evan Sisk",
        "edad": 27,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 15,
        "eraplus": 25,
        "gp": 5,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 3,
        "h": 9,
        "r": 5,
        "er": 5,
        "hr": 1,
        "bb": 2,
        "ibb": 0,
        "so": 5,
        "hbp": 1,
        "wp": 0,
        "be": 22,
        "dec": 0,
        "bs": 0,
        "whip": 3.67,
        "fip": 7.33
      },
      {
        "nombre": "Daniel Missaki",
        "edad": 28,
        "w": 2,
        "l": 0,
        "pct": 1,
        "era": 1.5,
        "eraplus": 255,
        "gp": 5,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 1,
        "ip": 6,
        "h": 2,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 4,
        "ibb": 2,
        "so": 8,
        "hbp": 1,
        "wp": 2,
        "be": 25,
        "dec": 2,
        "bs": 0,
        "whip": 1,
        "fip": 3.17
      },
      {
        "nombre": "Tyler Viza",
        "edad": 30,
        "w": 0,
        "l": 1,
        "pct": 0,
        "era": 11.25,
        "eraplus": 34,
        "gp": 4,
        "gs": 3,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 8,
        "h": 14,
        "r": 12,
        "er": 10,
        "hr": 0,
        "bb": 4,
        "ibb": 0,
        "so": 4,
        "hbp": 0,
        "wp": 0,
        "be": 41,
        "dec": 1,
        "bs": 0,
        "whip": 2.25,
        "fip": 3.83
      },
      {
        "nombre": "Keone Kela",
        "edad": 31,
        "w": 0,
        "l": 1,
        "pct": 0,
        "era": 12,
        "eraplus": 32,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 3,
        "h": 3,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 5,
        "ibb": 0,
        "so": 5,
        "hbp": 0,
        "wp": 1,
        "be": 16,
        "dec": 1,
        "bs": 0,
        "whip": 2.67,
        "fip": 5
      },
      {
        "nombre": "Thyago Vieira",
        "edad": 32,
        "w": 0,
        "l": 1,
        "pct": 0,
        "era": 6,
        "eraplus": 64,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 3,
        "h": 6,
        "r": 3,
        "er": 2,
        "hr": 0,
        "bb": 2,
        "ibb": 1,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 17,
        "dec": 1,
        "bs": 0,
        "whip": 2.67,
        "fip": 4.67
      },
      {
        "nombre": "Edwin Nuñez",
        "edad": 23,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 8.1,
        "eraplus": 47,
        "gp": 4,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 3.1,
        "h": 7,
        "r": 4,
        "er": 3,
        "hr": 1,
        "bb": 0,
        "ibb": 0,
        "so": 2,
        "hbp": 0,
        "wp": 0,
        "be": 17,
        "dec": 0,
        "bs": 0,
        "whip": 2.1,
        "fip": 6.04
      },
      {
        "nombre": "Johnny Cueto",
        "edad": 38,
        "w": 0,
        "l": 2,
        "pct": 0,
        "era": 5.4,
        "eraplus": 71,
        "gp": 3,
        "gs": 3,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 10,
        "h": 8,
        "r": 8,
        "er": 6,
        "hr": 3,
        "bb": 8,
        "ibb": 0,
        "so": 4,
        "hbp": 0,
        "wp": 0,
        "be": 47,
        "dec": 2,
        "bs": 0,
        "whip": 1.6,
        "fip": 8.84
      },
      {
        "nombre": "Carlos Peña",
        "edad": 26,
        "w": 0,
        "l": 1,
        "pct": 0,
        "era": 6.35,
        "eraplus": 60,
        "gp": 3,
        "gs": 1,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 5.2,
        "h": 8,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 3,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 0,
        "be": 28,
        "dec": 1,
        "bs": 0,
        "whip": 1.94,
        "fip": 3.86
      },
      {
        "nombre": "Daison Acosta",
        "edad": 26,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 0,
        "eraplus": "Inf",
        "gp": 3,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 2,
        "h": 3,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 3,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 2,
        "be": 12,
        "dec": 0,
        "bs": 0,
        "whip": 3,
        "fip": 6.83
      },
      {
        "nombre": "Marcos Diplan",
        "edad": 28,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 20.26,
        "eraplus": 19,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.3,
        "h": 1,
        "r": 3,
        "er": 3,
        "hr": 0,
        "bb": 4,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 3,
        "be": 8,
        "dec": 0,
        "bs": 0,
        "whip": 3.75,
        "fip": 12.34
      },
      {
        "nombre": "Anderson Paulino",
        "edad": 26,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 36,
        "eraplus": 11,
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1,
        "h": 3,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 6,
        "dec": 0,
        "bs": 0,
        "whip": 4,
        "fip": 6.33
      },
      {
        "nombre": "Randy Wynne",
        "edad": 31,
        "w": 1,
        "l": 0,
        "pct": 1,
        "era": 1,
        "eraplus": 382,
        "gp": 2,
        "gs": 2,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 9,
        "h": 8,
        "r": 1,
        "er": 1,
        "hr": 0,
        "bb": 2,
        "ibb": 0,
        "so": 3,
        "hbp": 0,
        "wp": 0,
        "be": 33,
        "dec": 1,
        "bs": 0,
        "whip": 1.11,
        "fip": 3.33
      },
      {
        "nombre": "Raúl Brito",
        "edad": 27,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 0,
        "eraplus": "Inf",
        "gp": 2,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 1.6,
        "h": 1,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 5,
        "dec": 0,
        "bs": 0,
        "whip": 1.2,
        "fip": 3.93
      },
      {
        "nombre": "Ramón Rossó",
        "edad": 28,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 54.05,
        "eraplus": 7,
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.3,
        "h": 0,
        "r": 2,
        "er": 2,
        "hr": 0,
        "bb": 2,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 3,
        "dec": 0,
        "bs": 0,
        "whip": 6.01,
        "fip": 15.35
      },
      {
        "nombre": "Carlos Paulino",
        "edad": 35,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": "Inf",
        "eraplus": 0,
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0,
        "h": 5,
        "r": 5,
        "er": 5,
        "hr": 0,
        "bb": 0,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 6,
        "dec": 0,
        "bs": 0,
        "whip": "Inf",
        "fip": 0
      },
      {
        "nombre": "Alfredo Reyes",
        "edad": 31,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 0,
        "eraplus": "Inf",
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.3,
        "h": 1,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 0,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 2,
        "dec": 0,
        "bs": 0,
        "whip": 3,
        "fip": 3.33
      },
      {
        "nombre": "Sam McWilliams",
        "edad": 27,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 0,
        "eraplus": "Inf",
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.3,
        "h": 1,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 1,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 3,
        "dec": 0,
        "bs": 0,
        "whip": 6.01,
        "fip": 12.34
      },{
        "nombre": "Wilmy Sanchez",
        "edad": 21,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 53.97,
        "eraplus": 7,
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.7,
        "h": 3,
        "r": 4,
        "er": 4,
        "hr": 0,
        "bb": 2,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 2,
        "be": 7,
        "dec": 0,
        "bs": 0,
        "whip": 7.5,
        "fip": 12.33
      },
      {
        "nombre": "Deury Carrasco",
        "edad": 25,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 0,
        "eraplus": "Inf",
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.3,
        "h": 0,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 0,
        "ibb": 0,
        "so": 0,
        "hbp": 0,
        "wp": 0,
        "be": 1,
        "dec": 0,
        "bs": 0,
        "whip": 0,
        "fip": 3.33
      },
      {
        "nombre": "Delvis Alegre",
        "edad": 23,
        "w": 0,
        "l": 0,
        "pct": 0,
        "era": 0,
        "eraplus": "Inf",
        "gp": 1,
        "gs": 0,
        "cg": 0,
        "sho": 0,
        "sv": 0,
        "ip": 0.3,
        "h": 0,
        "r": 0,
        "er": 0,
        "hr": 0,
        "bb": 0,
        "ibb": 0,
        "so": 1,
        "hbp": 0,
        "wp": 0,
        "be": 1,
        "dec": 0,
        "bs": 0,
        "whip": 0,
        "fip": -2.67
      },
      {
        "nombre": "Totales",
        "edad": 30,
        "w": 28,
        "l": 22,
        "pct": 0.56,
        "era": 4.37,
        "eraplus": 0,
        "gp": 336,
        "gs": 50,
        "cg": 0,
        "sho": 0,
        "sv": 14,
        "ip": 436.2,
        "h": 416,
        "r": 234,
        "er": 212,
        "hr": 32,
        "bb": 205,
        "ibb": 12,
        "so": 377,
        "hbp": 22,
        "wp": 33,
        "be": 1910,
        "dec": 50,
        "bs": 0,
        "whip": 1.42,
        "fip": 0
      }
    ]
  

function formatNumber(value: number): string {
  return value === 0 ? ".000" : value.toString().replace("0.", ".");
}

export default function Page() {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredBatters = batters.filter((jugador) =>
    jugador.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredPitchers = pitchers.filter((pitcher) =>
    pitcher.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-black">
      {/* Encabezado con imagen difuminada */}
      <header className="relative h-64 shadow-xl">
        <div className="absolute inset-0 z-0">
          <img
            src="/Logos/aguilas.png"
            alt="Estadio de béisbol"
            className="object-cover  h-full blur-s "
          />
          <div className="absolute inset-0 bg-black/30" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-4xl font-bold text-white mb-4 drop-shadow-lg">
            Estadísticas del Equipo Aguilas Cibaeñas
          </h1>
          <p className="text-xl text-white/90 drop-shadow-md">
            Temporada 2024 Serie Regular
          </p>
        </div>
      </header>

      {/* Contenido principal */}
      <div className="p-6 max-w-9xl mx-auto">
        {/* Barra de búsqueda */}
        <div className="mb-6">
          <input
            type="text"
            placeholder="Buscar jugador..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm"
          />
        </div>

        {/* Sección de Bateadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-yellow-500">Bateadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-black">
              <thead>
              <tr className="bg-yellow-500 text-white ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">POS</th>
            <th className="border border-gray-300 p-2">JJ</th>
            <th className="border border-gray-300 p-2">APP</th>
            <th className="border border-gray-300 p-2">AB</th>
            <th className="border border-gray-300 p-2">C</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">1B</th>
            <th className="border border-gray-300 p-2">2B</th>
            <th className="border border-gray-300 p-2">3B</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">RBI</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">SB</th>
            <th className="border border-gray-300 p-2">CS</th>
            <th className="border border-gray-300 p-2">AVG</th>
            <th className="border border-gray-300 p-2">OBP</th>
            <th className="border border-gray-300 p-2">SLG</th>
            <th className="border border-gray-300 p-2">OPS</th>
            <th className="border border-gray-300 p-2">OPS+</th>
            <th className="border border-gray-300 p-2">TB</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SF</th>
            <th className="border border-gray-300 p-2">S</th>
            <th className="border border-gray-300 p-2">DP</th>
            
          </tr>
              </thead>
              <tbody>
                {filteredBatters.map((jugador, index) => (
                  <tr key={index} className={jugador.nombre === "Totales" ? "bg-yellow-500 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-yellow-300">{jugador.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.pos}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.jj}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.ab}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.app}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.c}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.h}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.b1}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.b2}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.b3}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.rbi}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.so}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.sb}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.cs}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{formatNumber(jugador.avg)}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{formatNumber(jugador.obp)}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{formatNumber(jugador.slg)}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{formatNumber(jugador.ops)}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.opsp}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.tb}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.sf}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.s}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{jugador.dp}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sección de Lanzadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-yellow-500">Lanzadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-black">
              <thead>
              <tr className="bg-yellow-500 ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">W</th>
            <th className="border border-gray-300 p-2">L</th>
            <th className="border border-gray-300 p-2">PCT</th>
            <th className="border border-gray-300 p-2">ERA</th>
            <th className="border border-gray-300 p-2">ERA+</th>
            <th className="border border-gray-300 p-2">GP</th>
            <th className="border border-gray-300 p-2">GS</th>
            <th className="border border-gray-300 p-2">CG</th>
            <th className="border border-gray-300 p-2">SHO</th>
            <th className="border border-gray-300 p-2">SV</th>
            <th className="border border-gray-300 p-2">IP</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">R</th>
            <th className="border border-gray-300 p-2">ER</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">WP</th>
            <th className="border border-gray-300 p-2">BE</th>
            <th className="border border-gray-300 p-2">DEC</th>
            <th className="border border-gray-300 p-2">BS</th>
            <th className="border border-gray-300 p-2">WHIP</th>
            <th className="border border-gray-300 p-2">FIP</th>
          </tr>
              </thead>
              <tbody>
                {filteredPitchers.map((pitcher, index) => (
                  <tr key={index} className={pitcher.nombre === "Totales" ? "bg-yellow-500 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-yellow-300">{pitcher.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.w}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.l}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.pct}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.era}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.eraplus}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.gp}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.gs}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.cg}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.sho}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.sv}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.ip}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.h}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.r}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.er}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.so}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.wp}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.be}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.dec}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.bs}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.whip}</td>
                <td className="border border-gray-300 p-2 text-center text-white">{pitcher.fip}</td>
              </tr>
                  
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}