"use client"

import React, { useState } from 'react';

// Datos de los bateadores (mantenidos igual)
const batters = [
  {
    "nombre": "Magneuris Sierra",
    "edad": 28,
    "pos": "CF",
    "jj": 41,
    "app": 154,
    "ab": 142,
    "c": 22,
    "h": 40,
    "b1": 34,
    "b2": 4,
    "b3": 2,
    "hr": 0,
    "rbi": 16,
    "bb": 7,
    "so": 26,
    "sb": 18,
    "cs": 2,
    "avg": 0.282,
    "obp": 0.309,
    "slg": 0.338,
    "ops": 0.647,
    "opsp": 96,
    "tb": 48,
    "hbp": 0,
    "ibb": 0,
    "sf": 3,
    "s": 2,
    "dp": 0
  },
  {
    "nombre": "José Barrero",
    "edad": 26,
    "pos": "SS",
    "jj": 41,
    "app": 153,
    "ab": 132,
    "c": 22,
    "h": 30,
    "b1": 16,
    "b2": 10,
    "b3": 1,
    "hr": 3,
    "rbi": 23,
    "bb": 16,
    "so": 29,
    "sb": 6,
    "cs": 0,
    "avg": 0.227,
    "obp": 0.314,
    "slg": 0.386,
    "ops": 0.700,
    "opsp": 103,
    "tb": 51,
    "hbp": 2,
    "ibb": 1,
    "sf": 3,
    "s": 0,
    "dp": 4
  },
  {
    "nombre": "Carlos Martínez",
    "edad": 29,
    "pos": "C",
    "jj": 41,
    "app": 111,
    "ab": 97,
    "c": 12,
    "h": 26,
    "b1": 22,
    "b2": 4,
    "b3": 0,
    "hr": 0,
    "rbi": 13,
    "bb": 6,
    "so": 20,
    "sb": 4,
    "cs": 1,
    "avg": 0.268,
    "obp": 0.333,
    "slg": 0.309,
    "ops": 0.642,
    "opsp": 95,
    "tb": 30,
    "hbp": 4,
    "ibb": 0,
    "sf": 1,
    "s": 3,
    "dp": 0
  },
  {
    "nombre": "Rainer Nuñez",
    "edad": 24,
    "pos": "1B",
    "jj": 36,
    "app": 119,
    "ab": 99,
    "c": 8,
    "h": 22,
    "b1": 19,
    "b2": 2,
    "b3": 0,
    "hr": 1,
    "rbi": 6,
    "bb": 17,
    "so": 25,
    "sb": 0,
    "cs": 1,
    "avg": 0.222,
    "obp": 0.353,
    "slg": 0.273,
    "ops": 0.626,
    "opsp": 92,
    "tb": 27,
    "hbp": 3,
    "ibb": 2,
    "sf": 0,
    "s": 0,
    "dp": 5
  },
  {
    "nombre": "Vidal Bruján",
    "edad": 26,
    "pos": "RF",
    "jj": 34,
    "app": 152,
    "ab": 126,
    "c": 21,
    "h": 29,
    "b1": 24,
    "b2": 4,
    "b3": 0,
    "hr": 1,
    "rbi": 17,
    "bb": 20,
    "so": 19,
    "sb": 10,
    "cs": 4,
    "avg": 0.230,
    "obp": 0.344,
    "slg": 0.286,
    "ops": 0.630,
    "opsp": 93,
    "tb": 36,
    "hbp": 3,
    "ibb": 0,
    "sf": 2,
    "s": 1,
    "dp": 2
  },
  {
    "nombre": "Euribiel Angeles",
    "edad": 22,
    "pos": "2B",
    "jj": 34,
    "app": 138,
    "ab": 126,
    "c": 14,
    "h": 31,
    "b1": 26,
    "b2": 4,
    "b3": 1,
    "hr": 0,
    "rbi": 12,
    "bb": 9,
    "so": 17,
    "sb": 2,
    "cs": 1,
    "avg": 0.246,
    "obp": 0.301,
    "slg": 0.294,
    "ops": 0.595,
    "opsp": 88,
    "tb": 37,
    "hbp": 1,
    "ibb": 0,
    "sf": 0,
    "s": 2,
    "dp": 3
  },
  {
    "nombre": "Ismael Munguia",
    "edad": 26,
    "pos": "LF",
    "jj": 34,
    "app": 141,
    "ab": 121,
    "c": 18,
    "h": 35,
    "b1": 29,
    "b2": 3,
    "b3": 3,
    "hr": 0,
    "rbi": 15,
    "bb": 12,
    "so": 11,
    "sb": 13,
    "cs": 0,
    "avg": 0.289,
    "obp": 0.374,
    "slg": 0.364,
    "ops": 0.738,
    "opsp": 109,
    "tb": 44,
    "hbp": 5,
    "ibb": 3,
    "sf": 1,
    "s": 2,
    "dp": 2
  },
  {
    "nombre": "Raimel Tapia",
    "edad": 30,
    "pos": "LF",
    "jj": 32,
    "app": 131,
    "ab": 123,
    "c": 16,
    "h": 34,
    "b1": 26,
    "b2": 7,
    "b3": 0,
    "hr": 1,
    "rbi": 13,
    "bb": 7,
    "so": 24,
    "sb": 8,
    "cs": 0,
    "avg": 0.276,
    "obp": 0.321,
    "slg": 0.350,
    "ops": 0.671,
    "opsp": 99,
    "tb": 43,
    "hbp": 1,
    "ibb": 1,
    "sf": 0,
    "s": 0,
    "dp": 5
  },
  {
    "nombre": "Eguy Rosario",
    "edad": 25,
    "pos": "3B",
    "jj": 31,
    "app": 130,
    "ab": 116,
    "c": 14,
    "h": 39,
    "b1": 27,
    "b2": 8,
    "b3": 0,
    "hr": 4,
    "rbi": 20,
    "bb": 12,
    "so": 19,
    "sb": 4,
    "cs": 1,
    "avg": 0.336,
    "obp": 0.395,
    "slg": 0.509,
    "ops": 0.904,
    "opsp": 134,
    "tb": 59,
    "hbp": 0,
    "ibb": 1,
    "sf": 1,
    "s": 1,
    "dp": 2
  },
  {
    "nombre": "Enmanuel Valdez",
    "edad": 26,
    "pos": "2B",
    "jj": 31,
    "app": 118,
    "ab": 103,
    "c": 15,
    "h": 18,
    "b1": 13,
    "b2": 2,
    "b3": 1,
    "hr": 2,
    "rbi": 11,
    "bb": 14,
    "so": 17,
    "sb": 1,
    "cs": 0,
    "avg": 0.175,
    "obp": 0.280,
    "slg": 0.272,
    "ops": 0.552,
    "opsp": 82,
    "tb": 28,
    "hbp": 1,
    "ibb": 3,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Wilin Rosario",
    "edad": 35,
    "pos": "C",
    "jj": 23,
    "app": 43,
    "ab": 36,
    "c": 5,
    "h": 11,
    "b1": 5,
    "b2": 3,
    "b3": 0,
    "hr": 3,
    "rbi": 12,
    "bb": 7,
    "so": 10,
    "sb": 0,
    "cs": 0,
    "avg": 0.306,
    "obp": 0.419,
    "slg": 0.639,
    "ops": 1.058,
    "opsp": 156,
    "tb": 23,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 2
  },
  {
    "nombre": "Abraham Almonte",
    "edad": 35,
    "pos": "PH",
    "jj": 22,
    "app": 69,
    "ab": 54,
    "c": 9,
    "h": 6,
    "b1": 5,
    "b2": 0,
    "b3": 0,
    "hr": 1,
    "rbi": 4,
    "bb": 15,
    "so": 18,
    "sb": 2,
    "cs": 0,
    "avg": 0.111,
    "obp": 0.304,
    "slg": 0.167,
    "ops": 0.471,
    "opsp": 70,
    "tb": 9,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Miguel Sanó",
    "edad": 31,
    "pos": "1B",
    "jj": 19,
    "app": 79,
    "ab": 68,
    "c": 13,
    "h": 18,
    "b1": 11,
    "b2": 2,
    "b3": 0,
    "hr": 5,
    "rbi": 14,
    "bb": 9,
    "so": 20,
    "sb": 0,
    "cs": 0,
    "avg": 0.265,
    "obp": 0.342,
    "slg": 0.515,
    "ops": 0.857,
    "opsp": 127,
    "tb": 35,
    "hbp": 0,
    "ibb": 1,
    "sf": 2,
    "s": 0,
    "dp": 4
  },
  {
    "nombre": "Frank Schwindel",
    "edad": 32,
    "pos": "1B",
    "jj": 16,
    "app": 55,
    "ab": 54,
    "c": 6,
    "h": 13,
    "b1": 8,
    "b2": 5,
    "b3": 0,
    "hr": 0,
    "rbi": 4,
    "bb": 1,
    "so": 13,
    "sb": 1,
    "cs": 1,
    "avg": 0.241,
    "obp": 0.255,
    "slg": 0.333,
    "ops": 0.588,
    "opsp": 87,
    "tb": 18,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Juan Guerrero",
    "edad": 23,
    "pos": "RF",
    "jj": 15,
    "app": 40,
    "ab": 33,
    "c": 1,
    "h": 5,
    "b1": 4,
    "b2": 1,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 3,
    "so": 5,
    "sb": 1,
    "cs": 1,
    "avg": 0.152,
    "obp": 0.222,
    "slg": 0.182,
    "ops": 0.404,
    "opsp": 60,
    "tb": 6,
    "hbp": 0,
    "ibb": 1,
    "sf": 0,
    "s": 4,
    "dp": 1
  },
  {
    "nombre": "Willy Vasquez",
    "edad": 23,
    "pos": "3B",
    "jj": 12,
    "app": 19,
    "ab": 14,
    "c": 4,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 4,
    "so": 7,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.222,
    "slg": 0.000,
    "ops": 0.222,
    "opsp": 33,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 1,
    "dp": 0
  },
  {
    "nombre": "Rodolfo Castro",
    "edad": 25,
    "pos": "2B",
    "jj": 11,
    "app": 45,
    "ab": 39,
    "c": 6,
    "h": 7,
    "b1": 5,
    "b2": 2,
    "b3": 0,
    "hr": 0,
    "rbi": 1,
    "bb": 6,
    "so": 9,
    "sb": 1,
    "cs": 0,
    "avg": 0.179,
    "obp": 0.289,
    "slg": 0.231,
    "ops": 0.520,
    "opsp": 77,
    "tb": 9,
    "hbp": 0,
    "ibb": 2,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Jose Tena",
    "edad": 23,
    "pos": "2B",
    "jj": 10,
    "app": 41,
    "ab": 36,
    "c": 2,
    "h": 8,
    "b1": 4,
    "b2": 4,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 3,
    "so": 13,
    "sb": 0,
    "cs": 1,
    "avg": 0.222,
    "obp": 0.282,
    "slg": 0.333,
    "ops": 0.615,
    "opsp": 91,
    "tb": 12,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 2,
    "dp": 0
  },
  {
    "nombre": "Robinson Canó",
    "edad": 42,
    "pos": "DH",
    "jj": 9,
    "app": 38,
    "ab": 34,
    "c": 2,
    "h": 12,
    "b1": 10,
    "b2": 1,
    "b3": 0,
    "hr": 1,
    "rbi": 6,
    "bb": 3,
    "so": 5,
    "sb": 0,
    "cs": 0,
    "avg": 0.353,
    "obp": 0.395,
    "slg": 0.471,
    "ops": 0.866,
    "opsp": 128,
    "tb": 16,
    "hbp": 0,
    "ibb": 2,
    "sf": 1,
    "s": 0,
    "dp": 0
  },{
    "nombre": "Moisés Castillo",
    "edad": 25,
    "pos": "2B",
    "jj": 9,
    "app": 10,
    "ab": 8,
    "c": 1,
    "h": 3,
    "b1": 3,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 1,
    "bb": 2,
    "so": 1,
    "sb": 1,
    "cs": 0,
    "avg": 0.375,
    "obp": 0.500,
    "slg": 0.375,
    "ops": 0.875,
    "opsp": 129,
    "tb": 3,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "David Bañuelos",
    "edad": 30,
    "pos": "C",
    "jj": 8,
    "app": 20,
    "ab": 20,
    "c": 3,
    "h": 3,
    "b1": 2,
    "b2": 1,
    "b3": 0,
    "hr": 0,
    "rbi": 5,
    "bb": 0,
    "so": 9,
    "sb": 0,
    "cs": 0,
    "avg": 0.150,
    "obp": 0.150,
    "slg": 0.200,
    "ops": 0.350,
    "opsp": 52,
    "tb": 4,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Arismendy Alcántara",
    "edad": 33,
    "pos": "PR",
    "jj": 7,
    "app": 7,
    "ab": 7,
    "c": 2,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 1,
    "bb": 0,
    "so": 2,
    "sb": 0,
    "cs": 0,
    "avg": 0.143,
    "obp": 0.143,
    "slg": 0.143,
    "ops": 0.286,
    "opsp": 42,
    "tb": 1,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Danny Santana",
    "edad": 34,
    "pos": "DH",
    "jj": 7,
    "app": 25,
    "ab": 21,
    "c": 1,
    "h": 3,
    "b1": 3,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 1,
    "so": 3,
    "sb": 1,
    "cs": 2,
    "avg": 0.143,
    "obp": 0.208,
    "slg": 0.143,
    "ops": 0.351,
    "opsp": 52,
    "tb": 3,
    "hbp": 1,
    "ibb": 0,
    "sf": 1,
    "s": 1,
    "dp": 0
  },
  {
    "nombre": "Bryan Lavastida",
    "edad": 26,
    "pos": "C",
    "jj": 7,
    "app": 18,
    "ab": 18,
    "c": 2,
    "h": 5,
    "b1": 5,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 0,
    "so": 4,
    "sb": 1,
    "cs": 0,
    "avg": 0.278,
    "obp": 0.278,
    "slg": 0.278,
    "ops": 0.556,
    "opsp": 82,
    "tb": 5,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Junior Perez",
    "edad": 23,
    "pos": "PR",
    "jj": 6,
    "app": 2,
    "ab": 1,
    "c": 2,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 1,
    "so": 1,
    "sb": 0,
    "cs": 1,
    "avg": 0.000,
    "obp": 0.500,
    "slg": 0.000,
    "ops": 0.500,
    "opsp": 74,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Christian Cerda",
    "edad": 22,
    "pos": "C",
    "jj": 6,
    "app": 10,
    "ab": 4,
    "c": 1,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 4,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 0.250,
    "obp": 0.667,
    "slg": 0.250,
    "ops": 0.917,
    "opsp": 135,
    "tb": 1,
    "hbp": 1,
    "ibb": 0,
    "sf": 0,
    "s": 1,
    "dp": 0
  },
  {
    "nombre": "Oscar González",
    "edad": 26,
    "pos": "LF",
    "jj": 5,
    "app": 23,
    "ab": 22,
    "c": 2,
    "h": 6,
    "b1": 4,
    "b2": 2,
    "b3": 0,
    "hr": 0,
    "rbi": 3,
    "bb": 1,
    "so": 4,
    "sb": 0,
    "cs": 0,
    "avg": 0.273,
    "obp": 0.304,
    "slg": 0.364,
    "ops": 0.668,
    "opsp": 99,
    "tb": 8,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "JP Martinez",
    "edad": 28,
    "pos": "RF",
    "jj": 5,
    "app": 13,
    "ab": 9,
    "c": 4,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 4,
    "so": 3,
    "sb": 2,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.308,
    "slg": 0.000,
    "ops": 0.308,
    "opsp": 45,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Rubel Céspedes",
    "edad": 24,
    "pos": "1B",
    "jj": 3,
    "app": 4,
    "ab": 4,
    "c": 1,
    "h": 2,
    "b1": 1,
    "b2": 1,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 0.500,
    "obp": 0.500,
    "slg": 0.750,
    "ops": 1.250,
    "opsp": 185,
    "tb": 3,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Tomás Telis",
    "edad": 33,
    "pos": "C",
    "jj": 1,
    "app": 4,
    "ab": 4,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 2,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Roderick Arias",
    "edad": 20,
    "pos": "PH",
    "jj": 1,
    "app": 2,
    "ab": 2,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 2,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Yerlin Confidan",
    "edad": 22,
    "pos": "PH",
    "jj": 1,
    "app": 1,
    "ab": 1,
    "c": 0,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 1,
    "bb": 0,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 1.000,
    "obp": 1.000,
    "slg": 1.000,
    "ops": 2.000,
    "opsp": 295,
    "tb": 1,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Wilfredo Tovar",
    "edad": 33,
    "pos": "3B",
    "jj": 1,
    "app": 4,
    "ab": 4,
    "c": 0,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 1,
    "sb": 1,
    "cs": 0,
    "avg": 0.250,
    "obp": 0.250,
    "slg": 0.250,
    "ops": 0.500,
    "opsp": 74,
    "tb": 1,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Totales",
    "edad": 28,
    "pos": "",
    "jj": 559,
    "app": 1919,
    "ab": 1678,
    "c": 229,
    "h": 410,
    "b1": 310,
    "b2": 70,
    "b3": 8,
    "hr": 22,
    "rbi": 206,
    "bb": 184,
    "so": 339,
    "sb": 77,
    "cs": 16,
    "avg": 0.244,
    "obp": 0.324,
    "slg": 0.334,
    "ops": 0.658,
    "opsp": 0,
    "tb": 561,
    "hbp": 22,
    "ibb": 17,
    "sf": 15,
    "s": 20,
    "dp": 35
  }
];

// Datos de los lanzadores (mantenidos igual)
const pitchers = [
  {
    "nombre": "Jefry Yan",
    "edad": 28,
    "w": 0,
    "l": 2,
    "pct": 0.000,
    "era": 1.71,
    "eraplus": 223,
    "gp": 25,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 21,
    "h": 16,
    "r": 5,
    "er": 4,
    "hr": 2,
    "bb": 12,
    "ibb": 2,
    "so": 26,
    "hbp": 1,
    "wp": 5,
    "be": 89,
    "dec": 2,
    "bs": 0,
    "whip": 1.33,
    "fip": 3.95
  },
  {
    "nombre": "José Manuel Fernández",
    "edad": 31,
    "w": 3,
    "l": 0,
    "pct": 1.000,
    "era": 0.61,
    "eraplus": 626,
    "gp": 23,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.2,
    "h": 8,
    "r": 3,
    "er": 1,
    "hr": 0,
    "bb": 3,
    "ibb": 1,
    "so": 10,
    "hbp": 0,
    "wp": 0,
    "be": 54,
    "dec": 3,
    "bs": 0,
    "whip": 0.75,
    "fip": 2.58
  },
  {
    "nombre": "Neftalí Féliz",
    "edad": 36,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 2.11,
    "eraplus": 181,
    "gp": 22,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 9,
    "ip": 21.1,
    "h": 14,
    "r": 5,
    "er": 5,
    "hr": 0,
    "bb": 11,
    "ibb": 1,
    "so": 16,
    "hbp": 1,
    "wp": 0,
    "be": 87,
    "dec": 1,
    "bs": 0,
    "whip": 1.17,
    "fip": 3.52
  },
  {
    "nombre": "Gerónimo Franzuá",
    "edad": 31,
    "w": 3,
    "l": 1,
    "pct": 0.750,
    "era": 1.50,
    "eraplus": 255,
    "gp": 20,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 18,
    "h": 17,
    "r": 3,
    "er": 3,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 16,
    "hbp": 2,
    "wp": 0,
    "be": 71,
    "dec": 4,
    "bs": 1,
    "whip": 1.06,
    "fip": 2.22
  },
  {
    "nombre": "Carlos Belén",
    "edad": 28,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.64,
    "eraplus": 597,
    "gp": 20,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14,
    "h": 10,
    "r": 2,
    "er": 1,
    "hr": 0,
    "bb": 8,
    "ibb": 0,
    "so": 12,
    "hbp": 1,
    "wp": 1,
    "be": 58,
    "dec": 0,
    "bs": 0,
    "whip": 1.29,
    "fip": 3.55
  },
  {
    "nombre": "Elvis Alvarado",
    "edad": 27,
    "w": 2,
    "l": 2,
    "pct": 0.500,
    "era": 0.93,
    "eraplus": 411,
    "gp": 20,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 19.1,
    "h": 9,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 9,
    "ibb": 0,
    "so": 26,
    "hbp": 3,
    "wp": 1,
    "be": 79,
    "dec": 4,
    "bs": 0,
    "whip": 0.93,
    "fip": 2.51
  },
  {
    "nombre": "Patrick Weigel",
    "edad": 30,
    "w": 2,
    "l": 0,
    "pct": 1.000,
    "era": 0.95,
    "eraplus": 402,
    "gp": 18,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 1,
    "ip": 19,
    "h": 12,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 5,
    "ibb": 1,
    "so": 22,
    "hbp": 2,
    "wp": 2,
    "be": 72,
    "dec": 2,
    "bs": 0,
    "whip": 0.89,
    "fip": 2.12
  },
  {
    "nombre": "Roman Méndez",
    "edad": 34,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 5.40,
    "eraplus": 71,
    "gp": 17,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 10,
    "h": 9,
    "r": 6,
    "er": 6,
    "hr": 1,
    "bb": 4,
    "ibb": 0,
    "so": 9,
    "hbp": 0,
    "wp": 2,
    "be": 43,
    "dec": 0,
    "bs": 0,
    "whip": 1.30,
    "fip": 4.03
  },
  {
    "nombre": "Julián Fernández",
    "edad": 29,
    "w": 1,
    "l": 1,
    "pct": 0.500,
    "era": 4.30,
    "eraplus": 89,
    "gp": 16,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.2,
    "h": 16,
    "r": 8,
    "er": 7,
    "hr": 0,
    "bb": 8,
    "ibb": 1,
    "so": 20,
    "hbp": 0,
    "wp": 1,
    "be": 67,
    "dec": 2,
    "bs": 0,
    "whip": 1.64,
    "fip": 2.24
  },
  {
    "nombre": "Raffi Vizcaíno",
    "edad": 29,
    "w": 1,
    "l": 1,
    "pct": 0.500,
    "era": 9.49,
    "eraplus": 40,
    "gp": 14,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 12.1,
    "h": 20,
    "r": 14,
    "er": 13,
    "hr": 2,
    "bb": 5,
    "ibb": 1,
    "so": 11,
    "hbp": 4,
    "wp": 2,
    "be": 67,
    "dec": 2,
    "bs": 0,
    "whip": 2.03,
    "fip": 5.85
  },
  {
    "nombre": "Spencer Patton",
    "edad": 36,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.69,
    "eraplus": 554,
    "gp": 13,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 13,
    "h": 5,
    "r": 3,
    "er": 1,
    "hr": 1,
    "bb": 3,
    "ibb": 1,
    "so": 14,
    "hbp": 3,
    "wp": 1,
    "be": 49,
    "dec": 0,
    "bs": 0,
    "whip": 0.62,
    "fip": 3.57
  },{
    "nombre": "Andy Otero",
    "edad": 32,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.21,
    "eraplus": 119,
    "gp": 13,
    "gs": 11,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 33.2,
    "h": 37,
    "r": 15,
    "er": 12,
    "hr": 1,
    "bb": 11,
    "ibb": 0,
    "so": 28,
    "hbp": 0,
    "wp": 0,
    "be": 151,
    "dec": 0,
    "bs": 0,
    "whip": 1.43,
    "fip": 3.04
  },
  {
    "nombre": "Oscar De La Cruz",
    "edad": 29,
    "w": 3,
    "l": 2,
    "pct": 0.600,
    "era": 3.40,
    "eraplus": 112,
    "gp": 11,
    "gs": 7,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 39.2,
    "h": 29,
    "r": 15,
    "er": 15,
    "hr": 5,
    "bb": 10,
    "ibb": 0,
    "so": 38,
    "hbp": 1,
    "wp": 1,
    "be": 160,
    "dec": 5,
    "bs": 0,
    "whip": 0.98,
    "fip": 3.89
  },
  {
    "nombre": "Luis Moreno",
    "edad": 25,
    "w": 2,
    "l": 2,
    "pct": 0.500,
    "era": 1.83,
    "eraplus": 209,
    "gp": 11,
    "gs": 10,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 39.1,
    "h": 23,
    "r": 13,
    "er": 8,
    "hr": 0,
    "bb": 15,
    "ibb": 0,
    "so": 37,
    "hbp": 3,
    "wp": 3,
    "be": 153,
    "dec": 4,
    "bs": 0,
    "whip": 0.97,
    "fip": 2.83
  },
  {
    "nombre": "Felipe De La Cruz",
    "edad": 23,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 5.40,
    "eraplus": 71,
    "gp": 11,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 16.2,
    "h": 22,
    "r": 12,
    "er": 10,
    "hr": 3,
    "bb": 8,
    "ibb": 1,
    "so": 17,
    "hbp": 1,
    "wp": 1,
    "be": 79,
    "dec": 1,
    "bs": 0,
    "whip": 1.80,
    "fip": 5.26
  },
  {
    "nombre": "Jorge Martínez",
    "edad": 39,
    "w": 1,
    "l": 1,
    "pct": 0.500,
    "era": 3.33,
    "eraplus": 115,
    "gp": 10,
    "gs": 5,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 27,
    "h": 32,
    "r": 12,
    "er": 10,
    "hr": 0,
    "bb": 7,
    "ibb": 0,
    "so": 17,
    "hbp": 3,
    "wp": 0,
    "be": 122,
    "dec": 2,
    "bs": 0,
    "whip": 1.44,
    "fip": 3.19
  },
  {
    "nombre": "Carlos Gómez",
    "edad": 26,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 2.08,
    "eraplus": 184,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.1,
    "h": 5,
    "r": 2,
    "er": 1,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 4,
    "hbp": 1,
    "wp": 0,
    "be": 20,
    "dec": 1,
    "bs": 0,
    "whip": 1.62,
    "fip": 3.57
  },
  {
    "nombre": "Abdiel Mendoza",
    "edad": 26,
    "w": 3,
    "l": 1,
    "pct": 0.750,
    "era": 2.75,
    "eraplus": 139,
    "gp": 9,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 1,
    "ip": 16.1,
    "h": 18,
    "r": 6,
    "er": 5,
    "hr": 1,
    "bb": 7,
    "ibb": 0,
    "so": 14,
    "hbp": 2,
    "wp": 1,
    "be": 74,
    "dec": 4,
    "bs": 0,
    "whip": 1.53,
    "fip": 4.07
  },
  {
    "nombre": "Enoli Paredes",
    "edad": 29,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 1.17,
    "eraplus": 326,
    "gp": 8,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 7.2,
    "h": 8,
    "r": 3,
    "er": 1,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 4,
    "hbp": 3,
    "wp": 2,
    "be": 37,
    "dec": 1,
    "bs": 0,
    "whip": 1.43,
    "fip": 4.64
  },
  {
    "nombre": "Zac Lowther",
    "edad": 28,
    "w": 1,
    "l": 2,
    "pct": 0.333,
    "era": 3.55,
    "eraplus": 108,
    "gp": 8,
    "gs": 6,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 25.1,
    "h": 20,
    "r": 16,
    "er": 10,
    "hr": 1,
    "bb": 12,
    "ibb": 0,
    "so": 31,
    "hbp": 1,
    "wp": 2,
    "be": 111,
    "dec": 3,
    "bs": 0,
    "whip": 1.26,
    "fip": 2.94
  },
  {
    "nombre": "Robinson Piña",
    "edad": 26,
    "w": 2,
    "l": 1,
    "pct": 0.667,
    "era": 1.65,
    "eraplus": 232,
    "gp": 7,
    "gs": 6,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 27.1,
    "h": 23,
    "r": 6,
    "er": 5,
    "hr": 3,
    "bb": 3,
    "ibb": 0,
    "so": 27,
    "hbp": 0,
    "wp": 0,
    "be": 104,
    "dec": 3,
    "bs": 0,
    "whip": 0.95,
    "fip": 3.12
  },
  {
    "nombre": "Raúl Alcántara",
    "edad": 23,
    "w": 2,
    "l": 1,
    "pct": 0.667,
    "era": 6.40,
    "eraplus": 60,
    "gp": 7,
    "gs": 4,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 12.2,
    "h": 12,
    "r": 11,
    "er": 9,
    "hr": 1,
    "bb": 10,
    "ibb": 0,
    "so": 20,
    "hbp": 1,
    "wp": 1,
    "be": 61,
    "dec": 3,
    "bs": 0,
    "whip": 1.74,
    "fip": 3.81
  },
  {
    "nombre": "Luis Mey",
    "edad": 23,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.60,
    "eraplus": 106,
    "gp": 6,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5,
    "h": 3,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 9,
    "ibb": 0,
    "so": 5,
    "hbp": 0,
    "wp": 2,
    "be": 24,
    "dec": 0,
    "bs": 0,
    "whip": 2.40,
    "fip": 6.73
  },
  {
    "nombre": "Fernery Ozuna",
    "edad": 29,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 7.72,
    "eraplus": 49,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.1,
    "h": 4,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 1,
    "be": 14,
    "dec": 0,
    "bs": 0,
    "whip": 3.43,
    "fip": 8.48
  },
  {
    "nombre": "Ramón Santos",
    "edad": 30,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 12.00,
    "eraplus": 32,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 3,
    "h": 3,
    "r": 5,
    "er": 4,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 4,
    "hbp": 1,
    "wp": 0,
    "be": 16,
    "dec": 1,
    "bs": 0,
    "whip": 1.67,
    "fip": 3.67
  },
  {
    "nombre": "Sammy Peralta",
    "edad": 26,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 5.79,
    "eraplus": 66,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.2,
    "h": 5,
    "r": 4,
    "er": 3,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 6,
    "hbp": 1,
    "wp": 0,
    "be": 21,
    "dec": 1,
    "bs": 0,
    "whip": 1.29,
    "fip": 2.05
  },
  {
    "nombre": "Eury Ramos",
    "edad": 27,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 6,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 2,
    "ibb": 1,
    "so": 4,
    "hbp": 1,
    "wp": 0,
    "be": 15,
    "dec": 1,
    "bs": 0,
    "whip": 4.00,
    "fip": 3.83
  },
  {
    "nombre": "Eduarniel Nuñez",
    "edad": 25,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 4.91,
    "eraplus": 78,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 3.2,
    "h": 3,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 5,
    "hbp": 1,
    "wp": 0,
    "be": 16,
    "dec": 0,
    "bs": 0,
    "whip": 1.36,
    "fip": 3.06
  },
  {
    "nombre": "Thomas Hackimer",
    "edad": 30,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1.1,
    "h": 1,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 5,
    "dec": 0,
    "bs": 0,
    "whip": 1.50,
    "fip": 4.09
  },
  {
    "nombre": "Luis Reyes",
    "edad": 30,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.1,
    "h": 5,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 3,
    "hbp": 0,
    "wp": 1,
    "be": 11,
    "dec": 0,
    "bs": 0,
    "whip": 2.14,
    "fip": 0.76
  },
  {
    "nombre": "Luis Ledo",
    "edad": 29,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.86,
    "eraplus": 99,
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.1,
    "h": 1,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 3,
    "hbp": 0,
    "wp": 0,
    "be": 9,
    "dec": 0,
    "bs": 0,
    "whip": 0.86,
    "fip": 2.05
  },
  {
    "nombre": "Jeffrey Colón",
    "edad": 25,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1,
    "h": 3,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 1,
    "hbp": 1,
    "wp": 0,
    "be": 8,
    "dec": 0,
    "bs": 0,
    "whip": 4.00,
    "fip": 7.33
  },
  {
    "nombre": "José Geraldo",
    "edad": 25,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 81.08,
    "eraplus": 5,
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 0.1,
    "h": 2,
    "r": 3,
    "er": 3,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 4,
    "dec": 0,
    "bs": 0,
    "whip": 9.01,
    "fip": 12.34
  },
  {
    "nombre": "Totales",
    "edad": 29,
    "w": 30,
    "l": 20,
    "pct": 0.600,
    "era": 2.98,
    "eraplus": 0,
    "gp": 347,
    "gs": 50,
    "cg": 0,
    "sho": 0,
    "sv": 11,
    "ip": 455.1,
    "h": 401,
    "r": 189,
    "er": 151,
    "hr": 21,
    "bb": 182,
    "ibb": 10,
    "so": 451,
    "hbp": 38,
    "wp": 30,
    "be": 1951,
    "dec": 50,
    "bs": 1,
    "whip": 1.28,
    "fip": 0.00
  }

];

function formatNumber(value: number): string {
  return value === 0 ? ".000" : value.toString().replace("0.", ".");
}

export default function Page() {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredBatters = batters.filter((jugador) =>
    jugador.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredPitchers = pitchers.filter((pitcher) =>
    pitcher.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-green-800">
      {/* Encabezado con imagen difuminada */}
      <header className="relative h-64 shadow-xl">
        <div className="absolute inset-0 z-0">
          <img
            src="/Logos/Logo-estrellas.png"
            alt="Estadio de béisbol"
            className="object-cover  h-full blur-s "
          />
          <div className="absolute inset-0 bg-black/40 " />
        </div>
        
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-4xl font-bold text-white mb-4 drop-shadow-lg">
            Estadísticas de Las Estrellas Orientales
          </h1>
          <p className="text-xl text-white/90 drop-shadow-md">
          Temporada 2024 Serie Regular
          </p>
        </div>
      </header>

      {/* Contenido principal */}
      <div className="p-6 max-w-9xl mx-auto">
        {/* Barra de búsqueda */}
        <div className="mb-6">
          <input
            type="text"
            placeholder="Buscar jugador..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent shadow-sm"
          />
        </div>

        {/* Sección de Bateadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-black">Bateadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-black text-white ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">POS</th>
            <th className="border border-gray-300 p-2">JJ</th>
            <th className="border border-gray-300 p-2">APP</th>
            <th className="border border-gray-300 p-2">AB</th>
            <th className="border border-gray-300 p-2">C</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">1B</th>
            <th className="border border-gray-300 p-2">2B</th>
            <th className="border border-gray-300 p-2">3B</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">RBI</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">SB</th>
            <th className="border border-gray-300 p-2">CS</th>
            <th className="border border-gray-300 p-2">AVG</th>
            <th className="border border-gray-300 p-2">OBP</th>
            <th className="border border-gray-300 p-2">SLG</th>
            <th className="border border-gray-300 p-2">OPS</th>
            <th className="border border-gray-300 p-2">OPS+</th>
            <th className="border border-gray-300 p-2">TB</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SF</th>
            <th className="border border-gray-300 p-2">S</th>
            <th className="border border-gray-300 p-2">DP</th>
            
          </tr>
              </thead>
              <tbody>
                {filteredBatters.map((jugador, index) => (
                  <tr key={index} className={jugador.nombre === "Totales" ? "bg-green-400 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-lime-500 bg-black">{jugador.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.pos}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.jj}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ab}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.app}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.c}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b1}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b2}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b3}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.rbi}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.cs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.avg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.obp)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.slg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.ops)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.opsp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.tb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sf}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.s}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.dp}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sección de Lanzadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mt-8 mb-4 text-black">Lanzadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-black ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">W</th>
            <th className="border border-gray-300 p-2">L</th>
            <th className="border border-gray-300 p-2">PCT</th>
            <th className="border border-gray-300 p-2">ERA</th>
            <th className="border border-gray-300 p-2">ERA+</th>
            <th className="border border-gray-300 p-2">GP</th>
            <th className="border border-gray-300 p-2">GS</th>
            <th className="border border-gray-300 p-2">CG</th>
            <th className="border border-gray-300 p-2">SHO</th>
            <th className="border border-gray-300 p-2">SV</th>
            <th className="border border-gray-300 p-2">IP</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">R</th>
            <th className="border border-gray-300 p-2">ER</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">WP</th>
            <th className="border border-gray-300 p-2">BE</th>
            <th className="border border-gray-300 p-2">DEC</th>
            <th className="border border-gray-300 p-2">BS</th>
            <th className="border border-gray-300 p-2">WHIP</th>
            <th className="border border-gray-300 p-2">FIP</th>
          </tr>
              </thead>
              <tbody>
                {filteredPitchers.map((pitcher, index) => (
                  <tr key={index} className={pitcher.nombre === "Totales" ? "bg-green-400 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-lime-500 bg-black">{pitcher.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.w}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.l}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.pct.toFixed(3)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.era.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.eraplus}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.cg}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sho}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sv}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ip}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.r}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.er}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.wp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.be}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.dec}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.whip.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.fip.toFixed(2)}</td>
              </tr>
                  
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}