"use client"

import React, { useState } from 'react';

// Datos de los bateadores (mantenidos igual)
const batters = [
  {
    "nombre": "Junior Lake",
    "edad": 34,
    "pos": "LF",
    "jj": 43,
    "app": 184,
    "ab": 161,
    "c": 30,
    "h": 39,
    "b1": 30,
    "b2": 5,
    "b3": 2,
    "hr": 2,
    "rbi": 13,
    "bb": 17,
    "so": 42,
    "sb": 12,
    "cs": 3,
    "avg": 0.242,
    "obp": 0.320,
    "slg": 0.335,
    "ops": 0.655,
    "opsp": 97,
    "tb": 54,
    "hbp": 2,
    "ibb": 0,
    "sf": 1,
    "s": 3,
    "dp": 0
  },
  {
    "nombre": "Jean Segura",
    "edad": 34,
    "pos": "2B",
    "jj": 43,
    "app": 180,
    "ab": 167,
    "c": 19,
    "h": 48,
    "b1": 37,
    "b2": 9,
    "b3": 0,
    "hr": 2,
    "rbi": 23,
    "bb": 6,
    "so": 28,
    "sb": 8,
    "cs": 1,
    "avg": 0.287,
    "obp": 0.324,
    "slg": 0.377,
    "ops": 0.701,
    "opsp": 104,
    "tb": 63,
    "hbp": 4,
    "ibb": 1,
    "sf": 2,
    "s": 1,
    "dp": 4
  },
  {
    "nombre": "Erik González",
    "edad": 33,
    "pos": "SS",
    "jj": 39,
    "app": 156,
    "ab": 139,
    "c": 19,
    "h": 41,
    "b1": 37,
    "b2": 3,
    "b3": 1,
    "hr": 0,
    "rbi": 16,
    "bb": 15,
    "so": 10,
    "sb": 12,
    "cs": 2,
    "avg": 0.295,
    "obp": 0.364,
    "slg": 0.331,
    "ops": 0.695,
    "opsp": 103,
    "tb": 46,
    "hbp": 0,
    "ibb": 1,
    "sf": 0,
    "s": 2,
    "dp": 7
  },
  {
    "nombre": "José Marmolejos",
    "edad": 32,
    "pos": "1B",
    "jj": 38,
    "app": 129,
    "ab": 114,
    "c": 11,
    "h": 31,
    "b1": 21,
    "b2": 9,
    "b3": 0,
    "hr": 1,
    "rbi": 15,
    "bb": 11,
    "so": 24,
    "sb": 0,
    "cs": 1,
    "avg": 0.272,
    "obp": 0.326,
    "slg": 0.377,
    "ops": 0.703,
    "opsp": 104,
    "tb": 43,
    "hbp": 0,
    "ibb": 0,
    "sf": 4,
    "s": 0,
    "dp": 3
  },
  {
    "nombre": "Yamaico Navarro",
    "edad": 37,
    "pos": "1B",
    "jj": 36,
    "app": 139,
    "ab": 117,
    "c": 11,
    "h": 27,
    "b1": 19,
    "b2": 6,
    "b3": 0,
    "hr": 2,
    "rbi": 12,
    "bb": 20,
    "so": 24,
    "sb": 0,
    "cs": 1,
    "avg": 0.231,
    "obp": 0.353,
    "slg": 0.333,
    "ops": 0.686,
    "opsp": 101,
    "tb": 39,
    "hbp": 2,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Jonathan Guzmán",
    "edad": 25,
    "pos": "3B",
    "jj": 34,
    "app": 64,
    "ab": 61,
    "c": 7,
    "h": 22,
    "b1": 15,
    "b2": 7,
    "b3": 0,
    "hr": 0,
    "rbi": 4,
    "bb": 3,
    "so": 12,
    "sb": 4,
    "cs": 0,
    "avg": 0.361,
    "obp": 0.391,
    "slg": 0.475,
    "ops": 0.866,
    "opsp": 128,
    "tb": 29,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 2
  },
  {
    "nombre": "Sandber Pimentel",
    "edad": 30,
    "pos": "DH",
    "jj": 34,
    "app": 83,
    "ab": 71,
    "c": 7,
    "h": 18,
    "b1": 9,
    "b2": 6,
    "b3": 0,
    "hr": 3,
    "rbi": 13,
    "bb": 12,
    "so": 22,
    "sb": 0,
    "cs": 0,
    "avg": 0.254,
    "obp": 0.361,
    "slg": 0.465,
    "ops": 0.826,
    "opsp": 122,
    "tb": 33,
    "hbp": 0,
    "ibb": 1,
    "sf": 0,
    "s": 0,
    "dp": 3
  },
  {
    "nombre": "Luis De Los Santos",
    "edad": 26,
    "pos": "3B",
    "jj": 29,
    "app": 81,
    "ab": 75,
    "c": 8,
    "h": 15,
    "b1": 9,
    "b2": 5,
    "b3": 0,
    "hr": 1,
    "rbi": 9,
    "bb": 6,
    "so": 23,
    "sb": 1,
    "cs": 1,
    "avg": 0.200,
    "obp": 0.259,
    "slg": 0.307,
    "ops": 0.566,
    "opsp": 84,
    "tb": 23,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 3
  },
  {
    "nombre": "Steward Berroa",
    "edad": 25,
    "pos": "CF",
    "jj": 28,
    "app": 71,
    "ab": 53,
    "c": 15,
    "h": 12,
    "b1": 12,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 15,
    "so": 11,
    "sb": 12,
    "cs": 1,
    "avg": 0.226,
    "obp": 0.397,
    "slg": 0.226,
    "ops": 0.623,
    "opsp": 92,
    "tb": 12,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 3,
    "dp": 1
  },
  {
    "nombre": "Hector Rodriguez",
    "edad": 20,
    "pos": "RF",
    "jj": 24,
    "app": 96,
    "ab": 91,
    "c": 10,
    "h": 23,
    "b1": 19,
    "b2": 3,
    "b3": 0,
    "hr": 1,
    "rbi": 16,
    "bb": 2,
    "so": 15,
    "sb": 2,
    "cs": 1,
    "avg": 0.253,
    "obp": 0.263,
    "slg": 0.319,
    "ops": 0.582,
    "opsp": 86,
    "tb": 29,
    "hbp": 0,
    "ibb": 0,
    "sf": 2,
    "s": 1,
    "dp": 1
  },
  {
    "nombre": "Pedro Severino",
    "edad": 31,
    "pos": "C",
    "jj": 23,
    "app": 64,
    "ab": 54,
    "c": 5,
    "h": 13,
    "b1": 9,
    "b2": 4,
    "b3": 0,
    "hr": 0,
    "rbi": 6,
    "bb": 7,
    "so": 11,
    "sb": 1,
    "cs": 1,
    "avg": 0.241,
    "obp": 0.317,
    "slg": 0.315,
    "ops": 0.632,
    "opsp": 93,
    "tb": 17,
    "hbp": 0,
    "ibb": 0,
    "sf": 2,
    "s": 1,
    "dp": 1
  },
  {
    "nombre": "Francisco Urbáez",
    "edad": 27,
    "pos": "PH",
    "jj": 22,
    "app": 28,
    "ab": 22,
    "c": 3,
    "h": 4,
    "b1": 4,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 5,
    "so": 6,
    "sb": 0,
    "cs": 0,
    "avg": 0.182,
    "obp": 0.357,
    "slg": 0.182,
    "ops": 0.539,
    "opsp": 80,
    "tb": 4,
    "hbp": 1,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Franchy Cordero",
    "edad": 30,
    "pos": "DH",
    "jj": 21,
    "app": 77,
    "ab": 61,
    "c": 12,
    "h": 17,
    "b1": 8,
    "b2": 6,
    "b3": 1,
    "hr": 2,
    "rbi": 12,
    "bb": 16,
    "so": 20,
    "sb": 1,
    "cs": 1,
    "avg": 0.279,
    "obp": 0.429,
    "slg": 0.508,
    "ops": 0.937,
    "opsp": 138,
    "tb": 31,
    "hbp": 0,
    "ibb": 2,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Abiatal Avelino",
    "edad": 29,
    "pos": "3B",
    "jj": 20,
    "app": 24,
    "ab": 20,
    "c": 6,
    "h": 6,
    "b1": 5,
    "b2": 0,
    "b3": 0,
    "hr": 1,
    "rbi": 5,
    "bb": 1,
    "so": 4,
    "sb": 0,
    "cs": 0,
    "avg": 0.300,
    "obp": 0.375,
    "slg": 0.450,
    "ops": 0.825,
    "opsp": 122,
    "tb": 9,
    "hbp": 2,
    "ibb": 0,
    "sf": 1,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Ramón Laureano",
    "edad": 30,
    "pos": "CF",
    "jj": 17,
    "app": 72,
    "ab": 54,
    "c": 10,
    "h": 14,
    "b1": 9,
    "b2": 3,
    "b3": 1,
    "hr": 1,
    "rbi": 9,
    "bb": 12,
    "so": 17,
    "sb": 3,
    "cs": 1,
    "avg": 0.259,
    "obp": 0.417,
    "slg": 0.407,
    "ops": 0.824,
    "opsp": 122,
    "tb": 22,
    "hbp": 4,
    "ibb": 0,
    "sf": 2,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Gary Sánchez",
    "edad": 32,
    "pos": "C",
    "jj": 13,
    "app": 47,
    "ab": 36,
    "c": 5,
    "h": 5,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 4,
    "rbi": 8,
    "bb": 8,
    "so": 12,
    "sb": 0,
    "cs": 0,
    "avg": 0.139,
    "obp": 0.319,
    "slg": 0.472,
    "ops": 0.791,
    "opsp": 117,
    "tb": 17,
    "hbp": 2,
    "ibb": 2,
    "sf": 1,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Carlos Jimenez",
    "edad": 21,
    "pos": "RF",
    "jj": 13,
    "app": 16,
    "ab": 13,
    "c": 2,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 3,
    "so": 3,
    "sb": 0,
    "cs": 1,
    "avg": 0.077,
    "obp": 0.250,
    "slg": 0.077,
    "ops": 0.327,
    "opsp": 48,
    "tb": 1,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Matt Koperniak",
    "edad": 26,
    "pos": "RF",
    "jj": 13,
    "app": 49,
    "ab": 43,
    "c": 3,
    "h": 9,
    "b1": 8,
    "b2": 0,
    "b3": 1,
    "hr": 0,
    "rbi": 4,
    "bb": 5,
    "so": 14,
    "sb": 4,
    "cs": 0,
    "avg": 0.209,
    "obp": 0.306,
    "slg": 0.256,
    "ops": 0.562,
    "opsp": 83,
    "tb": 11,
    "hbp": 1,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Reese McGuire",
    "edad": 29,
    "pos": "C",
    "jj": 11,
    "app": 34,
    "ab": 29,
    "c": 5,
    "h": 10,
    "b1": 10,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 2,
    "so": 6,
    "sb": 1,
    "cs": 0,
    "avg": 0.345,
    "obp": 0.441,
    "slg": 0.345,
    "ops": 0.786,
    "opsp": 116,
    "tb": 10,
    "hbp": 3,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 2
  },
  {
    "nombre": "Martin Maldonado",
    "edad": 38,
    "pos": "C",
    "jj": 10,
    "app": 38,
    "ab": 35,
    "c": 3,
    "h": 4,
    "b1": 1,
    "b2": 1,
    "b3": 0,
    "hr": 2,
    "rbi": 3,
    "bb": 3,
    "so": 17,
    "sb": 0,
    "cs": 0,
    "avg": 0.114,
    "obp": 0.184,
    "slg": 0.314,
    "ops": 0.498,
    "opsp": 74,
    "tb": 11,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 2
  },
  {
    "nombre": "Franmil Reyes",
    "edad": 29,
    "pos": "DH",
    "jj": 10,
    "app": 39,
    "ab": 32,
    "c": 6,
    "h": 8,
    "b1": 5,
    "b2": 1,
    "b3": 0,
    "hr": 2,
    "rbi": 4,
    "bb": 7,
    "so": 9,
    "sb": 1,
    "cs": 0,
    "avg": 0.250,
    "obp": 0.385,
    "slg": 0.469,
    "ops": 0.854,
    "opsp": 126,
    "tb": 15,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Junior Caminero",
    "edad": 21,
    "pos": "3B",
    "jj": 9,
    "app": 35,
    "ab": 33,
    "c": 8,
    "h": 14,
    "b1": 10,
    "b2": 4,
    "b3": 0,
    "hr": 0,
    "rbi": 4,
    "bb": 1,
    "so": 1,
    "sb": 1,
    "cs": 2,
    "avg": 0.424,
    "obp": 0.457,
    "slg": 0.545,
    "ops": 1.002,
    "opsp": 148,
    "tb": 18,
    "hbp": 1,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Jimmy Paredes",
    "edad": 36,
    "pos": "PH",
    "jj": 8,
    "app": 13,
    "ab": 10,
    "c": 2,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 3,
    "so": 5,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.231,
    "slg": 0.000,
    "ops": 0.231,
    "opsp": 34,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Orlando Calixte",
    "edad": 32,
    "pos": "1B",
    "jj": 8,
    "app": 28,
    "ab": 27,
    "c": 4,
    "h": 5,
    "b1": 2,
    "b2": 2,
    "b3": 1,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 6,
    "sb": 2,
    "cs": 0,
    "avg": 0.185,
    "obp": 0.214,
    "slg": 0.333,
    "ops": 0.547,
    "opsp": 81,
    "tb": 9,
    "hbp": 1,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 2
  },
  {
    "nombre": "Tommy Pham",
    "edad": 36,
    "pos": "RF",
    "jj": 8,
    "app": 28,
    "ab": 24,
    "c": 2,
    "h": 3,
    "b1": 2,
    "b2": 1,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 2,
    "so": 5,
    "sb": 0,
    "cs": 0,
    "avg": 0.125,
    "obp": 0.179,
    "slg": 0.167,
    "ops": 0.346,
    "opsp": 51,
    "tb": 4,
    "hbp": 0,
    "ibb": 0,
    "sf": 2,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Freuddy Batista",
    "edad": 25,
    "pos": "C",
    "jj": 7,
    "app": 7,
    "ab": 6,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 1,
    "so": 2,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.143,
    "slg": 0.000,
    "ops": 0.143,
    "opsp": 21,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Ricardo Céspedes",
    "edad": 27,
    "pos": "PR",
    "jj": 7,
    "app": 3,
    "ab": 3,
    "c": 1,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 1,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Warming Bernabel",
    "edad": 22,
    "pos": "3B",
    "jj": 7,
    "app": 20,
    "ab": 20,
    "c": 0,
    "h": 3,
    "b1": 2,
    "b2": 1,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 0,
    "so": 1,
    "sb": 0,
    "cs": 0,
    "avg": 0.150,
    "obp": 0.150,
    "slg": 0.200,
    "ops": 0.350,
    "opsp": 52,
    "tb": 4,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 1
  },
  {
    "nombre": "Bryan González",
    "edad": 23,
    "pos": "PH",
    "jj": 6,
    "app": 9,
    "ab": 9,
    "c": 1,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 6,
    "sb": 0,
    "cs": 0,
    "avg": 0.111,
    "obp": 0.111,
    "slg": 0.111,
    "ops": 0.222,
    "opsp": 33,
    "tb": 1,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
  },
  {
    "nombre": "Zoilo Almonte",
    "edad": 35,
    "pos": "DH",
    "jj": 5,
    "app": 21,
    "ab": 18,
    "c": 1,
    "h": 7,
    "b1": 4,
    "b2": 3,
    "b3": 0,
    "hr": 0,
    "rbi": 2,
    "bb": 1,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 0.389,
    "obp": 0.476,
    "slg": 0.556,
    "ops": 1.032,
    "opsp": 152,
    "tb": 10,
    "hbp": 0,
    "ibb": 1,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "Sócrates Brito",
    "edad": 32,
    "pos": "CF",
    "jj": 4,
    "app": 20,
    "ab": 18,
    "c": 3,
    "h": 6,
    "b1": 4,
    "b2": 1,
    "b3": 1,
    "hr": 0,
    "rbi": 1,
    "bb": 2,
    "so": 3,
    "sb": 0,
    "cs": 0,
    "avg": 0.333,
    "obp": 0.400,
    "slg": 0.500,
    "ops": 0.900,
    "opsp": 133,
    "tb": 9,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "Anderson Féliz",
    "edad": 32,
    "pos": "PH",
    "jj": 4,
    "app": 4,
    "ab": 4,
    "c": 0,
    "h": 1,
    "b1": 1,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 2,
    "sb": 0,
    "cs": 1,
    "avg": 0.250,
    "obp": 0.250,
    "slg": 0.250,
    "ops": 0.500,
    "opsp": 74,
    "tb": 1,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "José Briceño",
    "edad": 32,
    "pos": "C",
    "jj": 4,
    "app": 7,
    "ab": 7,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 1,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "Darlin Moquete",
    "edad": 25,
    "pos": "PR",
    "jj": 3,
    "app": 1,
    "ab": 1,
    "c": 1,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "Randy Florentino",
    "edad": 24,
    "pos": "C",
    "jj": 2,
    "app": 3,
    "ab": 3,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "Joseph Rosa",
    "edad": 27,
    "pos": "2B",
    "jj": 1,
    "app": 3,
    "ab": 2,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 1,
    "so": 0,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.333,
    "slg": 0.000,
    "ops": 0.333,
    "opsp": 49,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},
{
    "nombre": "Johan Mieses",
    "edad": 29,
    "pos": "PH",
    "jj": 1,
    "app": 1,
    "ab": 1,
    "c": 0,
    "h": 0,
    "b1": 0,
    "b2": 0,
    "b3": 0,
    "hr": 0,
    "rbi": 0,
    "bb": 0,
    "so": 1,
    "sb": 0,
    "cs": 0,
    "avg": 0.000,
    "obp": 0.000,
    "slg": 0.000,
    "ops": 0.000,
    "opsp": 0,
    "tb": 0,
    "hbp": 0,
    "ibb": 0,
    "sf": 0,
    "s": 0,
    "dp": 0
},{
    "nombre": "Totales",
    "edad": 29,
    "pos": "",
    "jj": 605,
    "app": 1874,
    "ab": 1634,
    "c": 220,
    "h": 407,
    "b1": 295,
    "b2": 80,
    "b3": 8,
    "hr": 24,
    "rbi": 192,
    "bb": 189,
    "so": 367,
    "sb": 68,
    "cs": 18,
    "avg": 0.249,
    "obp": 0.332,
    "slg": 0.352,
    "ops": 0.684,
    "opsp": 0,
    "tb": 575,
    "hbp": 23,
    "ibb": 8,
    "sf": 17,
    "s": 11,
    "dp": 36
}
];

// Datos de los lanzadores (mantenidos igual)
const pitchers = [
  {
    "nombre": "Henry Sosa",
    "edad": 39,
    "w": 3,
    "l": 1,
    "pct": 0.750,
    "era": 4.22,
    "eraplus": 91,
    "gp": 21,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 21.1,
    "h": 24,
    "r": 11,
    "er": 10,
    "hr": 3,
    "bb": 8,
    "ibb": 3,
    "so": 19,
    "hbp": 0,
    "wp": 1,
    "be": 91,
    "dec": 4,
    "bs": 0,
    "whip": 1.50,
    "fip": 4.51
  },
  {
    "nombre": "Ivan Armstrong",
    "edad": 24,
    "w": 2,
    "l": 0,
    "pct": 1.000,
    "era": 2.25,
    "eraplus": 170,
    "gp": 18,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 16,
    "h": 16,
    "r": 5,
    "er": 4,
    "hr": 0,
    "bb": 8,
    "ibb": 1,
    "so": 13,
    "hbp": 1,
    "wp": 1,
    "be": 73,
    "dec": 2,
    "bs": 0,
    "whip": 1.50,
    "fip": 3.40
  },
  {
    "nombre": "Sauryn Lao",
    "edad": 25,
    "w": 2,
    "l": 2,
    "pct": 0.500,
    "era": 3.94,
    "eraplus": 97,
    "gp": 16,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 1,
    "ip": 16,
    "h": 15,
    "r": 8,
    "er": 7,
    "hr": 1,
    "bb": 5,
    "ibb": 1,
    "so": 7,
    "hbp": 0,
    "wp": 1,
    "be": 64,
    "dec": 4,
    "bs": 0,
    "whip": 1.25,
    "fip": 4.21
  },
  {
    "nombre": "Rodolfo Martínez",
    "edad": 30,
    "w": 0,
    "l": 2,
    "pct": 0.000,
    "era": 5.23,
    "eraplus": 73,
    "gp": 14,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 1,
    "ip": 10.1,
    "h": 9,
    "r": 7,
    "er": 6,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 8,
    "hbp": 0,
    "wp": 0,
    "be": 44,
    "dec": 2,
    "bs": 0,
    "whip": 1.26,
    "fip": 2.95
  },
  {
    "nombre": "Yohan Ramírez",
    "edad": 29,
    "w": 2,
    "l": 1,
    "pct": 0.667,
    "era": 3.29,
    "eraplus": 116,
    "gp": 14,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 2,
    "ip": 13.2,
    "h": 11,
    "r": 7,
    "er": 5,
    "hr": 1,
    "bb": 5,
    "ibb": 0,
    "so": 17,
    "hbp": 1,
    "wp": 3,
    "be": 58,
    "dec": 3,
    "bs": 0,
    "whip": 1.17,
    "fip": 3.12
  },
  {
    "nombre": "Alex Colomé",
    "edad": 36,
    "w": 1,
    "l": 1,
    "pct": 0.500,
    "era": 6.28,
    "eraplus": 61,
    "gp": 13,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.1,
    "h": 16,
    "r": 12,
    "er": 10,
    "hr": 2,
    "bb": 8,
    "ibb": 2,
    "so": 10,
    "hbp": 0,
    "wp": 2,
    "be": 68,
    "dec": 2,
    "bs": 0,
    "whip": 1.67,
    "fip": 5.43
  },
  {
    "nombre": "Cameron Gann",
    "edad": 32,
    "w": 2,
    "l": 1,
    "pct": 0.667,
    "era": 3.18,
    "eraplus": 120,
    "gp": 12,
    "gs": 2,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 22.2,
    "h": 18,
    "r": 11,
    "er": 8,
    "hr": 3,
    "bb": 11,
    "ibb": 0,
    "so": 19,
    "hbp": 0,
    "wp": 0,
    "be": 96,
    "dec": 3,
    "bs": 0,
    "whip": 1.28,
    "fip": 4.83
  },
  {
    "nombre": "Brian Moran",
    "edad": 36,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 11,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 1,
    "ip": 7,
    "h": 11,
    "r": 7,
    "er": 7,
    "hr": 1,
    "bb": 2,
    "ibb": 0,
    "so": 10,
    "hbp": 2,
    "wp": 0,
    "be": 35,
    "dec": 0,
    "bs": 0,
    "whip": 1.86,
    "fip": 4.05
  },
  {
    "nombre": "Trevor Kelley",
    "edad": 32,
    "w": 2,
    "l": 0,
    "pct": 1.000,
    "era": 2.63,
    "eraplus": 145,
    "gp": 11,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 2,
    "ip": 13.2,
    "h": 11,
    "r": 4,
    "er": 4,
    "hr": 2,
    "bb": 2,
    "ibb": 0,
    "so": 15,
    "hbp": 0,
    "wp": 0,
    "be": 53,
    "dec": 2,
    "bs": 0,
    "whip": 0.95,
    "fip": 3.48
  },
  {
    "nombre": "Jimmy Cordero",
    "edad": 33,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 2.45,
    "eraplus": 156,
    "gp": 10,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 1,
    "ip": 11,
    "h": 7,
    "r": 4,
    "er": 3,
    "hr": 1,
    "bb": 1,
    "ibb": 0,
    "so": 10,
    "hbp": 0,
    "wp": 1,
    "be": 40,
    "dec": 0,
    "bs": 0,
    "whip": 0.73,
    "fip": 2.97
  },
  {
    "nombre": "Eduardo Rivera",
    "edad": 32,
    "w": 1,
    "l": 5,
    "pct": 0.167,
    "era": 4.63,
    "eraplus": 83,
    "gp": 10,
    "gs": 9,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 35,
    "h": 30,
    "r": 21,
    "er": 18,
    "hr": 5,
    "bb": 18,
    "ibb": 0,
    "so": 25,
    "hbp": 3,
    "wp": 3,
    "be": 155,
    "dec": 6,
    "bs": 0,
    "whip": 1.37,
    "fip": 5.56
  },
  {
    "nombre": "Yorlin Calderon",
    "edad": 23,
    "w": 1,
    "l": 1,
    "pct": 0.500,
    "era": 3.72,
    "eraplus": 103,
    "gp": 10,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 9.2,
    "h": 10,
    "r": 5,
    "er": 4,
    "hr": 0,
    "bb": 5,
    "ibb": 0,
    "so": 11,
    "hbp": 0,
    "wp": 1,
    "be": 45,
    "dec": 2,
    "bs": 0,
    "whip": 1.55,
    "fip": 2.61
  },
  {
    "nombre": "Jeurys Familia",
    "edad": 35,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 4.32,
    "eraplus": 88,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 8.1,
    "h": 8,
    "r": 4,
    "er": 4,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 5,
    "hbp": 0,
    "wp": 0,
    "be": 32,
    "dec": 1,
    "bs": 0,
    "whip": 1.08,
    "fip": 2.50
  },
  {
    "nombre": "Phillips Valdez",
    "edad": 33,
    "w": 1,
    "l": 2,
    "pct": 0.333,
    "era": 4.46,
    "eraplus": 86,
    "gp": 9,
    "gs": 7,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 34.1,
    "h": 31,
    "r": 22,
    "er": 17,
    "hr": 1,
    "bb": 7,
    "ibb": 1,
    "so": 24,
    "hbp": 4,
    "wp": 1,
    "be": 140,
    "dec": 3,
    "bs": 0,
    "whip": 1.11,
    "fip": 3.28
  },
  {
    "nombre": "Keury Mella",
    "edad": 31,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.38,
    "eraplus": 113,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5.1,
    "h": 7,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 2,
    "hbp": 0,
    "wp": 0,
    "be": 27,
    "dec": 0,
    "bs": 0,
    "whip": 2.06,
    "fip": 4.84
  },
  {
    "nombre": "Enrique Burgos",
    "edad": 34,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 5.40,
    "eraplus": 71,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 8.1,
    "h": 8,
    "r": 5,
    "er": 5,
    "hr": 1,
    "bb": 3,
    "ibb": 0,
    "so": 6,
    "hbp": 0,
    "wp": 0,
    "be": 37,
    "dec": 0,
    "bs": 0,
    "whip": 1.32,
    "fip": 4.54
  },
  {
    "nombre": "Carlos Teller",
    "edad": 38,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 6.00,
    "eraplus": 64,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 9,
    "h": 9,
    "r": 6,
    "er": 6,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 7,
    "hbp": 0,
    "wp": 1,
    "be": 36,
    "dec": 0,
    "bs": 0,
    "whip": 1.44,
    "fip": 3.11
  },
  {
    "nombre": "Zac Rosscup",
    "edad": 36,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 6.75,
    "eraplus": 57,
    "gp": 8,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 6.2,
    "h": 9,
    "r": 5,
    "er": 5,
    "hr": 1,
    "bb": 5,
    "ibb": 0,
    "so": 4,
    "hbp": 2,
    "wp": 0,
    "be": 34,
    "dec": 0,
    "bs": 0,
    "whip": 2.10,
    "fip": 7.23
  },
  {
    "nombre": "Jasseel De La Cruz",
    "edad": 27,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 7,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5,
    "h": 5,
    "r": 5,
    "er": 5,
    "hr": 0,
    "bb": 6,
    "ibb": 0,
    "so": 4,
    "hbp": 1,
    "wp": 0,
    "be": 26,
    "dec": 0,
    "bs": 0,
    "whip": 2.20,
    "fip": 5.94
  },
  {
    "nombre": "Domingo Acevedo",
    "edad": 30,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 2.25,
    "eraplus": 170,
    "gp": 6,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 8,
    "h": 9,
    "r": 4,
    "er": 2,
    "hr": 0,
    "bb": 6,
    "ibb": 1,
    "so": 6,
    "hbp": 1,
    "wp": 1,
    "be": 38,
    "dec": 1,
    "bs": 0,
    "whip": 1.88,
    "fip": 4.46
  },
  {
    "nombre": "Diógenes Almengó",
    "edad": 29,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.00,
    "eraplus": 127,
    "gp": 6,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 6,
    "h": 6,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 4,
    "hbp": 0,
    "wp": 0,
    "be": 24,
    "dec": 0,
    "bs": 0,
    "whip": 1.17,
    "fip": 2.50
  },
  {
    "nombre": "Ralph Garza",
    "edad": 30,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 4.76,
    "eraplus": 80,
    "gp": 6,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5.2,
    "h": 11,
    "r": 5,
    "er": 3,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 3,
    "hbp": 2,
    "wp": 0,
    "be": 31,
    "dec": 0,
    "bs": 0,
    "whip": 2.12,
    "fip": 3.86
  },
  {
    "nombre": "Jesús Liranzo",
    "edad": 29,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 1.80,
    "eraplus": 212,
    "gp": 5,
    "gs": 2,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5,
    "h": 4,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 8,
    "hbp": 1,
    "wp": 1,
    "be": 22,
    "dec": 1,
    "bs": 0,
    "whip": 1.00,
    "fip": 1.33
  },
  {
    "nombre": "Gabriel Ynoa",
    "edad": 31,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 2.45,
    "eraplus": 156,
    "gp": 5,
    "gs": 4,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.2,
    "h": 16,
    "r": 4,
    "er": 4,
    "hr": 1,
    "bb": 3,
    "ibb": 0,
    "so": 7,
    "hbp": 0,
    "wp": 0,
    "be": 59,
    "dec": 1,
    "bs": 0,
    "whip": 1.30,
    "fip": 3.88
  },
  {
    "nombre": "Emmanuel Ramírez",
    "edad": 30,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 5,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5.1,
    "h": 2,
    "r": 2,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 7,
    "hbp": 0,
    "wp": 2,
    "be": 20,
    "dec": 0,
    "bs": 0,
    "whip": 0.56,
    "fip": 1.27
  },
  {
    "nombre": "Luke Westphal",
    "edad": 35,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 6.75,
    "eraplus": 57,
    "gp": 5,
    "gs": 3,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 12,
    "h": 15,
    "r": 9,
    "er": 9,
    "hr": 2,
    "bb": 9,
    "ibb": 1,
    "so": 11,
    "hbp": 0,
    "wp": 2,
    "be": 59,
    "dec": 0,
    "bs": 0,
    "whip": 2.00,
    "fip": 5.92
  },
  {
    "nombre": "Víctor Santos",
    "edad": 24,
    "w": 2,
    "l": 2,
    "pct": 0.500,
    "era": 1.54,
    "eraplus": 248,
    "gp": 5,
    "gs": 5,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 23.1,
    "h": 13,
    "r": 4,
    "er": 4,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 21,
    "hbp": 2,
    "wp": 0,
    "be": 86,
    "dec": 4,
    "bs": 0,
    "whip": 0.73,
    "fip": 2.31
  }, {
    "nombre": "Odalvi Javier",
    "edad": 28,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 9.64,
    "eraplus": 40,
    "gp": 5,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.2,
    "h": 9,
    "r": 9,
    "er": 5,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 1,
    "hbp": 1,
    "wp": 0,
    "be": 27,
    "dec": 1,
    "bs": 0,
    "whip": 2.57,
    "fip": 5.48
  },
  {
    "nombre": "Elián Leyva",
    "edad": 35,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 6.75,
    "eraplus": 57,
    "gp": 5,
    "gs": 5,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.2,
    "h": 18,
    "r": 14,
    "er": 11,
    "hr": 4,
    "bb": 2,
    "ibb": 0,
    "so": 9,
    "hbp": 0,
    "wp": 0,
    "be": 64,
    "dec": 1,
    "bs": 0,
    "whip": 1.36,
    "fip": 6.06
  },
  {
    "nombre": "Cesilio Pimentel",
    "edad": 32,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 6.75,
    "eraplus": 57,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.2,
    "h": 7,
    "r": 2,
    "er": 2,
    "hr": 1,
    "bb": 2,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 16,
    "dec": 0,
    "bs": 0,
    "whip": 3.38,
    "fip": 10.46
  },
  {
    "nombre": "Robinson Martínez",
    "edad": 26,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 2.08,
    "eraplus": 184,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 2,
    "ip": 4.1,
    "h": 2,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 4,
    "hbp": 0,
    "wp": 0,
    "be": 15,
    "dec": 0,
    "bs": 0,
    "whip": 0.46,
    "fip": 1.49
  },
  {
    "nombre": "Rafael Montero",
    "edad": 34,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 6.00,
    "eraplus": 64,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 3,
    "h": 2,
    "r": 2,
    "er": 2,
    "hr": 1,
    "bb": 1,
    "ibb": 0,
    "so": 3,
    "hbp": 0,
    "wp": 0,
    "be": 12,
    "dec": 1,
    "bs": 0,
    "whip": 1.00,
    "fip": 6.67
  },
  {
    "nombre": "Michael Ynoa",
    "edad": 33,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 5.40,
    "eraplus": 71,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 3.1,
    "h": 4,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 2,
    "hbp": 1,
    "wp": 0,
    "be": 15,
    "dec": 0,
    "bs": 0,
    "whip": 1.50,
    "fip": 3.94
  },
  {
    "nombre": "Ariel Miranda",
    "edad": 36,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 2.57,
    "eraplus": 149,
    "gp": 3,
    "gs": 3,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 7,
    "h": 7,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 6,
    "ibb": 0,
    "so": 3,
    "hbp": 1,
    "wp": 0,
    "be": 35,
    "dec": 1,
    "bs": 0,
    "whip": 1.86,
    "fip": 5.48
  },
  {
    "nombre": "Connor Thomas",
    "edad": 26,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 5.23,
    "eraplus": 73,
    "gp": 3,
    "gs": 3,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 10.1,
    "h": 9,
    "r": 7,
    "er": 6,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 10,
    "hbp": 0,
    "wp": 0,
    "be": 42,
    "dec": 1,
    "bs": 0,
    "whip": 1.16,
    "fip": 2.27
  },
  {
    "nombre": "Brayan Castillo",
    "edad": 24,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.2,
    "h": 0,
    "r": 1,
    "er": 0,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 2,
    "hbp": 0,
    "wp": 0,
    "be": 10,
    "dec": 0,
    "bs": 0,
    "whip": 0.75,
    "fip": 4.08
  },
  {
    "nombre": "Nick Gardewine",
    "edad": 31,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 3.86,
    "eraplus": 99,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.1,
    "h": 3,
    "r": 2,
    "er": 1,
    "hr": 1,
    "bb": 1,
    "ibb": 1,
    "so": 2,
    "hbp": 0,
    "wp": 0,
    "be": 11,
    "dec": 1,
    "bs": 0,
    "whip": 1.71,
    "fip": 8.48
  },
  {
    "nombre": "Dario Agrazal",
    "edad": 30,
    "w": 1,
    "l": 1,
    "pct": 0.500,
    "era": 4.15,
    "eraplus": 92,
    "gp": 3,
    "gs": 3,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 13,
    "h": 15,
    "r": 7,
    "er": 6,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 7,
    "hbp": 0,
    "wp": 0,
    "be": 56,
    "dec": 2,
    "bs": 0,
    "whip": 1.46,
    "fip": 3.18
  },
  {
    "nombre": "Johnny Cueto",
    "edad": 38,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 1.00,
    "eraplus": 382,
    "gp": 2,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 9,
    "h": 9,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 6,
    "hbp": 0,
    "wp": 0,
    "be": 35,
    "dec": 0,
    "bs": 0,
    "whip": 1.11,
    "fip": 2.33
  },
  {
    "nombre": "Robert Corniel",
    "edad": 29,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1,
    "h": 1,
    "r": 2,
    "er": 0,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 7,
    "dec": 0,
    "bs": 0,
    "whip": 3.00,
    "fip": 7.33
  },
  {
    "nombre": "Aneurys Zabala",
    "edad": 28,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 1,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 1,
    "be": 7,
    "dec": 0,
    "bs": 0,
    "whip": 0.50,
    "fip": 3.33
  },
  {
    "nombre": "Juan Méndez",
    "edad": 26,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1,
    "h": 1,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 5,
    "dec": 0,
    "bs": 0,
    "whip": 1.00,
    "fip": 1.33
  },
  {
    "nombre": "Joel Valdez",
    "edad": 24,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1,
    "h": 1,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 0,
    "hbp": 1,
    "wp": 0,
    "be": 5,
    "dec": 0,
    "bs": 0,
    "whip": 1.00,
    "fip": 6.33
  },
  {
    "nombre": "Samuel Vázquez",
    "edad": 25,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 0.6,
    "h": 0,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 4,
    "dec": 0,
    "bs": 0,
    "whip": 4.50,
    "fip": 16.83
  },{
    "nombre": "Augusto Calderon",
    "edad": 24,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1,
    "h": 2,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 7,
    "dec": 0,
    "bs": 0,
    "whip": 4.00,
    "fip": 9.34
  },
  {
    "nombre": "Joey Matulovich",
    "edad": 27,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 1,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 4,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 1,
    "hbp": 1,
    "wp": 0,
    "be": 11,
    "dec": 0,
    "bs": 0,
    "whip": 2.00,
    "fip": 3.83
  },
  {
    "nombre": "Totales",
    "edad": 30,
    "w": 24,
    "l": 25,
    "pct": 0.490,
    "era": 4.09,
    "eraplus": 0,
    "gp": 313,
    "gs": 49,
    "cg": 0,
    "sho": 0,
    "sv": 10,
    "ip": 433.1,
    "h": 426,
    "r": 238,
    "er": 197,
    "hr": 32,
    "bb": 166,
    "ibb": 11,
    "so": 335,
    "hbp": 25,
    "wp": 23,
    "be": 1877,
    "dec": 49,
    "bs": 0,
    "whip": 1.37,
    "fip": 0.00
  }

];

function formatNumber(value: number): string {
  return value === 0 ? ".000" : value.toString().replace("0.", ".");
}

export default function Page() {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredBatters = batters.filter((jugador) =>
    jugador.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredPitchers = pitchers.filter((pitcher) =>
    pitcher.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-red-500">
      {/* Encabezado con imagen difuminada */}
      <header className="relative h-40 shadow-xl">
        <div className="absolute inset-0 z-0">
          <img
            src="/Logos/escogido.png"
            alt="Estadio de béisbol"
            className="object-cover  h-full blur-s "
          />
          <div className="absolute inset-0 bg-black/30" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-4xl font-bold text-white mb-4 drop-shadow-lg">
            Estadísticas de Los Leones del Escogido
          </h1>
          <p className="text-xl text-white/90 drop-shadow-md">
          Temporada 2024 Serie Regular
          </p>
        </div>
      </header>

      {/* Contenido principal */}
      <div className="p-6 max-w-9xl mx-auto">
        {/* Barra de búsqueda */}
        <div className="mb-6">
          <input
            type="text"
            placeholder="Buscar jugador..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-900 focus:border-transparent shadow-sm"
          />
        </div>

        {/* Sección de Bateadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-black">Bateadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-black text-white ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">POS</th>
            <th className="border border-gray-300 p-2">JJ</th>
            <th className="border border-gray-300 p-2">APP</th>
            <th className="border border-gray-300 p-2">AB</th>
            <th className="border border-gray-300 p-2">C</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">1B</th>
            <th className="border border-gray-300 p-2">2B</th>
            <th className="border border-gray-300 p-2">3B</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">RBI</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">SB</th>
            <th className="border border-gray-300 p-2">CS</th>
            <th className="border border-gray-300 p-2">AVG</th>
            <th className="border border-gray-300 p-2">OBP</th>
            <th className="border border-gray-300 p-2">SLG</th>
            <th className="border border-gray-300 p-2">OPS</th>
            <th className="border border-gray-300 p-2">OPS+</th>
            <th className="border border-gray-300 p-2">TB</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SF</th>
            <th className="border border-gray-300 p-2">S</th>
            <th className="border border-gray-300 p-2">DP</th>
            
          </tr>
              </thead>
              <tbody>
                {filteredBatters.map((jugador, index) => (
                  <tr key={index} className={jugador.nombre === "Totales" ? "bg-red-400 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-red-500 bg-black">{jugador.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.pos}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.jj}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ab}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.app}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.c}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b1}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b2}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b3}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.rbi}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.cs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.avg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.obp)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.slg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.ops)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.opsp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.tb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sf}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.s}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.dp}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sección de Lanzadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mt-8 mb-4 text-black">Lanzadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-black ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">W</th>
            <th className="border border-gray-300 p-2">L</th>
            <th className="border border-gray-300 p-2">PCT</th>
            <th className="border border-gray-300 p-2">ERA</th>
            <th className="border border-gray-300 p-2">ERA+</th>
            <th className="border border-gray-300 p-2">GP</th>
            <th className="border border-gray-300 p-2">GS</th>
            <th className="border border-gray-300 p-2">CG</th>
            <th className="border border-gray-300 p-2">SHO</th>
            <th className="border border-gray-300 p-2">SV</th>
            <th className="border border-gray-300 p-2">IP</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">R</th>
            <th className="border border-gray-300 p-2">ER</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">WP</th>
            <th className="border border-gray-300 p-2">BE</th>
            <th className="border border-gray-300 p-2">DEC</th>
            <th className="border border-gray-300 p-2">BS</th>
            <th className="border border-gray-300 p-2">WHIP</th>
            <th className="border border-gray-300 p-2">FIP</th>
          </tr>
              </thead>
              <tbody>
                {filteredPitchers.map((pitcher, index) => (
                  <tr key={index} className={pitcher.nombre === "Totales" ? "bg-red-400 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-red-500 bg-black">{pitcher.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.w}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.l}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.pct.toFixed(3)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.era.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.eraplus}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.cg}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sho}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sv}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ip}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.r}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.er}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.wp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.be}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.dec}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.whip.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.fip.toFixed(2)}</td>
              </tr>
                  
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}