"use client"

import React, { useState } from 'react';

// Datos de los bateadores (mantenidos igual)
const batters = [
  {
    "nombre": "Troy Johnston",
      "edad": 27,
      "pos": "1B",
      "jj": 44,
      "app": 186,
      "ab": 163,
      "c": 13,
      "h": 41,
      "b1": 31,
      "b2": 9,
      "b3": 0,
      "hr": 1,
      "rbi": 27,
      "bb": 19,
      "so": 29,
      "sb": 4,
      "cs": 0,
      "avg": 0.252,
      "obp": 0.339,
      "slg": 0.325,
      "ops": 0.664,
      "opsp": 98,
      "tb": 53,
      "hbp": 3,
      "ibb": 1,
      "sf": 1,
      "s": 0,
      "dp": 6
    },
    {
      "nombre": "Gustavo Núñez",
      "edad": 36,
      "pos": "SS",
      "jj": 41,
      "app": 158,
      "ab": 144,
      "c": 23,
      "h": 29,
      "b1": 26,
      "b2": 1,
      "b3": 0,
      "hr": 2,
      "rbi": 9,
      "bb": 12,
      "so": 27,
      "sb": 12,
      "cs": 1,
      "avg": 0.201,
      "obp": 0.261,
      "slg": 0.25,
      "ops": 0.511,
      "opsp": 75,
      "tb": 36,
      "hbp": 0,
      "ibb": 0,
      "sf": 1,
      "s": 1,
      "dp": 3
    },
    {
      "nombre": "Cristhian Adames",
      "edad": 33,
      "pos": "SS",
      "jj": 35,
      "app": 124,
      "ab": 103,
      "c": 4,
      "h": 24,
      "b1": 19,
      "b2": 3,
      "b3": 1,
      "hr": 1,
      "rbi": 7,
      "bb": 13,
      "so": 24,
      "sb": 2,
      "cs": 2,
      "avg": 0.233,
      "obp": 0.333,
      "slg": 0.311,
      "ops": 0.644,
      "opsp": 95,
      "tb": 32,
      "hbp": 3,
      "ibb": 1,
      "sf": 1,
      "s": 4,
      "dp": 2
    },
    {
      "nombre": "Webster Rivas",
      "edad": 34,
      "pos": "C",
      "jj": 35,
      "app": 79,
      "ab": 69,
      "c": 6,
      "h": 16,
      "b1": 12,
      "b2": 4,
      "b3": 0,
      "hr": 0,
      "rbi": 2,
      "bb": 8,
      "so": 18,
      "sb": 0,
      "cs": 0,
      "avg": 0.232,
      "obp": 0.312,
      "slg": 0.29,
      "ops": 0.602,
      "opsp": 89,
      "tb": 20,
      "hbp": 0,
      "ibb": 0,
      "sf": 0,
      "s": 2,
      "dp": 1
    },
    {
      "nombre": "Engel Beltré",
      "edad": 35,
      "pos": "CF",
      "jj": 34,
      "app": 57,
      "ab": 52,
      "c": 7,
      "h": 10,
      "b1": 9,
      "b2": 1,
      "b3": 0,
      "hr": 0,
      "rbi": 2,
      "bb": 4,
      "so": 7,
      "sb": 2,
      "cs": 1,
      "avg": 0.192,
      "obp": 0.25,
      "slg": 0.212,
      "ops": 0.462,
      "opsp": 68,
      "tb": 11,
      "hbp": 0,
      "ibb": 0,
      "sf": 0,
      "s": 1,
      "dp": 0
    },
    {
      "nombre": "Francisco Peña",
      "edad": 35,
      "pos": "C",
      "jj": 32,
      "app": 74,
      "ab": 66,
      "c": 7,
      "h": 16,
      "b1": 12,
      "b2": 2,
      "b3": 0,
      "hr": 2,
      "rbi": 10,
      "bb": 6,
      "so": 9,
      "sb": 1,
      "cs": 0,
      "avg": 0.242,
      "obp": 0.306,
      "slg": 0.364,
      "ops": 0.67,
      "opsp": 99,
      "tb": 24,
      "hbp": 0,
      "ibb": 0,
      "sf": 0,
      "s": 2,
      "dp": 2
    },
    {
      "nombre": "Iván Castillo",
      "edad": 29,
      "pos": "2B",
      "jj": 29,
      "app": 77,
      "ab": 67,
      "c": 5,
      "h": 14,
      "b1": 11,
      "b2": 2,
      "b3": 1,
      "hr": 0,
      "rbi": 6,
      "bb": 8,
      "so": 10,
      "sb": 6,
      "cs": 1,
      "avg": 0.209,
      "obp": 0.312,
      "slg": 0.269,
      "ops": 0.581,
      "opsp": 86,
      "tb": 18,
      "hbp": 2,
      "ibb": 2,
      "sf": 0,
      "s": 0,
      "dp": 0
    },
    {
      "nombre": "Ronny Simon",
      "edad": 24,
      "pos": "LF",
      "jj": 29,
      "app": 126,
      "ab": 110,
      "c": 17,
      "h": 25,
      "b1": 17,
      "b2": 5,
      "b3": 3,
      "hr": 0,
      "rbi": 10,
      "bb": 13,
      "so": 21,
      "sb": 5,
      "cs": 3,
      "avg": 0.227,
      "obp": 0.312,
      "slg": 0.327,
      "ops": 0.639,
      "opsp": 94,
      "tb": 36,
      "hbp": 1,
      "ibb": 0,
      "sf": 1,
      "s": 1,
      "dp": 2
    },
    {
      "nombre": "Luis Valdez",
      "edad": 24,
      "pos": "PR",
      "jj": 29,
      "app": 40,
      "ab": 35,
      "c": 11,
      "h": 9,
      "b1": 9,
      "b2": 0,
      "b3": 0,
      "hr": 0,
      "rbi": 2,
      "bb": 4,
      "so": 11,
      "sb": 8,
      "cs": 2,
      "avg": 0.257,
      "obp": 0.333,
      "slg": 0.257,
      "ops": 0.59,
      "opsp": 87,
      "tb": 9,
      "hbp": 0,
      "ibb": 0,
      "sf": 0,
      "s": 1,
      "dp": 1
    },
    {
      "nombre": "Pablo Reyes",
      "edad": 31,
      "pos": "3B",
      "jj": 25,
      "app": 100,
      "ab": 89,
      "c": 11,
      "h": 23,
      "b1": 16,
      "b2": 5,
      "b3": 2,
      "hr": 0,
      "rbi": 6,
      "bb": 9,
      "so": 20,
      "sb": 4,
      "cs": 0,
      "avg": 0.258,
      "obp": 0.327,
      "slg": 0.36,
      "ops": 0.687,
      "opsp": 101,
      "tb": 32,
      "hbp": 0,
      "ibb": 0,
      "sf": 0,
      "s": 2,
      "dp": 1
    },
    {
      "nombre": "Luis Liberato",
      "edad": 29,
      "pos": "CF",
      "jj": 24,
      "app": 93,
      "ab": 83,
      "c": 13,
      "h": 22,
      "b1": 12,
      "b2": 6,
      "b3": 1,
      "hr": 3,
      "rbi": 13,
      "bb": 7,
      "so": 17,
      "sb": 3,
      "cs": 1,
      "avg": 0.265,
      "obp": 0.326,
      "slg": 0.47,
      "ops": 0.796,
      "opsp": 118,
      "tb": 39,
      "hbp": 1,
      "ibb": 3,
      "sf": 1,
      "s": 1,
      "dp": 0
    },{
        "nombre": "Yairo Muñoz",
        "edad": 29,
        "pos": "3B",
        "jj": 21,
        "app": 75,
        "ab": 67,
        "c": 8,
        "h": 15,
        "b1": 13,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 6,
        "bb": 5,
        "so": 15,
        "sb": 3,
        "cs": 1,
        "avg": 0.224,
        "obp": 0.293,
        "slg": 0.254,
        "ops": 0.547,
        "opsp": 81,
        "tb": 17,
        "hbp": 2,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Sandro Fabián",
        "edad": 26,
        "pos": "RF",
        "jj": 20,
        "app": 81,
        "ab": 69,
        "c": 12,
        "h": 18,
        "b1": 10,
        "b2": 3,
        "b3": 0,
        "hr": 5,
        "rbi": 13,
        "bb": 7,
        "so": 16,
        "sb": 1,
        "cs": 0,
        "avg": 0.261,
        "obp": 0.346,
        "slg": 0.522,
        "ops": 0.868,
        "opsp": 128,
        "tb": 36,
        "hbp": 3,
        "ibb": 1,
        "sf": 2,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Wendell Rijo",
        "edad": 29,
        "pos": "PH",
        "jj": 19,
        "app": 33,
        "ab": 28,
        "c": 5,
        "h": 8,
        "b1": 4,
        "b2": 3,
        "b3": 0,
        "hr": 1,
        "rbi": 4,
        "bb": 3,
        "so": 9,
        "sb": 1,
        "cs": 0,
        "avg": 0.286,
        "obp": 0.375,
        "slg": 0.5,
        "ops": 0.875,
        "opsp": 129,
        "tb": 14,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 1,
        "dp": 2
      },
      {
        "nombre": "Yeison Asencio",
        "edad": 35,
        "pos": "DH",
        "jj": 19,
        "app": 48,
        "ab": 45,
        "c": 5,
        "h": 14,
        "b1": 12,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 1,
        "so": 4,
        "sb": 1,
        "cs": 1,
        "avg": 0.311,
        "obp": 0.354,
        "slg": 0.356,
        "ops": 0.71,
        "opsp": 105,
        "tb": 16,
        "hbp": 2,
        "ibb": 1,
        "sf": 0,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Aneury Tavárez",
        "edad": 32,
        "pos": "RF",
        "jj": 17,
        "app": 30,
        "ab": 27,
        "c": 4,
        "h": 6,
        "b1": 6,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 4,
        "bb": 2,
        "so": 7,
        "sb": 1,
        "cs": 1,
        "avg": 0.222,
        "obp": 0.3,
        "slg": 0.222,
        "ops": 0.522,
        "opsp": 77,
        "tb": 6,
        "hbp": 1,
        "ibb": 1,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "TJ Rumfield",
        "edad": 24,
        "pos": "1B",
        "jj": 17,
        "app": 54,
        "ab": 54,
        "c": 2,
        "h": 8,
        "b1": 7,
        "b2": 0,
        "b3": 0,
        "hr": 1,
        "rbi": 4,
        "bb": 0,
        "so": 8,
        "sb": 0,
        "cs": 1,
        "avg": 0.148,
        "obp": 0.148,
        "slg": 0.204,
        "ops": 0.352,
        "opsp": 52,
        "tb": 11,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Alfredo Marte",
        "edad": 35,
        "pos": "LF",
        "jj": 15,
        "app": 48,
        "ab": 46,
        "c": 4,
        "h": 11,
        "b1": 9,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 2,
        "so": 8,
        "sb": 0,
        "cs": 0,
        "avg": 0.239,
        "obp": 0.271,
        "slg": 0.283,
        "ops": 0.554,
        "opsp": 82,
        "tb": 13,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Rafael Lantigua",
        "edad": 26,
        "pos": "2B",
        "jj": 14,
        "app": 49,
        "ab": 38,
        "c": 4,
        "h": 7,
        "b1": 6,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 9,
        "bb": 7,
        "so": 7,
        "sb": 3,
        "cs": 1,
        "avg": 0.184,
        "obp": 0.313,
        "slg": 0.211,
        "ops": 0.524,
        "opsp": 77,
        "tb": 8,
        "hbp": 1,
        "ibb": 0,
        "sf": 2,
        "s": 1,
        "dp": 0
      },
      {
        "nombre": "Emmanuel Rivera",
        "edad": 28,
        "pos": "3B",
        "jj": 13,
        "app": 54,
        "ab": 52,
        "c": 3,
        "h": 11,
        "b1": 8,
        "b2": 1,
        "b3": 0,
        "hr": 2,
        "rbi": 9,
        "bb": 2,
        "so": 14,
        "sb": 0,
        "cs": 0,
        "avg": 0.212,
        "obp": 0.241,
        "slg": 0.346,
        "ops": 0.587,
        "opsp": 87,
        "tb": 18,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Bryan De La Cruz",
        "edad": 28,
        "pos": "RF",
        "jj": 12,
        "app": 49,
        "ab": 42,
        "c": 2,
        "h": 12,
        "b1": 9,
        "b2": 2,
        "b3": 0,
        "hr": 1,
        "rbi": 6,
        "bb": 6,
        "so": 6,
        "sb": 2,
        "cs": 0,
        "avg": 0.286,
        "obp": 0.367,
        "slg": 0.405,
        "ops": 0.772,
        "opsp": 114,
        "tb": 17,
        "hbp": 0,
        "ibb": 2,
        "sf": 1,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Alen Hanson",
        "edad": 32,
        "pos": "PH",
        "jj": 10,
        "app": 21,
        "ab": 17,
        "c": 4,
        "h": 1,
        "b1": 0,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 2,
        "so": 4,
        "sb": 1,
        "cs": 0,
        "avg": 0.059,
        "obp": 0.158,
        "slg": 0.118,
        "ops": 0.276,
        "opsp": 41,
        "tb": 2,
        "hbp": 0,
        "ibb": 1,
        "sf": 0,
        "s": 2,
        "dp": 0
      },
      {
        "nombre": "José Rojas",
        "edad": 31,
        "pos": "DH",
        "jj": 9,
        "app": 29,
        "ab": 25,
        "c": 2,
        "h": 4,
        "b1": 2,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 2,
        "bb": 3,
        "so": 11,
        "sb": 0,
        "cs": 0,
        "avg": 0.16,
        "obp": 0.241,
        "slg": 0.24,
        "ops": 0.481,
        "opsp": 71,
        "tb": 6,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Mike Antico",
        "edad": 26,
        "pos": "CF",
        "jj": 9,
        "app": 23,
        "ab": 22,
        "c": 3,
        "h": 4,
        "b1": 3,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 7,
        "sb": 0,
        "cs": 1,
        "avg": 0.182,
        "obp": 0.217,
        "slg": 0.227,
        "ops": 0.444,
        "opsp": 66,
        "tb": 5,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Kennys Vargas",
        "edad": 34,
        "pos": "DH",
        "jj": 8,
        "app": 33,
        "ab": 29,
        "c": 3,
        "h": 5,
        "b1": 2,
        "b2": 1,
        "b3": 0,
        "hr": 2,
        "rbi": 3,
        "bb": 4,
        "so": 16,
        "sb": 0,
        "cs": 0,
        "avg": 0.172,
        "obp": 0.273,
        "slg": 0.414,
        "ops": 0.687,
        "opsp": 101,
        "tb": 12,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 2
      },
      {
        "nombre": "Denzer Guzmán",
        "edad": 20,
        "pos": "SS",
        "jj": 8,
        "app": 25,
        "ab": 25,
        "c": 1,
        "h": 5,
        "b1": 4,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 3,
        "bb": 0,
        "so": 9,
        "sb": 0,
        "cs": 0,
        "avg": 0.2,
        "obp": 0.2,
        "slg": 0.24,
        "ops": 0.44,
        "opsp": 65,
        "tb": 6,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Christopher Familia",
        "edad": 24,
        "pos": "PH",
        "jj": 7,
        "app": 14,
        "ab": 13,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 6,
        "sb": 0,
        "cs": 0,
        "avg": 0,
        "obp": 0.071,
        "slg": 0,
        "ops": 0.071,
        "opsp": 10,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },    {
        "nombre": "Elih Marrero",
        "edad": 27,
        "pos": "C",
        "jj": 7,
        "app": 13,
        "ab": 12,
        "c": 1,
        "h": 3,
        "b1": 1,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 0,
        "so": 7,
        "sb": 1,
        "cs": 1,
        "avg": 0.250,
        "obp": 0.231,
        "slg": 0.417,
        "ops": 0.648,
        "opsp": 96,
        "tb": 5,
        "hbp": 0,
        "ibb": 0,
        "sf": 1,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Ronny Rodríguez",
        "edad": 32,
        "pos": "PH",
        "jj": 5,
        "app": 3,
        "ab": 3,
        "c": 1,
        "h": 1,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.333,
        "obp": 0.333,
        "slg": 0.333,
        "ops": 0.666,
        "opsp": 98,
        "tb": 1,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Jeimer Candelario",
        "edad": 31,
        "pos": "3B",
        "jj": 5,
        "app": 18,
        "ab": 16,
        "c": 0,
        "h": 5,
        "b1": 4,
        "b2": 1,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 3,
        "sb": 0,
        "cs": 0,
        "avg": 0.313,
        "obp": 0.389,
        "slg": 0.375,
        "ops": 0.764,
        "opsp": 113,
        "tb": 6,
        "hbp": 1,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Jesús Sánchez",
        "edad": 27,
        "pos": "RF",
        "jj": 4,
        "app": 14,
        "ab": 13,
        "c": 0,
        "h": 3,
        "b1": 1,
        "b2": 2,
        "b3": 0,
        "hr": 0,
        "rbi": 1,
        "bb": 1,
        "so": 3,
        "sb": 0,
        "cs": 0,
        "avg": 0.231,
        "obp": 0.286,
        "slg": 0.385,
        "ops": 0.671,
        "opsp": 99,
        "tb": 5,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Phillip Evans",
        "edad": 32,
        "pos": "1B",
        "jj": 4,
        "app": 13,
        "ab": 12,
        "c": 0,
        "h": 1,
        "b1": 1,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 1,
        "so": 4,
        "sb": 0,
        "cs": 1,
        "avg": 0.083,
        "obp": 0.154,
        "slg": 0.083,
        "ops": 0.237,
        "opsp": 35,
        "tb": 1,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 1
      },
      {
        "nombre": "Carlos Castro",
        "edad": 30,
        "pos": "1B",
        "jj": 2,
        "app": 7,
        "ab": 7,
        "c": 1,
        "h": 4,
        "b1": 3,
        "b2": 0,
        "b3": 1,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.571,
        "obp": 0.571,
        "slg": 0.857,
        "ops": 1.428,
        "opsp": 211,
        "tb": 6,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Tito Polo",
        "edad": 30,
        "pos": "PR",
        "jj": 1,
        "app": 0,
        "ab": 0,
        "c": 1,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 0,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Seuly Matias",
        "edad": 26,
        "pos": "PH",
        "jj": 1,
        "app": 1,
        "ab": 1,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 0,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Jonatan Clase",
        "edad": 22,
        "pos": "CF",
        "jj": 1,
        "app": 3,
        "ab": 3,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 2,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },
      {
        "nombre": "Luis Mieses",
        "edad": 24,
        "pos": "PH",
        "jj": 1,
        "app": 2,
        "ab": 2,
        "c": 0,
        "h": 0,
        "b1": 0,
        "b2": 0,
        "b3": 0,
        "hr": 0,
        "rbi": 0,
        "bb": 0,
        "so": 1,
        "sb": 0,
        "cs": 0,
        "avg": 0.000,
        "obp": 0.000,
        "slg": 0.000,
        "ops": 0.000,
        "opsp": 0,
        "tb": 0,
        "hbp": 0,
        "ibb": 0,
        "sf": 0,
        "s": 0,
        "dp": 0
      },{
        "nombre": "Totales",
        "edad": 29,
        "pos": "",
        "jj": 606,
        "app": 1854,
        "ab": 1649,
        "c": 183,
        "h": 375,
        "b1": 280,
        "b2": 65,
        "b3": 9,
        "hr": 21,
        "rbi": 164,
        "bb": 152,
        "so": 362,
        "sb": 61,
        "cs": 19,
        "avg": 0.227,
        "obp": 0.299,
        "slg": 0.316,
        "ops": 0.615,
        "opsp": 0,
        "tb": 521,
        "hbp": 21,
        "ibb": 13,
        "sf": 13,
        "s": 19,
        "dp": 30
    }
  

];

// Datos de los lanzadores (mantenidos igual)
const pitchers = [
  {
    "nombre": "Joe Corbett",
    "edad": 28,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 1.37,
    "eraplus": 279,
    "gp": 23,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 19.2,
    "h": 9,
    "r": 3,
    "er": 3,
    "hr": 1,
    "bb": 4,
    "ibb": 0,
    "so": 23,
    "hbp": 1,
    "wp": 0,
    "be": 72,
    "dec": 1,
    "bs": 0,
    "whip": 0.66,
    "fip": 2.42
  },
  {
    "nombre": "Fernando Abad",
    "edad": 39,
    "w": 4,
    "l": 2,
    "pct": 0.667,
    "era": 1.09,
    "eraplus": 350,
    "gp": 20,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 6,
    "ip": 24.2,
    "h": 18,
    "r": 7,
    "er": 3,
    "hr": 0,
    "bb": 4,
    "ibb": 2,
    "so": 28,
    "hbp": 1,
    "wp": 1,
    "be": 101,
    "dec": 6,
    "bs": 0,
    "whip": 0.89,
    "fip": 1.67
  },
  {
    "nombre": "Chester Pimentel",
    "edad": 29,
    "w": 0,
    "l": 2,
    "pct": 0.000,
    "era": 4.91,
    "eraplus": 78,
    "gp": 20,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.2,
    "h": 12,
    "r": 10,
    "er": 8,
    "hr": 1,
    "bb": 9,
    "ibb": 1,
    "so": 8,
    "hbp": 0,
    "wp": 1,
    "be": 60,
    "dec": 2,
    "bs": 0,
    "whip": 1.43,
    "fip": 4.97
  },
  {
    "nombre": "Emailin Montilla",
    "edad": 29,
    "w": 1,
    "l": 2,
    "pct": 0.333,
    "era": 3.95,
    "eraplus": 97,
    "gp": 18,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 13.2,
    "h": 14,
    "r": 10,
    "er": 6,
    "hr": 1,
    "bb": 8,
    "ibb": 0,
    "so": 18,
    "hbp": 0,
    "wp": 1,
    "be": 65,
    "dec": 3,
    "bs": 0,
    "whip": 1.61,
    "fip": 3.41
  },
  {
    "nombre": "Diógenes Almengó",
    "edad": 29,
    "w": 2,
    "l": 3,
    "pct": 0.400,
    "era": 6.59,
    "eraplus": 58,
    "gp": 17,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 13.2,
    "h": 15,
    "r": 12,
    "er": 10,
    "hr": 1,
    "bb": 6,
    "ibb": 0,
    "so": 14,
    "hbp": 0,
    "wp": 0,
    "be": 61,
    "dec": 5,
    "bs": 0,
    "whip": 1.54,
    "fip": 3.55
  },
  {
    "nombre": "Yaramil Hiraldo",
    "edad": 29,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 4.09,
    "eraplus": 93,
    "gp": 14,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 11,
    "h": 10,
    "r": 5,
    "er": 5,
    "hr": 1,
    "bb": 6,
    "ibb": 0,
    "so": 13,
    "hbp": 0,
    "wp": 2,
    "be": 48,
    "dec": 1,
    "bs": 0,
    "whip": 1.45,
    "fip": 3.79
  },
  {
    "nombre": "Cristopher Molina",
    "edad": 27,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 11,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14,
    "h": 20,
    "r": 15,
    "er": 14,
    "hr": 0,
    "bb": 5,
    "ibb": 0,
    "so": 5,
    "hbp": 4,
    "wp": 2,
    "be": 70,
    "dec": 1,
    "bs": 0,
    "whip": 1.79,
    "fip": 4.55
  },
  {
    "nombre": "Esmil Rogers",
    "edad": 39,
    "w": 3,
    "l": 2,
    "pct": 0.600,
    "era": 3.04,
    "eraplus": 126,
    "gp": 10,
    "gs": 10,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 47.1,
    "h": 43,
    "r": 19,
    "er": 16,
    "hr": 4,
    "bb": 13,
    "ibb": 0,
    "so": 29,
    "hbp": 2,
    "wp": 1,
    "be": 193,
    "dec": 5,
    "bs": 0,
    "whip": 1.18,
    "fip": 4.16
  },
  {
    "nombre": "Luis Santos",
    "edad": 33,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 2.89,
    "eraplus": 132,
    "gp": 10,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 9.1,
    "h": 6,
    "r": 3,
    "er": 3,
    "hr": 2,
    "bb": 5,
    "ibb": 0,
    "so": 4,
    "hbp": 0,
    "wp": 0,
    "be": 36,
    "dec": 0,
    "bs": 0,
    "whip": 1.18,
    "fip": 6.87
  },
  {
    "nombre": "Matt Dermody",
    "edad": 34,
    "w": 1,
    "l": 3,
    "pct": 0.250,
    "era": 3.05,
    "eraplus": 125,
    "gp": 10,
    "gs": 10,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 41.1,
    "h": 47,
    "r": 18,
    "er": 14,
    "hr": 2,
    "bb": 11,
    "ibb": 0,
    "so": 39,
    "hbp": 1,
    "wp": 1,
    "be": 181,
    "dec": 4,
    "bs": 0,
    "whip": 1.40,
    "fip": 2.95
  },
  {
    "nombre": "Tanner Kiest",
    "edad": 30,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 10,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 9,
    "h": 3,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 14,
    "hbp": 1,
    "wp": 1,
    "be": 30,
    "dec": 0,
    "bs": 0,
    "whip": 0.44,
    "fip": 0.89
  },
  {
    "nombre": "Justin Courtney",
    "edad": 28,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 4.82,
    "eraplus": 79,
    "gp": 10,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 9.1,
    "h": 7,
    "r": 5,
    "er": 5,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 6,
    "hbp": 1,
    "wp": 0,
    "be": 38,
    "dec": 1,
    "bs": 0,
    "whip": 1.07,
    "fip": 3.33
  },
  {
    "nombre": "José Adames",
    "edad": 31,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 6.43,
    "eraplus": 59,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 7,
    "h": 5,
    "r": 5,
    "er": 5,
    "hr": 0,
    "bb": 7,
    "ibb": 0,
    "so": 8,
    "hbp": 0,
    "wp": 5,
    "be": 33,
    "dec": 1,
    "bs": 0,
    "whip": 1.71,
    "fip": 4.05
  },
  {
    "nombre": "RJ Alaniz",
    "edad": 33,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 1.69,
    "eraplus": 226,
    "gp": 9,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 10.2,
    "h": 13,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 4,
    "ibb": 0,
    "so": 8,
    "hbp": 0,
    "wp": 1,
    "be": 46,
    "dec": 0,
    "bs": 1,
    "whip": 1.59,
    "fip": 2.96
  },
  {
    "nombre": "Rafael Dolis",
    "edad": 37,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 6.75,
    "eraplus": 57,
    "gp": 8,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 6.2,
    "h": 12,
    "r": 5,
    "er": 5,
    "hr": 1,
    "bb": 2,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 32,
    "dec": 0,
    "bs": 0,
    "whip": 2.10,
    "fip": 6.18
  },
  {
    "nombre": "Joel Peguero",
    "edad": 27,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 7.94,
    "eraplus": 48,
    "gp": 8,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5.2,
    "h": 9,
    "r": 6,
    "er": 5,
    "hr": 0,
    "bb": 3,
    "ibb": 1,
    "so": 4,
    "hbp": 0,
    "wp": 0,
    "be": 30,
    "dec": 1,
    "bs": 0,
    "whip": 2.12,
    "fip": 3.51
  },
  {
    "nombre": "Rubby De La Rosa",
    "edad": 35,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 5.68,
    "eraplus": 67,
    "gp": 8,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 6.1,
    "h": 4,
    "r": 4,
    "er": 4,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 4,
    "hbp": 1,
    "wp": 0,
    "be": 27,
    "dec": 0,
    "bs": 0,
    "whip": 1.11,
    "fip": 3.97
  },
  {
    "nombre": "Franklyn Kilomé",
    "edad": 30,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 3.65,
    "eraplus": 105,
    "gp": 8,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 12.1,
    "h": 11,
    "r": 6,
    "er": 5,
    "hr": 1,
    "bb": 4,
    "ibb": 1,
    "so": 14,
    "hbp": 1,
    "wp": 2,
    "be": 52,
    "dec": 1,
    "bs": 0,
    "whip": 1.22,
    "fip": 3.33
  },
  {
    "nombre": "Félix Peña",
    "edad": 34,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 6.91,
    "eraplus": 55,
    "gp": 7,
    "gs": 3,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 14.1,
    "h": 19,
    "r": 13,
    "er": 11,
    "hr": 1,
    "bb": 7,
    "ibb": 0,
    "so": 11,
    "hbp": 0,
    "wp": 3,
    "be": 68,
    "dec": 1,
    "bs": 0,
    "whip": 1.81,
    "fip": 4.17
  },
  {
    "nombre": "José José",
    "edad": 34,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 5.06,
    "eraplus": 75,
    "gp": 6,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 5.1,
    "h": 6,
    "r": 4,
    "er": 3,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 5,
    "hbp": 0,
    "wp": 1,
    "be": 25,
    "dec": 0,
    "bs": 0,
    "whip": 1.69,
    "fip": 3.15
  },
  {
    "nombre": "Jenrry Mejía",
    "edad": 35,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 3.86,
    "eraplus": 99,
    "gp": 5,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.2,
    "h": 6,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 1,
    "be": 20,
    "dec": 1,
    "bs": 0,
    "whip": 1.29,
    "fip": 3.33
  },
  {
    "nombre": "Paolo Espino",
    "edad": 38,
    "w": 0,
    "l": 2,
    "pct": 0.000,
    "era": 7.02,
    "eraplus": 54,
    "gp": 5,
    "gs": 4,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 16.2,
    "h": 17,
    "r": 13,
    "er": 13,
    "hr": 4,
    "bb": 4,
    "ibb": 0,
    "so": 13,
    "hbp": 1,
    "wp": 1,
    "be": 71,
    "dec": 2,
    "bs": 0,
    "whip": 1.26,
    "fip": 5.80
  },
  {
    "nombre": "Jimmy Yacabonis",
    "edad": 32,
    "w": 1,
    "l": 0,
    "pct": 1.000,
    "era": 4.50,
    "eraplus": 85,
    "gp": 5,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4,
    "h": 2,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 16,
    "dec": 1,
    "bs": 0,
    "whip": 1.00,
    "fip": 4.33
  },
  {
    "nombre": "Antonio Jiménez",
    "edad": 23,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 8.31,
    "eraplus": 46,
    "gp": 5,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.1,
    "h": 7,
    "r": 4,
    "er": 4,
    "hr": 1,
    "bb": 5,
    "ibb": 0,
    "so": 4,
    "hbp": 0,
    "wp": 0,
    "be": 23,
    "dec": 1,
    "bs": 0,
    "whip": 2.77,
    "fip": 7.95
  },
  {
    "nombre": "Anthony Gose",
    "edad": 34,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 3,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 1,
    "be": 12,
    "dec": 0,
    "bs": 0,
    "whip": 2.50,
    "fip": 5.34
  },
  {
    "nombre": "Jaime Barría",
    "edad": 28,
    "w": 1,
    "l": 2,
    "pct": 0.333,
    "era": 3.12,
    "eraplus": 122,
    "gp": 4,
    "gs": 4,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 17.1,
    "h": 12,
    "r": 7,
    "er": 6,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 14,
    "hbp": 0,
    "wp": 0,
    "be": 68,
    "dec": 3,
    "bs": 0,
    "whip": 0.81,
    "fip": 2.07
  },
  {
    "nombre": "Wendolyn Bautista",
    "edad": 31,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 5.40,
    "eraplus": 71,
    "gp": 4,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 6.2,
    "h": 4,
    "r": 4,
    "er": 4,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 6,
    "hbp": 0,
    "wp": 0,
    "be": 27,
    "dec": 1,
    "bs": 0,
    "whip": 1.05,
    "fip": 2.89
  },
  {
    "nombre": "Pedro Fernández",
    "edad": 30,
    "w": 0,
    "l": 2,
    "pct": 0.000,
    "era": 5.12,
    "eraplus": 75,
    "gp": 4,
    "gs": 4,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 19.1,
    "h": 21,
    "r": 11,
    "er": 11,
    "hr": 3,
    "bb": 3,
    "ibb": 0,
    "so": 17,
    "hbp": 0,
    "wp": 1,
    "be": 80,
    "dec": 2,
    "bs": 0,
    "whip": 1.24,
    "fip": 4.06
  },
  {
    "nombre": "Domingo Germán",
    "edad": 32,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 7.71,
    "eraplus": 50,
    "gp": 4,
    "gs": 4,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 11.2,
    "h": 14,
    "r": 11,
    "er": 10,
    "hr": 0,
    "bb": 6,
    "ibb": 0,
    "so": 14,
    "hbp": 1,
    "wp": 1,
    "be": 55,
    "dec": 1,
    "bs": 0,
    "whip": 1.71,
    "fip": 2.73
  },  {
    "nombre": "Anderson Bidó",
    "edad": 25,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 2.25,
    "eraplus": 170,
    "gp": 4,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4,
    "h": 4,
    "r": 3,
    "er": 1,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 2,
    "hbp": 0,
    "wp": 1,
    "be": 18,
    "dec": 0,
    "bs": 0,
    "whip": 1.25,
    "fip": 3.08
  },
  {
    "nombre": "Alfredo Simón",
    "edad": 43,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 9.00,
    "eraplus": 42,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 3,
    "r": 3,
    "er": 2,
    "hr": 0,
    "bb": 2,
    "ibb": 1,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 13,
    "dec": 1,
    "bs": 0,
    "whip": 2.50,
    "fip": 5.33
  },
  {
    "nombre": "Jarlin García",
    "edad": 31,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 1,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 3,
    "hbp": 0,
    "wp": 0,
    "be": 8,
    "dec": 0,
    "bs": 0,
    "whip": 1.00,
    "fip": 1.83
  },
  {
    "nombre": "Chris Ellis",
    "edad": 32,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 3.86,
    "eraplus": 99,
    "gp": 3,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.2,
    "h": 4,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 7,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 25,
    "dec": 1,
    "bs": 0,
    "whip": 2.36,
    "fip": 7.41
  },
  {
    "nombre": "Teddy Stankiewicz",
    "edad": 31,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 4.97,
    "eraplus": 77,
    "gp": 3,
    "gs": 3,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 12.2,
    "h": 10,
    "r": 7,
    "er": 7,
    "hr": 1,
    "bb": 3,
    "ibb": 0,
    "so": 11,
    "hbp": 2,
    "wp": 0,
    "be": 52,
    "dec": 1,
    "bs": 0,
    "whip": 1.03,
    "fip": 3.81
  },
  {
    "nombre": "Jeff Kinley",
    "edad": 32,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 8.10,
    "eraplus": 47,
    "gp": 3,
    "gs": 2,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 6.2,
    "h": 10,
    "r": 6,
    "er": 6,
    "hr": 2,
    "bb": 5,
    "ibb": 0,
    "so": 11,
    "hbp": 0,
    "wp": 0,
    "be": 33,
    "dec": 0,
    "bs": 0,
    "whip": 2.25,
    "fip": 6.18
  },
  {
    "nombre": "Adam Ottavino",
    "edad": 39,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.00,
    "eraplus": 127,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 3,
    "h": 4,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 2,
    "hbp": 0,
    "wp": 0,
    "be": 12,
    "dec": 0,
    "bs": 0,
    "whip": 1.33,
    "fip": 2.00
  },
  {
    "nombre": "Juan Mateo",
    "edad": 32,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 6.75,
    "eraplus": 57,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4,
    "h": 3,
    "r": 3,
    "er": 3,
    "hr": 1,
    "bb": 3,
    "ibb": 0,
    "so": 2,
    "hbp": 1,
    "wp": 0,
    "be": 18,
    "dec": 0,
    "bs": 0,
    "whip": 1.50,
    "fip": 8.59
  },
  {
    "nombre": "Chris Devenski",
    "edad": 34,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 3.86,
    "eraplus": 99,
    "gp": 3,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.1,
    "h": 2,
    "r": 1,
    "er": 1,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 2,
    "hbp": 0,
    "wp": 1,
    "be": 9,
    "dec": 0,
    "bs": 0,
    "whip": 0.86,
    "fip": 1.62
  },
  {
    "nombre": "Michael Ynoa",
    "edad": 33,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 13.50,
    "eraplus": 28,
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1.3,
    "h": 3,
    "r": 2,
    "er": 2,
    "hr": 0,
    "bb": 2,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 9,
    "dec": 0,
    "bs": 0,
    "whip": 3.75,
    "fip": 7.84
  },
  {
    "nombre": "Olbis Parra",
    "edad": 30,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2.1,
    "h": 2,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 3,
    "hbp": 0,
    "wp": 1,
    "be": 10,
    "dec": 0,
    "bs": 0,
    "whip": 1.29,
    "fip": 2.05
  },
  {
    "nombre": "Wandisson Charles",
    "edad": 28,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 1,
    "r": 2,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 2,
    "hbp": 0,
    "wp": 0,
    "be": 9,
    "dec": 0,
    "bs": 0,
    "whip": 1.00,
    "fip": 2.83
  },
  {
    "nombre": "Alex Sanabia",
    "edad": 36,
    "w": 0,
    "l": 1,
    "pct": 0.000,
    "era": 10.39,
    "eraplus": 37,
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 4.1,
    "h": 7,
    "r": 5,
    "er": 5,
    "hr": 1,
    "bb": 1,
    "ibb": 0,
    "so": 4,
    "hbp": 0,
    "wp": 0,
    "be": 21,
    "dec": 1,
    "bs": 0,
    "whip": 1.85,
    "fip": 5.18
  },
  {
    "nombre": "Domingo Jiménez",
    "edad": 31,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 2,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1.1,
    "h": 2,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 6,
    "dec": 0,
    "bs": 0,
    "whip": 1.50,
    "fip": 1.83
  },
  {
    "nombre": "Joe Van Meter",
    "edad": 36,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 0.6,
    "h": 2,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 1,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 5,
    "dec": 0,
    "bs": 0,
    "whip": 4.50,
    "fip": 4.83
  },
  {
    "nombre": "Jumbo Díaz",
    "edad": 40,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 0.00,
    "eraplus": "Inf",
    "gp": 1,
    "gs": 0,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 1,
    "h": 1,
    "r": 0,
    "er": 0,
    "hr": 0,
    "bb": 0,
    "ibb": 0,
    "so": 0,
    "hbp": 0,
    "wp": 0,
    "be": 4,
    "dec": 0,
    "bs": 0,
    "whip": 1.00,
    "fip": 3.33
  },
  {
    "nombre": "Raúl Valdés",
    "edad": 47,
    "w": 0,
    "l": 0,
    "pct": 0.000,
    "era": 18.00,
    "eraplus": 21,
    "gp": 1,
    "gs": 1,
    "cg": 0,
    "sho": 0,
    "sv": 0,
    "ip": 2,
    "h": 5,
    "r": 4,
    "er": 4,
    "hr": 0,
    "bb": 3,
    "ibb": 0,
    "so": 1,
    "hbp": 0,
    "wp": 0,
    "be": 14,
    "dec": 0,
    "bs": 0,
    "whip": 4.00,
    "fip": 6.83
  },{
    "nombre": "Totales",
    "edad": 33,
    "w": 17,
    "l": 32,
    "pct": 0.347,
    "era": 4.41,
    "eraplus": 0,
    "gp": 317,
    "gs": 49,
    "cg": 0,
    "sho": 0,
    "sv": 6,
    "ip": 439,
    "h": 433,
    "r": 249,
    "er": 215,
    "hr": 29,
    "bb": 166,
    "ibb": 6,
    "so": 372,
    "hbp": 18,
    "wp": 30,
    "be": 1906,
    "dec": 49,
    "bs": 1,
    "whip": 1.36,
    "fip": 0.00
  }
];

function formatNumber(value: number): string {
  return value === 0 ? ".000" : value.toString().replace("0.", ".");
}

export default function Page() {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredBatters = batters.filter((jugador) =>
    jugador.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredPitchers = pitchers.filter((pitcher) =>
    pitcher.nombre.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-orange-500">
      {/* Encabezado con imagen difuminada */}
      <header className="relative h-64 shadow-xl">
        <div className="absolute inset-0 z-0">
          <img
            src="/Logos/torosdeleste.png"
            alt="Estadio de béisbol"
            className="object-cover  h-full blur-s "
          />
          <div className="absolute inset-0 bg-black/30" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-4xl font-bold text-white mb-4 drop-shadow-lg">
            Estadísticas de Los Toros del Este
          </h1>
          <p className="text-xl text-white/90 drop-shadow-md">
          Temporada 2024 Serie Regular
          </p>
        </div>
      </header>

      {/* Contenido principal */}
      <div className="p-6 max-w-9xl mx-auto">
        {/* Barra de búsqueda */}
        <div className="mb-6">
          <input
            type="text"
            placeholder="Buscar jugador..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-white focus:border-transparent shadow-sm"
          />
        </div>

        {/* Sección de Bateadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mb-4 text-black">Bateadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-orange-500 text-white ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">POS</th>
            <th className="border border-gray-300 p-2">JJ</th>
            <th className="border border-gray-300 p-2">APP</th>
            <th className="border border-gray-300 p-2">AB</th>
            <th className="border border-gray-300 p-2">C</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">1B</th>
            <th className="border border-gray-300 p-2">2B</th>
            <th className="border border-gray-300 p-2">3B</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">RBI</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">SB</th>
            <th className="border border-gray-300 p-2">CS</th>
            <th className="border border-gray-300 p-2">AVG</th>
            <th className="border border-gray-300 p-2">OBP</th>
            <th className="border border-gray-300 p-2">SLG</th>
            <th className="border border-gray-300 p-2">OPS</th>
            <th className="border border-gray-300 p-2">OPS+</th>
            <th className="border border-gray-300 p-2">TB</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SF</th>
            <th className="border border-gray-300 p-2">S</th>
            <th className="border border-gray-300 p-2">DP</th>
            
          </tr>
              </thead>
              <tbody>
                {filteredBatters.map((jugador, index) => (
                  <tr key={index} className={jugador.nombre === "Totales" ? "bg-orange-200 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-orange-500 bg-black">{jugador.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.pos}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.jj}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ab}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.app}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.c}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b1}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b2}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.b3}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.rbi}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.cs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.avg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.obp)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.slg)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(jugador.ops)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.opsp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.tb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.sf}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.s}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{jugador.dp}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sección de Lanzadores */}
        <div className="mb-12">
          <h1 className="text-2xl font-bold mt-8 mb-4 text-black">Lanzadores</h1>
          <div className="overflow-x-auto shadow-lg rounded-lg">
            <table className="w-full border-collapse bg-white">
              <thead>
              <tr className="bg-orange-500 ">
            <th className="border border-gray-300 p-2">Nombre</th>
            <th className="border border-gray-300 p-2">Edad</th>
            <th className="border border-gray-300 p-2">W</th>
            <th className="border border-gray-300 p-2">L</th>
            <th className="border border-gray-300 p-2">PCT</th>
            <th className="border border-gray-300 p-2">ERA</th>
            <th className="border border-gray-300 p-2">ERA+</th>
            <th className="border border-gray-300 p-2">GP</th>
            <th className="border border-gray-300 p-2">GS</th>
            <th className="border border-gray-300 p-2">CG</th>
            <th className="border border-gray-300 p-2">SHO</th>
            <th className="border border-gray-300 p-2">SV</th>
            <th className="border border-gray-300 p-2">IP</th>
            <th className="border border-gray-300 p-2">H</th>
            <th className="border border-gray-300 p-2">R</th>
            <th className="border border-gray-300 p-2">ER</th>
            <th className="border border-gray-300 p-2">HR</th>
            <th className="border border-gray-300 p-2">BB</th>
            <th className="border border-gray-300 p-2">IBB</th>
            <th className="border border-gray-300 p-2">SO</th>
            <th className="border border-gray-300 p-2">HBP</th>
            <th className="border border-gray-300 p-2">WP</th>
            <th className="border border-gray-300 p-2">BE</th>
            <th className="border border-gray-300 p-2">DEC</th>
            <th className="border border-gray-300 p-2">BS</th>
            <th className="border border-gray-300 p-2">WHIP</th>
            <th className="border border-gray-300 p-2">FIP</th>
          </tr>
              </thead>
              <tbody>
                {filteredPitchers.map((pitcher, index) => (
                  <tr key={index} className={pitcher.nombre === "Totales" ? "bg-orange-200 font-bold" : ""}>
                    <td className="border border-gray-300 p-2 text-orange-500 bg-black">{pitcher.nombre}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.edad}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.w}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.l}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{formatNumber(pitcher.pct)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.era.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.eraplus}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.gs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.cg}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sho}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.sv}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ip}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.h}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.r}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.er}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hr}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.ibb}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.so}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.hbp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.wp}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.be}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.dec}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.bs}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.whip.toFixed(2)}</td>
                <td className="border border-gray-300 p-2 text-center text-black">{pitcher.fip.toFixed(2)}</td>
              </tr>
                  
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}